--[[
	InstallMeatGlow.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Variant glow on MOVED meat. Silver / Gold meat glows in the blender, on the
	belt and on the stack (InstallFishVariants); every later hop is a fresh
	MeatTemplate clone that used to lose the glow. Now it keeps it:
	  * BotSystem: the piece the Blender Bot carries, and on the sale table
	  * CustomerSystem: the piece in the customer's hand
	  * TruckSystem: the stack a player carries, the pieces flying to the
	    truck, and the meat loaded in the truck
	Display only: it reads the Variant the ledger stamped on the piece; value
	and payment are unchanged. Without ReplicatedStorage.FishVariantVisuals the
	scripts behave exactly like before.
	BotSystem may be the sales version or the Blender Bot recovery version:
	install InstallBotRecovery.lua FIRST if you want it (it refuses after this).
	Requires: InstallFishVariants.lua (the visuals module, checked by source).

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyMeatGlowBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackMeatGlow.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallMeatGlow"
local BACKUP = "EconomyMeatGlowBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomyVariantsBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyMeatGlowBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "BotSystem", where = "script:BotSystem", class = "Script", variants = { { label = "sales", old = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

pose(0, 0)
while true do
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		continue
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then continue end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	meat:Destroy()
	local c = meatTemplate:Clone()
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	idle(0.25)
end
]], new = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

pose(0, 0)
while true do
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		continue
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then continue end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	meat:Destroy()
	local c = meatTemplate:Clone()
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	glow(c, c:GetAttribute("Variant")) -- MeatGlow: carried, then on the table
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	idle(0.25)
end
]] }, { label = "bot", old = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
--
-- [Bot recovery patch] Each trip runs under pcall. If anything errors while
-- the bot holds a piece (between the stack and the table), the loose clone is
-- removed and the piece is held in the ledger: the grinder brings it back out
-- of the pipe, so it is never lost unpaid. The bot then carries on (it used to
-- stop for good). Changes are marked "Recovery".
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

-- Recovery: the piece in the bot's hands, from leaving the stack until it lies
-- on the table ({ pieceId = id?, part = clone? })
local inHand = nil

local function trip()
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		return
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then return end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	inHand = { pieceId = tags and tags.PieceId } -- Recovery
	meat:Destroy()
	local c = meatTemplate:Clone()
	inHand.part = c -- Recovery
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	inHand = nil -- Recovery: on the table, the customer sale takes it from here
	idle(0.25)
end

-- Recovery: whatever the bot was holding goes back to the ledger (held: the
-- grinder re-emits it), never lost unpaid. (Once it lies on the table inHand
-- is already nil: the customer sale takes it from there.)
local function recover()
	carried = nil
	local h = inHand
	inHand = nil
	if not h then return end
	if Economy and h.pieceId then
		pcall(Economy.hold, h.pieceId)
	end
	if h.part then pcall(function() h.part:Destroy() end) end
end

pose(0, 0)
local fails = 0
while true do
	local ok, err = pcall(trip)
	if ok then
		fails = 0
	else
		fails += 1
		recover()
		if fails == 1 or fails % 20 == 0 then
			warn("[BotSystem] trip failed (" .. fails .. "x), piece kept, retrying: " .. tostring(err))
		end
		task.wait(math.min(5, fails)) -- back off while something stays broken
	end
end
]], new = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
--
-- [Bot recovery patch] Each trip runs under pcall. If anything errors while
-- the bot holds a piece (between the stack and the table), the loose clone is
-- removed and the piece is held in the ledger: the grinder brings it back out
-- of the pipe, so it is never lost unpaid. The bot then carries on (it used to
-- stop for good). Changes are marked "Recovery".
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

-- Recovery: the piece in the bot's hands, from leaving the stack until it lies
-- on the table ({ pieceId = id?, part = clone? })
local inHand = nil

local function trip()
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		return
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then return end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	inHand = { pieceId = tags and tags.PieceId } -- Recovery
	meat:Destroy()
	local c = meatTemplate:Clone()
	inHand.part = c -- Recovery
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	glow(c, c:GetAttribute("Variant")) -- MeatGlow: carried, then on the table
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	inHand = nil -- Recovery: on the table, the customer sale takes it from here
	idle(0.25)
end

-- Recovery: whatever the bot was holding goes back to the ledger (held: the
-- grinder re-emits it), never lost unpaid. (Once it lies on the table inHand
-- is already nil: the customer sale takes it from there.)
local function recover()
	carried = nil
	local h = inHand
	inHand = nil
	if not h then return end
	if Economy and h.pieceId then
		pcall(Economy.hold, h.pieceId)
	end
	if h.part then pcall(function() h.part:Destroy() end) end
end

pose(0, 0)
local fails = 0
while true do
	local ok, err = pcall(trip)
	if ok then
		fails = 0
	else
		fails += 1
		recover()
		if fails == 1 or fails % 20 == 0 then
			warn("[BotSystem] trip failed (" .. fails .. "x), piece kept, retrying: " .. tostring(err))
		end
		task.wait(math.min(5, fails)) -- back off while something stays broken
	end
end
]] } } },
	{ key = "CustomerSystem", where = "script:CustomerSystem", class = "Script", variants = { { label = "sales", old = [[
-- Customers: avatars of the server owner's friends walk out of the shops in the city,
-- down the sidewalk to the meat table at the end of the conveyor, buy a piece of meat
-- (if there is any), and walk back into the city.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- A customer's purchase is the piece's one sale: EconomyService pays the piece's
-- owner its ledger value. The tier is read before the piece is destroyed.
local Players = game:GetService("Players")
local PhysicsService = game:GetService("PhysicsService")
local SS = game:GetService("ServerStorage")

local folder = workspace:WaitForChild("Customers")
local saleMeat = workspace:WaitForChild("SaleMeat")
local meatTemplate = SS:WaitForChild("MeatTemplate")
local bought = SS:WaitForChild("CustomerEvents"):WaitForChild("CustomerBought")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[CustomerSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[CustomerSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- tuning
local SPAWN_DELAY = { 10, 20 }   -- seconds between new customers
local MAX_IN_LINE = 4
local WAIT_FOR_MEAT = 18         -- how long they wait at the table before giving up
local WALK_SPEED = 9

-- route (sidewalk from the shop doors to the table)
local Y = 9.3
local DOORS = {
	{ door = Vector3.new(-125.6, Y, 185), out = Vector3.new(-126.1, Y, 184) },
	{ door = Vector3.new(-125.6, Y, 202), out = Vector3.new(-126.1, Y, 201) },
}
local CORNER = Vector3.new(-126.1, Y, 163.1)
local DOCK = Vector3.new(-94, Y, 163.1)
local SLOTS = { -- slot 1 is at the sale table, the rest line up behind
	Vector3.new(-94.8, Y, 152.5),
	Vector3.new(-94.8, Y, 157.5),
	Vector3.new(-94.6, Y, 162.4),
	Vector3.new(-98.5, Y, 163.1),
	Vector3.new(-102.5, Y, 163.1),
	Vector3.new(-106.5, Y, 163.1),
	Vector3.new(-110.5, Y, 163.1),
	Vector3.new(-114.5, Y, 163.1),
}
local TABLE_LOOK = Vector3.new(-80, Y, 152.5)

-- R15 default animations
local ANIM_IDLE = "rbxassetid://507766388"
local ANIM_WALK = "rbxassetid://507777826"

pcall(function()
	PhysicsService:RegisterCollisionGroup("Customers")
	PhysicsService:CollisionGroupSetCollidable("Customers", "Customers", false)
end)

------------------------------------------------ friends list
local friendIds = {}
local fetched = false
local function fetchFriends(player)
	if fetched then return end
	fetched = true
	local ok, pages = pcall(function() return Players:GetFriendsAsync(player.UserId) end)
	if ok and pages then
		while true do
			for _, f in ipairs(pages:GetCurrentPage()) do table.insert(friendIds, f.Id) end
			if pages.IsFinished or #friendIds >= 60 then break end
			local ok2 = pcall(function() pages:AdvanceToNextPageAsync() end)
			if not ok2 then break end
		end
	end
	if #friendIds == 0 then table.insert(friendIds, player.UserId) end
end
Players.PlayerAdded:Connect(fetchFriends)
for _, p in ipairs(Players:GetPlayers()) do task.spawn(fetchFriends, p) end

local descCache = {}
local function makeAvatar()
	local id = #friendIds > 0 and friendIds[math.random(1, #friendIds)] or nil
	local desc
	if id then
		desc = descCache[id]
		if not desc then
			local ok, d = pcall(function() return Players:GetHumanoidDescriptionFromUserId(id) end)
			if ok then desc = d descCache[id] = d end
		end
	end
	desc = desc or Instance.new("HumanoidDescription")
	local ok, model = pcall(function() return Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R15) end)
	if not ok or not model then return nil end
	if id then
		local ok2, name = pcall(function() return Players:GetNameFromUserIdAsync(id) end)
		model.Name = ok2 and name or "Customer"
	else
		model.Name = "Customer"
	end
	local anim = model:FindFirstChild("Animate") if anim then anim:Destroy() end
	for _, p in ipairs(model:GetDescendants()) do
		if p:IsA("BasePart") then p.CollisionGroup = "Customers" end
	end
	return model
end

------------------------------------------------ customer behaviour
local line = {}

local function walkTo(c, pos)
	local hum = c.hum
	if not hum.Parent or hum.Health <= 0 then return false end
	hum:MoveTo(pos)
	local done = false
	local conn = hum.MoveToFinished:Connect(function() done = true end)
	local t = 0
	while not done and t < 12 do t += task.wait(0.1) end
	conn:Disconnect()
	return true
end

local function face(c, target)
	local hrp = c.hrp
	local look = Vector3.new(target.X, hrp.Position.Y, target.Z)
	hrp.CFrame = CFrame.lookAt(hrp.Position, look)
end

local function topOfStack() -- nearest meat on the sale table
	local best, bd = nil, math.huge
	for _, m in ipairs(saleMeat:GetChildren()) do
		if not m:GetAttribute("Sold") then
			local d = (m.Position - SLOTS[1]).Magnitude
			if d < bd then best, bd = m, d end
		end
	end
	if best then best:SetAttribute("Sold", true) end
	return best
end

local function giveMeat(c, meat)
	local from = meat.Position
	meat:Destroy()
	local hand = c.model:FindFirstChild("RightHand") or c.hrp
	local p = meatTemplate:Clone()
	p.Anchored = true
	p.Parent = workspace
	local to = c.hrp.Position + c.hrp.CFrame.LookVector * 1.2 + Vector3.new(0, 0.3, 0)
	local t = 0
	while t < 0.35 do
		t += task.wait()
		local u = math.min(t / 0.35, 1)
		p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, 3 * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
	end
	-- hold it in front of them
	p.Anchored = false
	p.Massless = true
	p.CanCollide = false
	p.CFrame = c.hrp.CFrame * CFrame.new(0, 0.2, -1.1) * CFrame.Angles(0, math.rad(90), 0)
	local w = Instance.new("WeldConstraint")
	w.Part0 = c.hrp w.Part1 = p w.Parent = p
	p.Parent = c.model
end

local function reposition()
	for i, c in ipairs(line) do
		if c.state == "queued" and c.slot ~= i then
			c.slot = i
			task.spawn(function()
				walkTo(c, SLOTS[math.min(i, #SLOTS)])
				if i == 1 then face(c, TABLE_LOOK) end
			end)
		end
	end
end

local function leave(c)
	for i, x in ipairs(line) do if x == c then table.remove(line, i) break end end
	c.state = "leaving"
	reposition()
	walkTo(c, DOCK)
	walkTo(c, CORNER)
	walkTo(c, c.route.out)
	walkTo(c, c.route.door)
	c.model:Destroy()
end

local function runCustomer(c)
	walkTo(c, c.route.out)
	walkTo(c, CORNER)
	walkTo(c, DOCK)
	c.state = "queued"
	c.slot = nil
	reposition()
	-- wait until we're at the front and standing at the table
	while c.model.Parent and (line[1] ~= c or (c.hrp.Position - SLOTS[1]).Magnitude > 3) do task.wait(0.3) end
	if not c.model.Parent then return end
	face(c, TABLE_LOOK)
	task.wait(1.2)
	local waited = 0
	while waited < WAIT_FOR_MEAT do
		local meat = topOfStack()
		if meat then
			local tier = meat:GetAttribute("Tier") -- Economy: read before giveMeat destroys it
			if Economy then Economy.settle(meat:GetAttribute("PieceId"), "Customer") end -- Economy: the one sale
			giveMeat(c, meat)
			bought:Fire(c.model.Name, tier)
			task.wait(0.8)
			break
		end
		waited += task.wait(0.5)
	end
	leave(c)
end

local function spawnCustomer()
	local model = makeAvatar()
	if not model then return end
	local route = DOORS[math.random(1, #DOORS)]
	local hum = model:FindFirstChildOfClass("Humanoid")
	local hrp = model:FindFirstChild("HumanoidRootPart")
	hum.WalkSpeed = WALK_SPEED
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	local up = Vector3.new(0, 2.9, 0)
	model:PivotTo(CFrame.lookAt(route.door + up, route.out + up))
	model.Parent = folder
	pcall(function() hrp:SetNetworkOwner(nil) end)
	-- walk / idle animations
	local animator = hum:FindFirstChildOfClass("Animator") or Instance.new("Animator", hum)
	local idleA = Instance.new("Animation") idleA.AnimationId = ANIM_IDLE
	local walkA = Instance.new("Animation") walkA.AnimationId = ANIM_WALK
	local idle = animator:LoadAnimation(idleA)
	local walk = animator:LoadAnimation(walkA)
	idle.Looped = true walk.Looped = true
	idle:Play()
	hum.Running:Connect(function(speed)
		if speed > 0.5 then
			if not walk.IsPlaying then walk:Play(0.2) end
			walk:AdjustSpeed(speed / 12)
		else
			if walk.IsPlaying then walk:Stop(0.25) end
		end
	end)
	local c = { model = model, hum = hum, hrp = hrp, route = route, state = "walking" }
	table.insert(line, c)
	task.spawn(runCustomer, c)
end

task.wait(4)
while true do
	-- Customers upgrade (CarSalesServer) publishes rate + line cap on workspace
	local cap = workspace:GetAttribute("CustomersLineCap") or MAX_IN_LINE
	if #Players:GetPlayers() > 0 and #line < cap then
		spawnCustomer()
	end
	local perMin = workspace:GetAttribute("CustomersPerMin")
	if perMin then
		local gap = 60 / perMin
		task.wait(gap * (0.75 + math.random() * 0.5))
	else
		task.wait(math.random(SPAWN_DELAY[1] * 10, SPAWN_DELAY[2] * 10) / 10)
	end
end

]], new = [[
-- Customers: avatars of the server owner's friends walk out of the shops in the city,
-- down the sidewalk to the meat table at the end of the conveyor, buy a piece of meat
-- (if there is any), and walk back into the city.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- A customer's purchase is the piece's one sale: EconomyService pays the piece's
-- owner its ledger value. The tier is read before the piece is destroyed.
local Players = game:GetService("Players")
local PhysicsService = game:GetService("PhysicsService")
local SS = game:GetService("ServerStorage")

local folder = workspace:WaitForChild("Customers")
local saleMeat = workspace:WaitForChild("SaleMeat")
local meatTemplate = SS:WaitForChild("MeatTemplate")
local bought = SS:WaitForChild("CustomerEvents"):WaitForChild("CustomerBought")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[CustomerSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[CustomerSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

-- tuning
local SPAWN_DELAY = { 10, 20 }   -- seconds between new customers
local MAX_IN_LINE = 4
local WAIT_FOR_MEAT = 18         -- how long they wait at the table before giving up
local WALK_SPEED = 9

-- route (sidewalk from the shop doors to the table)
local Y = 9.3
local DOORS = {
	{ door = Vector3.new(-125.6, Y, 185), out = Vector3.new(-126.1, Y, 184) },
	{ door = Vector3.new(-125.6, Y, 202), out = Vector3.new(-126.1, Y, 201) },
}
local CORNER = Vector3.new(-126.1, Y, 163.1)
local DOCK = Vector3.new(-94, Y, 163.1)
local SLOTS = { -- slot 1 is at the sale table, the rest line up behind
	Vector3.new(-94.8, Y, 152.5),
	Vector3.new(-94.8, Y, 157.5),
	Vector3.new(-94.6, Y, 162.4),
	Vector3.new(-98.5, Y, 163.1),
	Vector3.new(-102.5, Y, 163.1),
	Vector3.new(-106.5, Y, 163.1),
	Vector3.new(-110.5, Y, 163.1),
	Vector3.new(-114.5, Y, 163.1),
}
local TABLE_LOOK = Vector3.new(-80, Y, 152.5)

-- R15 default animations
local ANIM_IDLE = "rbxassetid://507766388"
local ANIM_WALK = "rbxassetid://507777826"

pcall(function()
	PhysicsService:RegisterCollisionGroup("Customers")
	PhysicsService:CollisionGroupSetCollidable("Customers", "Customers", false)
end)

------------------------------------------------ friends list
local friendIds = {}
local fetched = false
local function fetchFriends(player)
	if fetched then return end
	fetched = true
	local ok, pages = pcall(function() return Players:GetFriendsAsync(player.UserId) end)
	if ok and pages then
		while true do
			for _, f in ipairs(pages:GetCurrentPage()) do table.insert(friendIds, f.Id) end
			if pages.IsFinished or #friendIds >= 60 then break end
			local ok2 = pcall(function() pages:AdvanceToNextPageAsync() end)
			if not ok2 then break end
		end
	end
	if #friendIds == 0 then table.insert(friendIds, player.UserId) end
end
Players.PlayerAdded:Connect(fetchFriends)
for _, p in ipairs(Players:GetPlayers()) do task.spawn(fetchFriends, p) end

local descCache = {}
local function makeAvatar()
	local id = #friendIds > 0 and friendIds[math.random(1, #friendIds)] or nil
	local desc
	if id then
		desc = descCache[id]
		if not desc then
			local ok, d = pcall(function() return Players:GetHumanoidDescriptionFromUserId(id) end)
			if ok then desc = d descCache[id] = d end
		end
	end
	desc = desc or Instance.new("HumanoidDescription")
	local ok, model = pcall(function() return Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R15) end)
	if not ok or not model then return nil end
	if id then
		local ok2, name = pcall(function() return Players:GetNameFromUserIdAsync(id) end)
		model.Name = ok2 and name or "Customer"
	else
		model.Name = "Customer"
	end
	local anim = model:FindFirstChild("Animate") if anim then anim:Destroy() end
	for _, p in ipairs(model:GetDescendants()) do
		if p:IsA("BasePart") then p.CollisionGroup = "Customers" end
	end
	return model
end

------------------------------------------------ customer behaviour
local line = {}

local function walkTo(c, pos)
	local hum = c.hum
	if not hum.Parent or hum.Health <= 0 then return false end
	hum:MoveTo(pos)
	local done = false
	local conn = hum.MoveToFinished:Connect(function() done = true end)
	local t = 0
	while not done and t < 12 do t += task.wait(0.1) end
	conn:Disconnect()
	return true
end

local function face(c, target)
	local hrp = c.hrp
	local look = Vector3.new(target.X, hrp.Position.Y, target.Z)
	hrp.CFrame = CFrame.lookAt(hrp.Position, look)
end

local function topOfStack() -- nearest meat on the sale table
	local best, bd = nil, math.huge
	for _, m in ipairs(saleMeat:GetChildren()) do
		if not m:GetAttribute("Sold") then
			local d = (m.Position - SLOTS[1]).Magnitude
			if d < bd then best, bd = m, d end
		end
	end
	if best then best:SetAttribute("Sold", true) end
	return best
end

local function giveMeat(c, meat)
	local from = meat.Position
	local variant = meat:GetAttribute("Variant") -- MeatGlow: read before it goes
	meat:Destroy()
	local hand = c.model:FindFirstChild("RightHand") or c.hrp
	local p = meatTemplate:Clone()
	glow(p, variant) -- MeatGlow: in the customer's hand
	p.Anchored = true
	p.Parent = workspace
	local to = c.hrp.Position + c.hrp.CFrame.LookVector * 1.2 + Vector3.new(0, 0.3, 0)
	local t = 0
	while t < 0.35 do
		t += task.wait()
		local u = math.min(t / 0.35, 1)
		p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, 3 * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
	end
	-- hold it in front of them
	p.Anchored = false
	p.Massless = true
	p.CanCollide = false
	p.CFrame = c.hrp.CFrame * CFrame.new(0, 0.2, -1.1) * CFrame.Angles(0, math.rad(90), 0)
	local w = Instance.new("WeldConstraint")
	w.Part0 = c.hrp w.Part1 = p w.Parent = p
	p.Parent = c.model
end

local function reposition()
	for i, c in ipairs(line) do
		if c.state == "queued" and c.slot ~= i then
			c.slot = i
			task.spawn(function()
				walkTo(c, SLOTS[math.min(i, #SLOTS)])
				if i == 1 then face(c, TABLE_LOOK) end
			end)
		end
	end
end

local function leave(c)
	for i, x in ipairs(line) do if x == c then table.remove(line, i) break end end
	c.state = "leaving"
	reposition()
	walkTo(c, DOCK)
	walkTo(c, CORNER)
	walkTo(c, c.route.out)
	walkTo(c, c.route.door)
	c.model:Destroy()
end

local function runCustomer(c)
	walkTo(c, c.route.out)
	walkTo(c, CORNER)
	walkTo(c, DOCK)
	c.state = "queued"
	c.slot = nil
	reposition()
	-- wait until we're at the front and standing at the table
	while c.model.Parent and (line[1] ~= c or (c.hrp.Position - SLOTS[1]).Magnitude > 3) do task.wait(0.3) end
	if not c.model.Parent then return end
	face(c, TABLE_LOOK)
	task.wait(1.2)
	local waited = 0
	while waited < WAIT_FOR_MEAT do
		local meat = topOfStack()
		if meat then
			local tier = meat:GetAttribute("Tier") -- Economy: read before giveMeat destroys it
			if Economy then Economy.settle(meat:GetAttribute("PieceId"), "Customer") end -- Economy: the one sale
			giveMeat(c, meat)
			bought:Fire(c.model.Name, tier)
			task.wait(0.8)
			break
		end
		waited += task.wait(0.5)
	end
	leave(c)
end

local function spawnCustomer()
	local model = makeAvatar()
	if not model then return end
	local route = DOORS[math.random(1, #DOORS)]
	local hum = model:FindFirstChildOfClass("Humanoid")
	local hrp = model:FindFirstChild("HumanoidRootPart")
	hum.WalkSpeed = WALK_SPEED
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	local up = Vector3.new(0, 2.9, 0)
	model:PivotTo(CFrame.lookAt(route.door + up, route.out + up))
	model.Parent = folder
	pcall(function() hrp:SetNetworkOwner(nil) end)
	-- walk / idle animations
	local animator = hum:FindFirstChildOfClass("Animator") or Instance.new("Animator", hum)
	local idleA = Instance.new("Animation") idleA.AnimationId = ANIM_IDLE
	local walkA = Instance.new("Animation") walkA.AnimationId = ANIM_WALK
	local idle = animator:LoadAnimation(idleA)
	local walk = animator:LoadAnimation(walkA)
	idle.Looped = true walk.Looped = true
	idle:Play()
	hum.Running:Connect(function(speed)
		if speed > 0.5 then
			if not walk.IsPlaying then walk:Play(0.2) end
			walk:AdjustSpeed(speed / 12)
		else
			if walk.IsPlaying then walk:Stop(0.25) end
		end
	end)
	local c = { model = model, hum = hum, hrp = hrp, route = route, state = "walking" }
	table.insert(line, c)
	task.spawn(runCustomer, c)
end

task.wait(4)
while true do
	-- Customers upgrade (CarSalesServer) publishes rate + line cap on workspace
	local cap = workspace:GetAttribute("CustomersLineCap") or MAX_IN_LINE
	if #Players:GetPlayers() > 0 and #line < cap then
		spawnCustomer()
	end
	local perMin = workspace:GetAttribute("CustomersPerMin")
	if perMin then
		local gap = 60 / perMin
		task.wait(gap * (0.75 + math.random() * 0.5))
	else
		task.wait(math.random(SPAWN_DELAY[1] * 10, SPAWN_DELAY[2] * 10) / 10)
	end
end

]] } } },
	{ key = "TruckSystem", where = "script:TruckSystem", class = "Script", variants = { { label = "sales", old = [[
-- Delivery trucks: a line of trucks comes out of Cave1, waits at the U-turn next to the dock,
-- players carry meat from the stack at the end of the conveyor and drop it in the front truck's bucket.
-- When a truck has all the meat it needs it drives around the U-turn into Cave2 and the line moves up.
-- (Trucks are drawn/moved on each client by TruckClient using the "S" attribute; server keeps the logic.)
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- Players carry the ledger ids of the meat they pick up. Dropping a piece in a
-- truck is that piece's one sale (paid to the piece's owner, not the carrier).
-- If a carrier leaves or respawns, their pieces are held and come back out of
-- the grinder pipe instead of vanishing unpaid. Truck UI is unchanged.
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")
local RS = game:GetService("ReplicatedStorage")
local SS = game:GetService("ServerStorage")

local Path = require(RS:WaitForChild("TruckPath"))
local truckTypes = SS:WaitForChild("TruckTypes") -- each has Weight / NeedMin / NeedMax attributes
local meatTemplate = SS:WaitForChild("MeatTemplate")
local trucksFolder = workspace:WaitForChild("Trucks")
local meatStack = workspace:WaitForChild("MeatStack")
local events = SS:WaitForChild("TruckEvents")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[TruckSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[TruckSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- tuning
local MAX_TRUCKS = 5
local TRUCK_DELAY = { 6, 14 } -- seconds between new trucks pulling in
local nextTruckAt = 0
local NEED_MIN, NEED_MAX = 2, 5
local DRIVE_SPEED = 12
local MAX_CARRY = 10
local TRANSFER_EVERY = 0.15
local STACK_CENTER = Vector3.new(-78.4, 10.05, 160)
local STACK_HALF = Vector3.new(6.3, 0, 5.5)   -- pickup area around the end box
local DELIVER_RANGE = 9

local function pickType()
	local list, total = truckTypes:GetChildren(), 0
	for _, t in ipairs(list) do total += t:GetAttribute("Weight") or 1 end
	local r = Random.new():NextNumber(0, total)
	for _, t in ipairs(list) do
		r -= t:GetAttribute("Weight") or 1
		if r <= 0 then return t end
	end
	return list[1]
end
local rng = Random.new()
local queue = {}      -- waiting / loading trucks, front first
local departing = {}

------------------------------------------------------------ GUI
local MEAT_IMAGE = "rbxassetid://128058252479007"
local DOTS = 16
local FILLED, EMPTY = Color3.fromRGB(90, 225, 80), Color3.fromRGB(205, 210, 220)

-- cartoon order bubble: white disc, progress dots around the edge, meat picture, green count badge
local function makeGui(truck)
	local floor = truck:FindFirstChild("TubInnerFloor") or truck.PrimaryPart
	local bb = Instance.new("BillboardGui")
	bb.Name = "NeedGui"
	bb.Size = UDim2.fromScale(4.2, 4.2)
	bb.StudsOffsetWorldSpace = Vector3.new(0, 6.2, 0)
	bb.LightInfluence = 0
	bb.MaxDistance = 150
	bb.Parent = floor

	local shadow = Instance.new("Frame")
	shadow.Size = UDim2.fromScale(0.9, 0.9)
	shadow.Position = UDim2.fromScale(0.08, 0.1)
	shadow.BackgroundColor3 = Color3.new(0, 0, 0)
	shadow.BackgroundTransparency = 0.7
	shadow.Parent = bb
	Instance.new("UICorner", shadow).CornerRadius = UDim.new(1, 0)

	local circle = Instance.new("Frame")
	circle.Name = "Circle"
	circle.Size = UDim2.fromScale(0.9, 0.9)
	circle.Position = UDim2.fromScale(0.05, 0.05)
	circle.BackgroundColor3 = Color3.new(1, 1, 1)
	circle.Parent = bb
	Instance.new("UICorner", circle).CornerRadius = UDim.new(1, 0)
	local grad = Instance.new("UIGradient", circle)
	grad.Rotation = 90
	grad.Color = ColorSequence.new(Color3.fromRGB(255, 255, 255), Color3.fromRGB(215, 232, 255))
	local stroke = Instance.new("UIStroke", circle)
	stroke.Color = Color3.fromRGB(20, 20, 25)
	stroke.Thickness = 4

	local dots = {}
	for i = 1, DOTS do
		local a = (i - 1) / DOTS * math.pi * 2 - math.pi / 2
		local d = Instance.new("Frame")
		d.AnchorPoint = Vector2.new(0.5, 0.5)
		d.Size = UDim2.fromScale(0.1, 0.1)
		d.Position = UDim2.fromScale(0.5 + math.cos(a) * 0.4, 0.5 + math.sin(a) * 0.4)
		d.BackgroundColor3 = EMPTY
		d.Parent = circle
		Instance.new("UICorner", d).CornerRadius = UDim.new(1, 0)
		local ds = Instance.new("UIStroke", d)
		ds.Color = Color3.fromRGB(20, 20, 25)
		ds.Thickness = 1.5
		dots[i] = d
	end

	local meat = Instance.new("ImageLabel")
	meat.Name = "Meat"
	meat.AnchorPoint = Vector2.new(0.5, 0.5)
	meat.Position = UDim2.fromScale(0.5, 0.48)
	meat.Size = UDim2.fromScale(0.58, 0.58)
	meat.BackgroundTransparency = 1
	meat.Image = MEAT_IMAGE
	meat.ScaleType = Enum.ScaleType.Fit
	meat.Parent = circle

	local badge = Instance.new("Frame")
	badge.Name = "Badge"
	badge.Size = UDim2.fromScale(0.44, 0.44)
	badge.Position = UDim2.fromScale(0.62, 0.62)
	badge.BackgroundColor3 = Color3.new(1, 1, 1)
	badge.Parent = bb
	Instance.new("UICorner", badge).CornerRadius = UDim.new(1, 0)
	local bg = Instance.new("UIGradient", badge)
	bg.Rotation = 90
	bg.Color = ColorSequence.new(Color3.fromRGB(150, 255, 90), Color3.fromRGB(40, 185, 50))
	local bs = Instance.new("UIStroke", badge)
	bs.Color = Color3.fromRGB(20, 20, 25)
	bs.Thickness = 3.5
	local num = Instance.new("TextLabel")
	num.Name = "Num"
	num.Size = UDim2.fromScale(0.8, 0.8)
	num.Position = UDim2.fromScale(0.1, 0.08)
	num.BackgroundTransparency = 1
	num.Font = Enum.Font.FredokaOne
	num.TextScaled = true
	num.TextColor3 = Color3.new(1, 1, 1)
	num.Parent = badge
	local ns = Instance.new("UIStroke", num)
	ns.Color = Color3.fromRGB(20, 20, 25)
	ns.Thickness = 2.5

	local function setProgress(frac)
		local n = math.floor(frac * DOTS + 0.5)
		for i, d in ipairs(dots) do d.BackgroundColor3 = i <= n and FILLED or EMPTY end
	end
	setProgress(0)
	return num, setProgress
end

------------------------------------------------------------ TRUCKS
local function spawnTruck()
	local tpl = pickType()
	local m = tpl:Clone()
	local need = rng:NextInteger(tpl:GetAttribute("NeedMin") or NEED_MIN, tpl:GetAttribute("NeedMax") or NEED_MAX)
	m:SetAttribute("Need", need)
	m:SetAttribute("Loaded", 0)
	m:SetAttribute("S", 0)
	m:PivotTo(Path.truckCF(0))
	local t = { model = m, s = 0, need = need, loaded = 0, lastSent = -1, bucketOffset = tpl:GetAttribute("BucketOffset") }
	t.num, t.setProgress = makeGui(m)
	t.num.Text = tostring(need)
	m.Parent = trucksFolder
	table.insert(queue, t)
end

local function depart(t)
	local gui = t.model:FindFirstChild("NeedGui", true)
	if gui then gui:Destroy() end
	for i, q in ipairs(queue) do if q == t then table.remove(queue, i) break end end
	table.insert(departing, t)
end

local function step(t, target, dt)
	local d = target - t.s
	if math.abs(d) < 0.01 then t.s = target return end
	local v = math.min(DRIVE_SPEED, math.abs(d) * 2.5 + 0.5)
	t.s += math.sign(d) * math.min(math.abs(d), v * dt)
end

local sendClock = 0
RunService.Heartbeat:Connect(function(dt)
	for i, t in ipairs(queue) do
		step(t, Path.slot(i), dt)
	end
	for i = #departing, 1, -1 do
		local t = departing[i]
		step(t, Path.TOTAL, dt)
		if t.s >= Path.TOTAL - 0.05 then
			t.model:Destroy()
			table.remove(departing, i)
		end
	end
	sendClock += dt
	if sendClock >= 0.066 then
		sendClock = 0
		for _, list in ipairs({ queue, departing }) do
			for _, t in ipairs(list) do
				if t.s ~= t.lastSent then
					t.lastSent = t.s
					t.model:SetAttribute("S", t.s)
				end
			end
		end
	end
	-- keep the line full
	local last = queue[#queue]
	-- cars only come once someone has bought Car Sales; Max Line + Car Speed upgrades
	local maxQ = workspace:GetAttribute("CarsMaxQueue") or MAX_TRUCKS
	if workspace:GetAttribute("CarsUnlocked") and #queue + #departing < maxQ + 2 and #queue < maxQ and (not last or last.s >= Path.SPACING) and os.clock() >= nextTruckAt then
		spawnTruck()
		local gap = workspace:GetAttribute("CarsGapSeconds")
		if gap then
			nextTruckAt = os.clock() + gap * rng:NextNumber(0.85, 1.15)
		else
			nextTruckAt = os.clock() + rng:NextNumber(TRUCK_DELAY[1], TRUCK_DELAY[2])
		end
	end
end)

------------------------------------------------------------ CARRYING
local carry = {} -- player -> {count, parts, ids}

-- Economy: ledger ids of the meat a player carries (false = untracked piece).
-- A carrier who leaves or respawns gives them back as held pieces.
local function dropCarried(c)
	if Economy and c and c.ids then
		for _, id in ipairs(c.ids) do
			if id then Economy.hold(id) end
		end
		table.clear(c.ids)
	end
end

local function carryVisual(player)
	local c = carry[player]
	local char = player.Character
	local hrp = char and char:FindFirstChild("HumanoidRootPart")
	if not hrp then return end
	local folder = char:FindFirstChild("CarriedMeat")
	if not folder then folder = Instance.new("Folder") folder.Name = "CarriedMeat" folder.Parent = char end
	while #c.parts < c.count do
		local p = meatTemplate:Clone()
		p.Anchored = false
		p.Massless = true
		p.CanCollide = false
		local i = #c.parts
		p.CFrame = hrp.CFrame * CFrame.new(0, 0.1 + i * 0.3, -1.7) * CFrame.Angles(0, math.rad(90), 0)
		local w = Instance.new("WeldConstraint")
		w.Part0 = hrp w.Part1 = p w.Parent = p
		p.Parent = folder
		table.insert(c.parts, p)
	end
	while #c.parts > c.count do
		table.remove(c.parts):Destroy()
	end
	player:SetAttribute("CarryMeat", c.count)
end

local function flyPart(from, to, height, dur)
	local p = meatTemplate:Clone()
	p.CFrame = CFrame.new(from)
	p.Parent = workspace
	task.spawn(function()
		local t = 0
		while t < dur do
			t += RunService.Heartbeat:Wait()
			local u = math.min(t / dur, 1)
			p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
		end
		p:Destroy()
	end)
	return dur
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function addMeatToTruck(t, n) -- n = 0-based slot
	local layer = n // 4
	local i = n % 4
	local off = t.bucketOffset + Vector3.new((i % 2 - 0.5) * 1.6, 0.16 + layer * 0.3, (i // 2 - 0.5) * 1.9)
	local p = meatTemplate:Clone()
	p.Name = "LoadedMeat"
	-- server-side the truck stays at its spawn pose; the client moves everything together
	p.CFrame = Path.truckCF(0) * CFrame.new(off) * CFrame.Angles(0, rng:NextNumber(-0.3, 0.3), 0)
	p.Parent = t.model
end

local timers = {}
task.spawn(function()
	while true do
		task.wait(TRANSFER_EVERY)
		local front = queue[1]
		local loading = front and math.abs(front.s - Path.LOAD_S) < 0.3 and front.loaded < front.need
		local bucketPos = front and (Path.truckCF(Path.LOAD_S) * CFrame.new(front.bucketOffset)).Position
		for _, player in ipairs(Players:GetPlayers()) do
			local char = player.Character
			local hrp = char and char:FindFirstChild("HumanoidRootPart")
			local hum = char and char:FindFirstChildOfClass("Humanoid")
			if not hrp or not hum or hum.Health <= 0 then continue end
			carry[player] = carry[player] or { count = 0, parts = {}, ids = {} }
			local c = carry[player]
			local pos = hrp.Position
			local rel = pos - STACK_CENTER
			-- pick up from the stack
			if math.abs(rel.X) <= STACK_HALF.X and math.abs(rel.Z) <= STACK_HALF.Z and math.abs(rel.Y) < 8 and c.count < MAX_CARRY then
				local meat = topOfStack()
				if meat then
					local from = meat.Position
					local pieceId = meat:GetAttribute("PieceId") -- Economy
					meat:Destroy()
					if Economy then
						table.insert(c.ids, if pieceId and Economy.carry(pieceId) then pieceId else false)
					end
					flyPart(from, pos + Vector3.new(0, 0.5 + c.count * 0.3, 0), 2, 0.2)
					c.count += 1
					carryVisual(player)
				end
			-- drop into the front truck
			elseif loading and c.count > 0 then
				local d = Vector3.new(pos.X - bucketPos.X, 0, pos.Z - bucketPos.Z).Magnitude
				if d <= DELIVER_RANGE then
					c.count -= 1
					if Economy then Economy.settle(table.remove(c.ids), "Truck") end -- Economy: the one sale
					carryVisual(player)
					local truck = front
					local slotLoaded = truck.loaded
					truck.loaded += 1
					truck.model:SetAttribute("Loaded", truck.loaded)
					truck.num.Text = tostring(truck.need - truck.loaded)
					if truck.setProgress then truck.setProgress(truck.loaded / truck.need) end
					events.MeatDelivered:Fire(player, truck.model)
					local dur = flyPart(pos + Vector3.new(0, 1.5, 0), bucketPos + Vector3.new(0, 0.5, 0), 4, 0.35)
					task.delay(dur, function()
						if truck.model.Parent then addMeatToTruck(truck, slotLoaded) end
					end)
					if truck.loaded >= truck.need then
						events.TruckFilled:Fire(player, truck.need)
						loading = false
						task.delay(0.8, function() depart(truck) end)
					end
				end
			end
		end
	end
end)

Players.PlayerRemoving:Connect(function(p) dropCarried(carry[p]) carry[p] = nil end)
-- Economy: loading EconomyService (top of this script) can yield, so players
-- may already be in the server here; bind every player exactly once.
local bound = {}
local function bindPlayer(p)
	if bound[p] then return end
	bound[p] = true
	p.CharacterAdded:Connect(function()
		dropCarried(carry[p]) -- Economy: a respawned carrier's pieces are held, not lost
		carry[p] = { count = 0, parts = {}, ids = {} }
		p:SetAttribute("CarryMeat", 0)
	end)
end
Players.PlayerAdded:Connect(bindPlayer)
for _, p in ipairs(Players:GetPlayers()) do bindPlayer(p) end
Players.PlayerRemoving:Connect(function(p) bound[p] = nil end)

]], new = [[
-- Delivery trucks: a line of trucks comes out of Cave1, waits at the U-turn next to the dock,
-- players carry meat from the stack at the end of the conveyor and drop it in the front truck's bucket.
-- When a truck has all the meat it needs it drives around the U-turn into Cave2 and the line moves up.
-- (Trucks are drawn/moved on each client by TruckClient using the "S" attribute; server keeps the logic.)
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- Players carry the ledger ids of the meat they pick up. Dropping a piece in a
-- truck is that piece's one sale (paid to the piece's owner, not the carrier).
-- If a carrier leaves or respawns, their pieces are held and come back out of
-- the grinder pipe instead of vanishing unpaid. Truck UI is unchanged.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")
local RS = game:GetService("ReplicatedStorage")
local SS = game:GetService("ServerStorage")

local Path = require(RS:WaitForChild("TruckPath"))
local truckTypes = SS:WaitForChild("TruckTypes") -- each has Weight / NeedMin / NeedMax attributes
local meatTemplate = SS:WaitForChild("MeatTemplate")
local trucksFolder = workspace:WaitForChild("Trucks")
local meatStack = workspace:WaitForChild("MeatStack")
local events = SS:WaitForChild("TruckEvents")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[TruckSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[TruckSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

-- tuning
local MAX_TRUCKS = 5
local TRUCK_DELAY = { 6, 14 } -- seconds between new trucks pulling in
local nextTruckAt = 0
local NEED_MIN, NEED_MAX = 2, 5
local DRIVE_SPEED = 12
local MAX_CARRY = 10
local TRANSFER_EVERY = 0.15
local STACK_CENTER = Vector3.new(-78.4, 10.05, 160)
local STACK_HALF = Vector3.new(6.3, 0, 5.5)   -- pickup area around the end box
local DELIVER_RANGE = 9

local function pickType()
	local list, total = truckTypes:GetChildren(), 0
	for _, t in ipairs(list) do total += t:GetAttribute("Weight") or 1 end
	local r = Random.new():NextNumber(0, total)
	for _, t in ipairs(list) do
		r -= t:GetAttribute("Weight") or 1
		if r <= 0 then return t end
	end
	return list[1]
end
local rng = Random.new()
local queue = {}      -- waiting / loading trucks, front first
local departing = {}

------------------------------------------------------------ GUI
local MEAT_IMAGE = "rbxassetid://128058252479007"
local DOTS = 16
local FILLED, EMPTY = Color3.fromRGB(90, 225, 80), Color3.fromRGB(205, 210, 220)

-- cartoon order bubble: white disc, progress dots around the edge, meat picture, green count badge
local function makeGui(truck)
	local floor = truck:FindFirstChild("TubInnerFloor") or truck.PrimaryPart
	local bb = Instance.new("BillboardGui")
	bb.Name = "NeedGui"
	bb.Size = UDim2.fromScale(4.2, 4.2)
	bb.StudsOffsetWorldSpace = Vector3.new(0, 6.2, 0)
	bb.LightInfluence = 0
	bb.MaxDistance = 150
	bb.Parent = floor

	local shadow = Instance.new("Frame")
	shadow.Size = UDim2.fromScale(0.9, 0.9)
	shadow.Position = UDim2.fromScale(0.08, 0.1)
	shadow.BackgroundColor3 = Color3.new(0, 0, 0)
	shadow.BackgroundTransparency = 0.7
	shadow.Parent = bb
	Instance.new("UICorner", shadow).CornerRadius = UDim.new(1, 0)

	local circle = Instance.new("Frame")
	circle.Name = "Circle"
	circle.Size = UDim2.fromScale(0.9, 0.9)
	circle.Position = UDim2.fromScale(0.05, 0.05)
	circle.BackgroundColor3 = Color3.new(1, 1, 1)
	circle.Parent = bb
	Instance.new("UICorner", circle).CornerRadius = UDim.new(1, 0)
	local grad = Instance.new("UIGradient", circle)
	grad.Rotation = 90
	grad.Color = ColorSequence.new(Color3.fromRGB(255, 255, 255), Color3.fromRGB(215, 232, 255))
	local stroke = Instance.new("UIStroke", circle)
	stroke.Color = Color3.fromRGB(20, 20, 25)
	stroke.Thickness = 4

	local dots = {}
	for i = 1, DOTS do
		local a = (i - 1) / DOTS * math.pi * 2 - math.pi / 2
		local d = Instance.new("Frame")
		d.AnchorPoint = Vector2.new(0.5, 0.5)
		d.Size = UDim2.fromScale(0.1, 0.1)
		d.Position = UDim2.fromScale(0.5 + math.cos(a) * 0.4, 0.5 + math.sin(a) * 0.4)
		d.BackgroundColor3 = EMPTY
		d.Parent = circle
		Instance.new("UICorner", d).CornerRadius = UDim.new(1, 0)
		local ds = Instance.new("UIStroke", d)
		ds.Color = Color3.fromRGB(20, 20, 25)
		ds.Thickness = 1.5
		dots[i] = d
	end

	local meat = Instance.new("ImageLabel")
	meat.Name = "Meat"
	meat.AnchorPoint = Vector2.new(0.5, 0.5)
	meat.Position = UDim2.fromScale(0.5, 0.48)
	meat.Size = UDim2.fromScale(0.58, 0.58)
	meat.BackgroundTransparency = 1
	meat.Image = MEAT_IMAGE
	meat.ScaleType = Enum.ScaleType.Fit
	meat.Parent = circle

	local badge = Instance.new("Frame")
	badge.Name = "Badge"
	badge.Size = UDim2.fromScale(0.44, 0.44)
	badge.Position = UDim2.fromScale(0.62, 0.62)
	badge.BackgroundColor3 = Color3.new(1, 1, 1)
	badge.Parent = bb
	Instance.new("UICorner", badge).CornerRadius = UDim.new(1, 0)
	local bg = Instance.new("UIGradient", badge)
	bg.Rotation = 90
	bg.Color = ColorSequence.new(Color3.fromRGB(150, 255, 90), Color3.fromRGB(40, 185, 50))
	local bs = Instance.new("UIStroke", badge)
	bs.Color = Color3.fromRGB(20, 20, 25)
	bs.Thickness = 3.5
	local num = Instance.new("TextLabel")
	num.Name = "Num"
	num.Size = UDim2.fromScale(0.8, 0.8)
	num.Position = UDim2.fromScale(0.1, 0.08)
	num.BackgroundTransparency = 1
	num.Font = Enum.Font.FredokaOne
	num.TextScaled = true
	num.TextColor3 = Color3.new(1, 1, 1)
	num.Parent = badge
	local ns = Instance.new("UIStroke", num)
	ns.Color = Color3.fromRGB(20, 20, 25)
	ns.Thickness = 2.5

	local function setProgress(frac)
		local n = math.floor(frac * DOTS + 0.5)
		for i, d in ipairs(dots) do d.BackgroundColor3 = i <= n and FILLED or EMPTY end
	end
	setProgress(0)
	return num, setProgress
end

------------------------------------------------------------ TRUCKS
local function spawnTruck()
	local tpl = pickType()
	local m = tpl:Clone()
	local need = rng:NextInteger(tpl:GetAttribute("NeedMin") or NEED_MIN, tpl:GetAttribute("NeedMax") or NEED_MAX)
	m:SetAttribute("Need", need)
	m:SetAttribute("Loaded", 0)
	m:SetAttribute("S", 0)
	m:PivotTo(Path.truckCF(0))
	local t = { model = m, s = 0, need = need, loaded = 0, lastSent = -1, bucketOffset = tpl:GetAttribute("BucketOffset") }
	t.num, t.setProgress = makeGui(m)
	t.num.Text = tostring(need)
	m.Parent = trucksFolder
	table.insert(queue, t)
end

local function depart(t)
	local gui = t.model:FindFirstChild("NeedGui", true)
	if gui then gui:Destroy() end
	for i, q in ipairs(queue) do if q == t then table.remove(queue, i) break end end
	table.insert(departing, t)
end

local function step(t, target, dt)
	local d = target - t.s
	if math.abs(d) < 0.01 then t.s = target return end
	local v = math.min(DRIVE_SPEED, math.abs(d) * 2.5 + 0.5)
	t.s += math.sign(d) * math.min(math.abs(d), v * dt)
end

local sendClock = 0
RunService.Heartbeat:Connect(function(dt)
	for i, t in ipairs(queue) do
		step(t, Path.slot(i), dt)
	end
	for i = #departing, 1, -1 do
		local t = departing[i]
		step(t, Path.TOTAL, dt)
		if t.s >= Path.TOTAL - 0.05 then
			t.model:Destroy()
			table.remove(departing, i)
		end
	end
	sendClock += dt
	if sendClock >= 0.066 then
		sendClock = 0
		for _, list in ipairs({ queue, departing }) do
			for _, t in ipairs(list) do
				if t.s ~= t.lastSent then
					t.lastSent = t.s
					t.model:SetAttribute("S", t.s)
				end
			end
		end
	end
	-- keep the line full
	local last = queue[#queue]
	-- cars only come once someone has bought Car Sales; Max Line + Car Speed upgrades
	local maxQ = workspace:GetAttribute("CarsMaxQueue") or MAX_TRUCKS
	if workspace:GetAttribute("CarsUnlocked") and #queue + #departing < maxQ + 2 and #queue < maxQ and (not last or last.s >= Path.SPACING) and os.clock() >= nextTruckAt then
		spawnTruck()
		local gap = workspace:GetAttribute("CarsGapSeconds")
		if gap then
			nextTruckAt = os.clock() + gap * rng:NextNumber(0.85, 1.15)
		else
			nextTruckAt = os.clock() + rng:NextNumber(TRUCK_DELAY[1], TRUCK_DELAY[2])
		end
	end
end)

------------------------------------------------------------ CARRYING
local carry = {} -- player -> {count, parts, ids}

-- Economy: ledger ids of the meat a player carries (false = untracked piece).
-- A carrier who leaves or respawns gives them back as held pieces.
local function dropCarried(c)
	if Economy and c and c.ids then
		for _, id in ipairs(c.ids) do
			if id then Economy.hold(id) end
		end
		table.clear(c.ids)
	end
end

local function carryVisual(player)
	local c = carry[player]
	local char = player.Character
	local hrp = char and char:FindFirstChild("HumanoidRootPart")
	if not hrp then return end
	local folder = char:FindFirstChild("CarriedMeat")
	if not folder then folder = Instance.new("Folder") folder.Name = "CarriedMeat" folder.Parent = char end
	while #c.parts < c.count do
		local p = meatTemplate:Clone()
		p.Anchored = false
		p.Massless = true
		p.CanCollide = false
		local i = #c.parts
		glow(p, c.glow and c.glow[i + 1]) -- MeatGlow
		p.CFrame = hrp.CFrame * CFrame.new(0, 0.1 + i * 0.3, -1.7) * CFrame.Angles(0, math.rad(90), 0)
		local w = Instance.new("WeldConstraint")
		w.Part0 = hrp w.Part1 = p w.Parent = p
		p.Parent = folder
		table.insert(c.parts, p)
	end
	while #c.parts > c.count do
		table.remove(c.parts):Destroy()
	end
	player:SetAttribute("CarryMeat", c.count)
end

local function flyPart(from, to, height, dur, variant) -- MeatGlow: variant
	local p = meatTemplate:Clone()
	glow(p, variant) -- MeatGlow
	p.CFrame = CFrame.new(from)
	p.Parent = workspace
	task.spawn(function()
		local t = 0
		while t < dur do
			t += RunService.Heartbeat:Wait()
			local u = math.min(t / dur, 1)
			p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
		end
		p:Destroy()
	end)
	return dur
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function addMeatToTruck(t, n, variant) -- n = 0-based slot; MeatGlow: variant
	local layer = n // 4
	local i = n % 4
	local off = t.bucketOffset + Vector3.new((i % 2 - 0.5) * 1.6, 0.16 + layer * 0.3, (i // 2 - 0.5) * 1.9)
	local p = meatTemplate:Clone()
	p.Name = "LoadedMeat"
	glow(p, variant) -- MeatGlow
	-- server-side the truck stays at its spawn pose; the client moves everything together
	p.CFrame = Path.truckCF(0) * CFrame.new(off) * CFrame.Angles(0, rng:NextNumber(-0.3, 0.3), 0)
	p.Parent = t.model
end

local timers = {}
task.spawn(function()
	while true do
		task.wait(TRANSFER_EVERY)
		local front = queue[1]
		local loading = front and math.abs(front.s - Path.LOAD_S) < 0.3 and front.loaded < front.need
		local bucketPos = front and (Path.truckCF(Path.LOAD_S) * CFrame.new(front.bucketOffset)).Position
		for _, player in ipairs(Players:GetPlayers()) do
			local char = player.Character
			local hrp = char and char:FindFirstChild("HumanoidRootPart")
			local hum = char and char:FindFirstChildOfClass("Humanoid")
			if not hrp or not hum or hum.Health <= 0 then continue end
			carry[player] = carry[player] or { count = 0, parts = {}, ids = {} }
			local c = carry[player]
			local pos = hrp.Position
			local rel = pos - STACK_CENTER
			-- pick up from the stack
			if math.abs(rel.X) <= STACK_HALF.X and math.abs(rel.Z) <= STACK_HALF.Z and math.abs(rel.Y) < 8 and c.count < MAX_CARRY then
				local meat = topOfStack()
				if meat then
					local from = meat.Position
					local pieceId = meat:GetAttribute("PieceId") -- Economy
					local variant = meat:GetAttribute("Variant") -- MeatGlow
					meat:Destroy()
					if Economy then
						table.insert(c.ids, if pieceId and Economy.carry(pieceId) then pieceId else false)
					end
					flyPart(from, pos + Vector3.new(0, 0.5 + c.count * 0.3, 0), 2, 0.2, variant)
					c.count += 1
					c.glow = c.glow or {} -- MeatGlow
					c.glow[c.count] = variant or false
					carryVisual(player)
				end
			-- drop into the front truck
			elseif loading and c.count > 0 then
				local d = Vector3.new(pos.X - bucketPos.X, 0, pos.Z - bucketPos.Z).Magnitude
				if d <= DELIVER_RANGE then
					c.count -= 1
					local variant = c.glow and c.glow[c.count + 1] -- MeatGlow: the top piece
					if Economy then Economy.settle(table.remove(c.ids), "Truck") end -- Economy: the one sale
					carryVisual(player)
					local truck = front
					local slotLoaded = truck.loaded
					truck.loaded += 1
					truck.model:SetAttribute("Loaded", truck.loaded)
					truck.num.Text = tostring(truck.need - truck.loaded)
					if truck.setProgress then truck.setProgress(truck.loaded / truck.need) end
					events.MeatDelivered:Fire(player, truck.model)
					local dur = flyPart(pos + Vector3.new(0, 1.5, 0), bucketPos + Vector3.new(0, 0.5, 0), 4, 0.35, variant)
					task.delay(dur, function()
						if truck.model.Parent then addMeatToTruck(truck, slotLoaded, variant) end
					end)
					if truck.loaded >= truck.need then
						events.TruckFilled:Fire(player, truck.need)
						loading = false
						task.delay(0.8, function() depart(truck) end)
					end
				end
			end
		end
	end
end)

Players.PlayerRemoving:Connect(function(p) dropCarried(carry[p]) carry[p] = nil end)
-- Economy: loading EconomyService (top of this script) can yield, so players
-- may already be in the server here; bind every player exactly once.
local bound = {}
local function bindPlayer(p)
	if bound[p] then return end
	bound[p] = true
	p.CharacterAdded:Connect(function()
		dropCarried(carry[p]) -- Economy: a respawned carrier's pieces are held, not lost
		carry[p] = { count = 0, parts = {}, ids = {} }
		p:SetAttribute("CarryMeat", 0)
	end)
end
Players.PlayerAdded:Connect(bindPlayer)
for _, p in ipairs(Players:GetPlayers()) do bindPlayer(p) end
Players.PlayerRemoving:Connect(function(p) bound[p] = nil end)

]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {
	{ key = "FishVariantVisuals", where = "ReplicatedStorage/FishVariantVisuals", class = "ModuleScript", tag = "EconomyOwned", source = [[
-- FishVariantVisuals (ModuleScript in ReplicatedStorage).
-- Tasteful effects for Silver/Gold fish and their meat. Species colors and
-- details are never changed; the effects are ADDED as non-BasePart children
-- (a Highlight outline with a faint tint, a few sparkles, a small light, a
-- label), so FishSwimClient's part list and BulkMoveTo animation are
-- unaffected. Uses only built-in particle textures; no external assets.
--
-- Cost per variant object: 1 ParticleEmitter (3-4 particles/s), 1 PointLight
-- without shadows, and for fish 1 Highlight + 1 BillboardGui. Variants are
-- rare (~2.5% of fish), so this stays cheap with 60 river fish. Roblox renders
-- at most 31 Highlights per client; beyond that the outline alone is skipped.

local FishVariants = require(script.Parent.FishVariants)

local V = {}

local FX = "VariantFx"

local function colorOf(name: string): Color3
	local c = FishVariants.Defs[name].Color
	return Color3.fromRGB(c[1], c[2], c[3])
end

local function rootPart(inst: Instance): BasePart?
	if inst:IsA("BasePart") then
		return inst
	end
	if inst:IsA("Model") then
		return inst.PrimaryPart or inst:FindFirstChildWhichIsA("BasePart", true)
	end
	return nil
end

local function sparkles(parent: Instance, color: Color3, rate: number, size: number)
	local e = Instance.new("ParticleEmitter")
	e.Name = FX .. "Sparkles"
	e.Color = ColorSequence.new(color)
	e.LightEmission = 1
	e.LightInfluence = 0
	e.Rate = rate
	e.Lifetime = NumberRange.new(0.5, 0.9)
	e.Speed = NumberRange.new(0.4, 1)
	e.SpreadAngle = Vector2.new(180, 180)
	e.Size = NumberSequence.new({ NumberSequenceKeypoint.new(0, size), NumberSequenceKeypoint.new(1, 0) })
	e.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0.1), NumberSequenceKeypoint.new(1, 1) })
	e.Parent = parent
end

local function light(parent: Instance, color: Color3, range: number)
	local l = Instance.new("PointLight")
	l.Name = FX .. "Light"
	l.Color = color
	l.Brightness = 1.2
	l.Range = range
	l.Shadows = false
	l.Parent = parent
end

-- Fish models (river, rod reveal, aquarium). `label` defaults to true.
function V.applyToFish(model: Instance, variant: any, label: boolean?)
	local name = FishVariants.sanitize(variant)
	if not name or model:FindFirstChild(FX) then
		return
	end
	local color = colorOf(name)
	local folder = Instance.new("Folder")
	folder.Name = FX

	local hl = Instance.new("Highlight")
	hl.Adornee = model
	hl.FillColor = color
	hl.FillTransparency = 0.82 -- faint tint: species colors stay readable
	hl.OutlineColor = color
	hl.OutlineTransparency = 0.15
	hl.DepthMode = Enum.HighlightDepthMode.Occluded
	hl.Parent = folder

	local root = rootPart(model)
	if root then
		local att = Instance.new("Attachment")
		att.Name = FX .. "Att"
		att.Parent = root
		sparkles(att, color, if name == "Gold" then 4 else 3, 0.3)
		light(root, color, 6)
		if label ~= false then
			local gui = Instance.new("BillboardGui")
			gui.Name = FX .. "Label"
			gui.Adornee = root
			gui.Size = UDim2.fromOffset(84, 22)
			gui.StudsOffsetWorldSpace = Vector3.new(0, 2.2, 0)
			gui.MaxDistance = 80
			gui.LightInfluence = 0
			local text = Instance.new("TextLabel")
			text.Size = UDim2.fromScale(1, 1)
			text.BackgroundTransparency = 1
			text.Font = Enum.Font.FredokaOne
			text.TextScaled = true
			text.Text = FishVariants.Defs[name].Label
			text.TextColor3 = color
			text.TextStrokeColor3 = Color3.fromRGB(30, 30, 40)
			text.TextStrokeTransparency = 0.2
			text.Parent = gui
			gui.Parent = folder
		end
	end
	folder.Parent = model
end

-- Meat pieces (blender, belt, stack, carried, loaded, held by a customer):
-- a small glow and sparkles only, so a full stack doesn't get cluttered.
function V.applyToPart(part: Instance, variant: any)
	local name = FishVariants.sanitize(variant)
	if not name or not part:IsA("BasePart") or part:FindFirstChild(FX .. "Att") then
		return
	end
	local color = colorOf(name)
	local att = Instance.new("Attachment")
	att.Name = FX .. "Att"
	att.Parent = part
	sparkles(att, color, 2, 0.2)
	light(part, color, 4)
end

return V
]] },
}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackMeatGlow.lua restores the previous sources)")
