--[[
	InstallJumpRate.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Fish jump more often (about twice as often). Changes only the two period
	numbers in ReplicatedStorage.FishJump:
	  PeriodMin     16 -> 8   seconds
	  PeriodSpread  12 -> 6   seconds   (each fish's period: 16-28 s -> 8-14 s)
	Unchanged: Chance 0.35 per period, 0.9 s in the air, heights, the river-end
	margin, snakes don't jump, splash pool 10, and the client's protections
	(a netted or harpooned fish never jumps; FishSwimClient isn't touched).
	Each fish keeps its own period and offset, so jumps stay staggered. Per
	fish: about once every 63 s -> about once every 31 s.
	Its own backup (FishJumpRateBackup); FishJumpBackup is never touched.
	Requires: fish jumps (InstallFishJump.lua). Roll this back BEFORE
	UninstallFishJump (which refuses while it is in).

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.FishJumpRateBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackJumpRate.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallJumpRate"
local BACKUP = "FishJumpRateBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "FishJumpBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "FishJumpRateBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "FishJump", where = "ReplicatedStorage/FishJump", class = "ModuleScript", tag = "FishJumpOwned", variants = { { label = "installed", old = [[
--!strict
-- FishJump (ModuleScript in ReplicatedStorage). Pure, visual-only jump
-- schedule for river fish, used by the patched FishSwimClient.
--
-- Each fish gets its own period and time offset from its Seed; in every
-- period it jumps with probability Chance, decided by an integer hash of
-- (Seed, cycle number). Everything is a pure function of server time and
-- Seed, so every client sees the same fish jump at the same moment, jumps are
-- sparse and staggered, and a player joining mid-jump computes the same arc.
-- The hash uses exact 32-bit integer ops (not sin()) because server time is
-- ~1.7e9 and large-argument sin() can differ between devices.
--
-- Nothing here touches the server: net catch eligibility (NetLiftScript's
-- fishPos uses only x/z from the spawn attributes) and rewards are unchanged,
-- and the jump never moves the fish's x/z, so it stays in its lane.

local FishJump = {}

export type Config = {
	Enabled: boolean,
	Chance: number, -- probability a fish jumps in one of its periods
	PeriodMin: number, -- seconds; each fish's period is in [PeriodMin, PeriodMin + PeriodSpread)
	PeriodSpread: number,
	Duration: number, -- seconds in the air
	HeightPerStud: number, -- jump height per stud of SwimLen
	MinHeight: number,
	MaxHeight: number,
	PitchScale: number, -- 1 = nose follows the arc exactly; lower = gentler pitch
	EdgeMargin: number, -- no jumps this close to the river's MinZ/MaxZ
	SkipSnakes: boolean, -- CrystalSerpent-style long fish don't jump
	Splash: boolean,
	SplashPool: number, -- max simultaneous splash rings
}

FishJump.Defaults = {
	Enabled = true,
	Chance = 0.35,
	PeriodMin = 16,
	PeriodSpread = 12,
	Duration = 0.9,
	HeightPerStud = 0.45,
	MinHeight = 1.2,
	MaxHeight = 3.2,
	PitchScale = 0.6,
	EdgeMargin = 6,
	SkipSnakes = true,
	Splash = true,
	SplashPool = 10,
} :: Config

local TWO32 = 4294967296

local function u32(v: number): number
	return math.floor(v) % TWO32
end

local function xorshift(h: number): number
	h = bit32.bxor(h, bit32.lshift(h, 13))
	h = bit32.bxor(h, bit32.rshift(h, 17))
	h = bit32.bxor(h, bit32.lshift(h, 5))
	return h
end

-- Deterministic hash of two integers to [0, 1).
function FishJump.hash01(a: number, b: number): number
	local h = bit32.bxor(u32(a), bit32.lrotate(u32(b), 16), 0x9E3779B9)
	if h == 0 then
		h = 0x6D2B79F5
	end
	h = xorshift(xorshift(xorshift(h)))
	return h / TWO32
end

-- Reads optional overrides from attributes on the river folder:
-- JumpEnabled (bool), JumpChance (0..1), JumpHeightScale (multiplier).
function FishJump.config(get: (string) -> any): Config
	local cfg = table.clone(FishJump.Defaults)
	local enabled = get("JumpEnabled")
	if type(enabled) == "boolean" then
		cfg.Enabled = enabled
	end
	local chance = get("JumpChance")
	if type(chance) == "number" and chance == chance then
		cfg.Chance = math.clamp(chance, 0, 1)
	end
	local scale = get("JumpHeightScale")
	if type(scale) == "number" and scale == scale and scale > 0 then
		cfg.HeightPerStud *= scale
		cfg.MinHeight *= scale
		cfg.MaxHeight *= scale
	end
	return cfg
end

function FishJump.period(seed: number, cfg: Config): number
	return cfg.PeriodMin + cfg.PeriodSpread * FishJump.hash01(seed, 1)
end

-- Returns (u, cycle): u in [0, 1) while this fish is in the air at time t,
-- otherwise nil. `cycle` identifies the current period (for splash bookkeeping).
function FishJump.phase(seed: number, t: number, cfg: Config): (number?, number)
	local period = FishJump.period(seed, cfg)
	local offset = FishJump.hash01(seed, 2) * period
	local x = (t - offset) / period
	local cycle = math.floor(x)
	local into = (x - cycle) * period
	if not cfg.Enabled or into >= cfg.Duration then
		return nil, cycle
	end
	if FishJump.hash01(seed, cycle + 3) >= cfg.Chance then
		return nil, cycle
	end
	return into / cfg.Duration, cycle
end

-- Size-aware, modest jump height.
function FishJump.height(swimLen: any, cfg: Config): number
	local L = if type(swimLen) == "number" and swimLen > 0 then swimLen else 4
	return math.clamp(L * cfg.HeightPerStud, cfg.MinHeight, cfg.MaxHeight)
end

-- Vertical offset and (pitch-scaled) vertical velocity along the arc.
function FishJump.offset(u: number, height: number, cfg: Config): (number, number)
	u = math.clamp(u, 0, 1)
	local dy = height * 4 * u * (1 - u)
	local vy = height * 4 * (1 - 2 * u) / cfg.Duration * cfg.PitchScale
	return dy, vy
end

-- Jumps only away from the ends of the river, so the arc stays in bounds.
function FishJump.allowed(z: number, minZ: any, maxZ: any, cfg: Config): boolean
	if type(minZ) ~= "number" or type(maxZ) ~= "number" then
		return false
	end
	return z >= minZ + cfg.EdgeMargin and z <= maxZ - cfg.EdgeMargin
end

return FishJump
]], new = [[
--!strict
-- FishJump (ModuleScript in ReplicatedStorage). Pure, visual-only jump
-- schedule for river fish, used by the patched FishSwimClient.
--
-- Each fish gets its own period and time offset from its Seed; in every
-- period it jumps with probability Chance, decided by an integer hash of
-- (Seed, cycle number). Everything is a pure function of server time and
-- Seed, so every client sees the same fish jump at the same moment, jumps are
-- sparse and staggered, and a player joining mid-jump computes the same arc.
-- The hash uses exact 32-bit integer ops (not sin()) because server time is
-- ~1.7e9 and large-argument sin() can differ between devices.
--
-- Nothing here touches the server: net catch eligibility (NetLiftScript's
-- fishPos uses only x/z from the spawn attributes) and rewards are unchanged,
-- and the jump never moves the fish's x/z, so it stays in its lane.

-- [JumpRate v1] Periods halved (16-28 s -> 8-14 s): about twice the jumps,
-- still one period and offset per fish, so they stay staggered.
local FishJump = {}

export type Config = {
	Enabled: boolean,
	Chance: number, -- probability a fish jumps in one of its periods
	PeriodMin: number, -- seconds; each fish's period is in [PeriodMin, PeriodMin + PeriodSpread)
	PeriodSpread: number,
	Duration: number, -- seconds in the air
	HeightPerStud: number, -- jump height per stud of SwimLen
	MinHeight: number,
	MaxHeight: number,
	PitchScale: number, -- 1 = nose follows the arc exactly; lower = gentler pitch
	EdgeMargin: number, -- no jumps this close to the river's MinZ/MaxZ
	SkipSnakes: boolean, -- CrystalSerpent-style long fish don't jump
	Splash: boolean,
	SplashPool: number, -- max simultaneous splash rings
}

FishJump.Defaults = {
	Enabled = true,
	Chance = 0.35,
	PeriodMin = 8, -- JumpRate: was 16 (jumps about twice as often)
	PeriodSpread = 6, -- JumpRate: was 12 (jumps about twice as often)
	Duration = 0.9,
	HeightPerStud = 0.45,
	MinHeight = 1.2,
	MaxHeight = 3.2,
	PitchScale = 0.6,
	EdgeMargin = 6,
	SkipSnakes = true,
	Splash = true,
	SplashPool = 10,
} :: Config

local TWO32 = 4294967296

local function u32(v: number): number
	return math.floor(v) % TWO32
end

local function xorshift(h: number): number
	h = bit32.bxor(h, bit32.lshift(h, 13))
	h = bit32.bxor(h, bit32.rshift(h, 17))
	h = bit32.bxor(h, bit32.lshift(h, 5))
	return h
end

-- Deterministic hash of two integers to [0, 1).
function FishJump.hash01(a: number, b: number): number
	local h = bit32.bxor(u32(a), bit32.lrotate(u32(b), 16), 0x9E3779B9)
	if h == 0 then
		h = 0x6D2B79F5
	end
	h = xorshift(xorshift(xorshift(h)))
	return h / TWO32
end

-- Reads optional overrides from attributes on the river folder:
-- JumpEnabled (bool), JumpChance (0..1), JumpHeightScale (multiplier).
function FishJump.config(get: (string) -> any): Config
	local cfg = table.clone(FishJump.Defaults)
	local enabled = get("JumpEnabled")
	if type(enabled) == "boolean" then
		cfg.Enabled = enabled
	end
	local chance = get("JumpChance")
	if type(chance) == "number" and chance == chance then
		cfg.Chance = math.clamp(chance, 0, 1)
	end
	local scale = get("JumpHeightScale")
	if type(scale) == "number" and scale == scale and scale > 0 then
		cfg.HeightPerStud *= scale
		cfg.MinHeight *= scale
		cfg.MaxHeight *= scale
	end
	return cfg
end

function FishJump.period(seed: number, cfg: Config): number
	return cfg.PeriodMin + cfg.PeriodSpread * FishJump.hash01(seed, 1)
end

-- Returns (u, cycle): u in [0, 1) while this fish is in the air at time t,
-- otherwise nil. `cycle` identifies the current period (for splash bookkeeping).
function FishJump.phase(seed: number, t: number, cfg: Config): (number?, number)
	local period = FishJump.period(seed, cfg)
	local offset = FishJump.hash01(seed, 2) * period
	local x = (t - offset) / period
	local cycle = math.floor(x)
	local into = (x - cycle) * period
	if not cfg.Enabled or into >= cfg.Duration then
		return nil, cycle
	end
	if FishJump.hash01(seed, cycle + 3) >= cfg.Chance then
		return nil, cycle
	end
	return into / cfg.Duration, cycle
end

-- Size-aware, modest jump height.
function FishJump.height(swimLen: any, cfg: Config): number
	local L = if type(swimLen) == "number" and swimLen > 0 then swimLen else 4
	return math.clamp(L * cfg.HeightPerStud, cfg.MinHeight, cfg.MaxHeight)
end

-- Vertical offset and (pitch-scaled) vertical velocity along the arc.
function FishJump.offset(u: number, height: number, cfg: Config): (number, number)
	u = math.clamp(u, 0, 1)
	local dy = height * 4 * u * (1 - u)
	local vy = height * 4 * (1 - 2 * u) / cfg.Duration * cfg.PitchScale
	return dy, vy
end

-- Jumps only away from the ends of the river, so the arc stays in bounds.
function FishJump.allowed(z: number, minZ: any, maxZ: any, cfg: Config): boolean
	if type(minZ) ~= "number" or type(maxZ) ~= "number" then
		return false
	end
	return z >= minZ + cfg.EdgeMargin and z <= maxZ - cfg.EdgeMargin
end

return FishJump
]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {

}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackJumpRate.lua restores the previous sources)")
