--[[
	InstallFishJump.lua - GENERATED by tools/fish-jump/build/build_installer.py.
	Edit tools/fish-jump sources and rebuild; don't edit this file.

	Opt-in Studio installer: river fish occasionally jump out of the water
	(client visuals only). Independent of the aquarium install; either order.
	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	Checks first and changes nothing if any fails:
	  * ReplicatedStorage.FishJump and ServerStorage.FishJumpBackup don't exist
	  * exactly one LocalScript named FishSwimClient (searched in StarterPlayer,
	    StarterGui, ReplicatedFirst) whose source matches the reviewed original
	Then, in one undo step ("Install FishJump"):
	  1. backs up FishSwimClient to ServerStorage.FishJumpBackup
	     (disabled copies of the original and the patched script)
	  2. replaces FishSwimClient.Source with the patched version
	  3. adds ReplicatedStorage.FishJump (ModuleScript)
	Added objects carry FishJumpOwned = true; UninstallFishJump.lua removes
	only those and restores the original source.

	Tuning / kill switch, live, no reinstall: attributes on
	Workspace.SwimmingFish: JumpEnabled (bool), JumpChance (0..1),
	JumpHeightScale (multiplier). Defaults are in the FishJump module.
]]

local ALLOW_SOURCE_MISMATCH = false

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ReplicatedFirst = game:GetService("ReplicatedFirst")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local StarterGui = game:GetService("StarterGui")
local StarterPlayer = game:GetService("StarterPlayer")

local ORIGINAL = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, math.max(0, lt - LAUNCH_RISE) * 11)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]]
local PATCHED = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
--
-- [FishJump patch v1] Changes vs. the original are marked "FishJump". With
-- ReplicatedStorage.FishJump installed, fish occasionally jump out of the water
-- (visual only: the same x/z lane path, so net catches and rewards are
-- unchanged) with a small splash on takeoff and landing. Without the module
-- this script behaves exactly like the original.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

------------------------------------------------ jumps (FishJump)
local Jump, jumpCfg = nil, nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishJump")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Jump = m
			jumpCfg = m.config(function(name) return folder:GetAttribute(name) end)
		else
			warn("[FishSwimClient] FishJump failed to load; no jumps: " .. tostring(m))
		end
	end
end
local riverMinZ, riverMaxZ = folder:GetAttribute("MinZ"), folder:GetAttribute("MaxZ")
if Jump then
	-- JumpEnabled / JumpChance / JumpHeightScale on SwimmingFish apply live
	folder.AttributeChanged:Connect(function(name)
		if name:sub(1, 4) == "Jump" then
			local splashOn = jumpCfg.Splash
			jumpCfg = Jump.config(function(n) return folder:GetAttribute(n) end)
			jumpCfg.Splash = splashOn -- the splash pool is built once at startup
		end
	end)
end

-- pooled splash discs, reused (never more than SplashPool at once)
local SPLASH_TIME = 0.5
local splashPool, activeSplashes = {}, {}
if Jump and jumpCfg.Splash then
	local splashFolder = Instance.new("Folder")
	splashFolder.Name = "FishJumpSplashes"
	for _ = 1, jumpCfg.SplashPool do
		local ring = Instance.new("Part")
		ring.Name = "Splash"
		ring.Shape = Enum.PartType.Cylinder
		ring.Anchored = true
		ring.CanCollide = false
		ring.CanQuery = false
		ring.CanTouch = false
		ring.CastShadow = false
		ring.Material = Enum.Material.SmoothPlastic
		ring.Color = Color3.fromRGB(235, 248, 255)
		ring.Transparency = 1
		ring.Size = Vector3.new(0.08, 1, 1)
		ring.CFrame = CFrame.new(0, -1000, 0)
		ring.Parent = splashFolder
		table.insert(splashPool, ring)
	end
	splashFolder.Parent = workspace
	script.Destroying:Connect(function() splashFolder:Destroy() end)
end

local function splash(x, z, L)
	local ring = table.remove(splashPool)
	if not ring then return end
	table.insert(activeSplashes, { ring = ring, t0 = os.clock(), x = x, z = z, r = math.clamp(L * 0.5, 1, 3) })
end

local function updateSplashes()
	local now = os.clock()
	for i = #activeSplashes, 1, -1 do
		local s = activeSplashes[i]
		local u = (now - s.t0) / SPLASH_TIME
		if u >= 1 then
			s.ring.Transparency = 1
			s.ring.CFrame = CFrame.new(0, -1000, 0)
			table.insert(splashPool, s.ring)
			table.remove(activeSplashes, i)
		else
			local d = s.r * (1 + 3 * u)
			s.ring.Size = Vector3.new(0.08, d, d)
			s.ring.CFrame = CFrame.new(s.x, surfaceY + 0.05, s.z) * CFrame.Angles(0, 0, math.pi / 2)
			s.ring.Transparency = 0.35 + 0.65 * u
		end
	end
end

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

-- Jump-adjusted position/direction at `time` (pure: no splashes). x/z are
-- untouched; only height and nose pitch change. Returns pos, dir, u, cycle.
local function jumpAt(f, time, pos, dir)
	if f.snake and jumpCfg.SkipSnakes then return pos, dir, nil, nil end
	local u, cycle = Jump.phase(f.seed, time, jumpCfg)
	-- judge the river-end margin at takeoff, so a jump never gets cut off mid-air
	if not u or not Jump.allowed(pos.Z - f.speed * u * jumpCfg.Duration, riverMinZ, riverMaxZ, jumpCfg) then
		return pos, dir, nil, cycle
	end
	local dy, vy = Jump.offset(u, f.jumpH, jumpCfg)
	return pos + Vector3.new(0, dy, 0), Vector3.new(dir.X, vy, dir.Z), u, cycle
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	f.seed = seed -- FishJump
	f.jumpH = Jump and Jump.height(L, jumpCfg) -- FishJump
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	if Jump then updateSplashes() end -- FishJump
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			-- FishJump: launch from wherever the fish was in its jump (no snap back to the water)
			if Jump then p0, dir0 = jumpAt(f, f.caughtT, p0, dir0) end
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, math.max(0, lt - LAUNCH_RISE) * 11)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		if Jump then -- FishJump
			local u, cycle
			pos, dir, u, cycle = jumpAt(f, t, pos, dir)
			if u then
				if f.jumpCycle ~= cycle then
					f.jumpCycle = cycle
					-- splash only for jumps seen taking off, not ones already in the air on join
					f.splashCycle = if u < 0.25 then cycle else nil
					if f.splashCycle and jumpCfg.Splash then splash(pos.X, pos.Z, L) end
				end
				f.airborne = true
			elseif f.airborne then
				f.airborne = false
				if jumpCfg.Splash and f.splashCycle ~= nil and f.splashCycle == f.jumpCycle then splash(pos.X, pos.Z, L) end
			end
		end
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]]
local MODULE = [[
--!strict
-- FishJump (ModuleScript in ReplicatedStorage). Pure, visual-only jump
-- schedule for river fish, used by the patched FishSwimClient.
--
-- Each fish gets its own period and time offset from its Seed; in every
-- period it jumps with probability Chance, decided by an integer hash of
-- (Seed, cycle number). Everything is a pure function of server time and
-- Seed, so every client sees the same fish jump at the same moment, jumps are
-- sparse and staggered, and a player joining mid-jump computes the same arc.
-- The hash uses exact 32-bit integer ops (not sin()) because server time is
-- ~1.7e9 and large-argument sin() can differ between devices.
--
-- Nothing here touches the server: net catch eligibility (NetLiftScript's
-- fishPos uses only x/z from the spawn attributes) and rewards are unchanged,
-- and the jump never moves the fish's x/z, so it stays in its lane.

local FishJump = {}

export type Config = {
	Enabled: boolean,
	Chance: number, -- probability a fish jumps in one of its periods
	PeriodMin: number, -- seconds; each fish's period is in [PeriodMin, PeriodMin + PeriodSpread)
	PeriodSpread: number,
	Duration: number, -- seconds in the air
	HeightPerStud: number, -- jump height per stud of SwimLen
	MinHeight: number,
	MaxHeight: number,
	PitchScale: number, -- 1 = nose follows the arc exactly; lower = gentler pitch
	EdgeMargin: number, -- no jumps this close to the river's MinZ/MaxZ
	SkipSnakes: boolean, -- CrystalSerpent-style long fish don't jump
	Splash: boolean,
	SplashPool: number, -- max simultaneous splash rings
}

FishJump.Defaults = {
	Enabled = true,
	Chance = 0.35,
	PeriodMin = 16,
	PeriodSpread = 12,
	Duration = 0.9,
	HeightPerStud = 0.45,
	MinHeight = 1.2,
	MaxHeight = 3.2,
	PitchScale = 0.6,
	EdgeMargin = 6,
	SkipSnakes = true,
	Splash = true,
	SplashPool = 10,
} :: Config

local TWO32 = 4294967296

local function u32(v: number): number
	return math.floor(v) % TWO32
end

local function xorshift(h: number): number
	h = bit32.bxor(h, bit32.lshift(h, 13))
	h = bit32.bxor(h, bit32.rshift(h, 17))
	h = bit32.bxor(h, bit32.lshift(h, 5))
	return h
end

-- Deterministic hash of two integers to [0, 1).
function FishJump.hash01(a: number, b: number): number
	local h = bit32.bxor(u32(a), bit32.lrotate(u32(b), 16), 0x9E3779B9)
	if h == 0 then
		h = 0x6D2B79F5
	end
	h = xorshift(xorshift(xorshift(h)))
	return h / TWO32
end

-- Reads optional overrides from attributes on the river folder:
-- JumpEnabled (bool), JumpChance (0..1), JumpHeightScale (multiplier).
function FishJump.config(get: (string) -> any): Config
	local cfg = table.clone(FishJump.Defaults)
	local enabled = get("JumpEnabled")
	if type(enabled) == "boolean" then
		cfg.Enabled = enabled
	end
	local chance = get("JumpChance")
	if type(chance) == "number" and chance == chance then
		cfg.Chance = math.clamp(chance, 0, 1)
	end
	local scale = get("JumpHeightScale")
	if type(scale) == "number" and scale == scale and scale > 0 then
		cfg.HeightPerStud *= scale
		cfg.MinHeight *= scale
		cfg.MaxHeight *= scale
	end
	return cfg
end

function FishJump.period(seed: number, cfg: Config): number
	return cfg.PeriodMin + cfg.PeriodSpread * FishJump.hash01(seed, 1)
end

-- Returns (u, cycle): u in [0, 1) while this fish is in the air at time t,
-- otherwise nil. `cycle` identifies the current period (for splash bookkeeping).
function FishJump.phase(seed: number, t: number, cfg: Config): (number?, number)
	local period = FishJump.period(seed, cfg)
	local offset = FishJump.hash01(seed, 2) * period
	local x = (t - offset) / period
	local cycle = math.floor(x)
	local into = (x - cycle) * period
	if not cfg.Enabled or into >= cfg.Duration then
		return nil, cycle
	end
	if FishJump.hash01(seed, cycle + 3) >= cfg.Chance then
		return nil, cycle
	end
	return into / cfg.Duration, cycle
end

-- Size-aware, modest jump height.
function FishJump.height(swimLen: any, cfg: Config): number
	local L = if type(swimLen) == "number" and swimLen > 0 then swimLen else 4
	return math.clamp(L * cfg.HeightPerStud, cfg.MinHeight, cfg.MaxHeight)
end

-- Vertical offset and (pitch-scaled) vertical velocity along the arc.
function FishJump.offset(u: number, height: number, cfg: Config): (number, number)
	u = math.clamp(u, 0, 1)
	local dy = height * 4 * u * (1 - u)
	local vy = height * 4 * (1 - 2 * u) / cfg.Duration * cfg.PitchScale
	return dy, vy
end

-- Jumps only away from the ends of the river, so the arc stays in bounds.
function FishJump.allowed(z: number, minZ: any, maxZ: any, cfg: Config): boolean
	if type(minZ) ~= "number" or type(maxZ) ~= "number" then
		return false
	end
	return z >= minZ + cfg.EdgeMargin and z <= maxZ - cfg.EdgeMargin
end

return FishJump
]]

local TAG = "FishJumpOwned"

local function fail(msg)
	warn("[InstallFishJump] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

if ReplicatedStorage:FindFirstChild("FishJump") or ServerStorage:FindFirstChild("FishJumpBackup") then
	return fail("already installed (run UninstallFishJump.lua first)")
end

local found = {}
for _, container in ipairs({ StarterPlayer, StarterGui, ReplicatedFirst }) do
	for _, d in ipairs(container:GetDescendants()) do
		if d.Name == "FishSwimClient" and d:IsA("LocalScript") then
			table.insert(found, d)
		end
	end
end
if #found ~= 1 then
	return fail(string.format("expected exactly 1 LocalScript named FishSwimClient, found %d", #found))
end
local client = found[1]
local sourceMatches = normalize(client.Source) == normalize(ORIGINAL)
if not sourceMatches and not ALLOW_SOURCE_MISMATCH then
	return fail(
		client:GetFullName()
			.. " source differs from the reviewed original (tools/fish-jump/studio/FishSwimClient.original.lua)."
			.. " Send the current source for a re-patch, or set ALLOW_SOURCE_MISMATCH after review"
	)
end

local river = workspace:FindFirstChild("SwimmingFish")
if not (river and type(river:GetAttribute("MinZ")) == "number" and type(river:GetAttribute("MaxZ")) == "number") then
	warn("[InstallFishJump] Workspace.SwimmingFish MinZ/MaxZ not found: fish won't jump until they exist.")
end

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording("Install FishJump")
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before Install FishJump")
	end)
end

local originalSource = client.Source
local created = {}

local built, buildErr = pcall(function()
	local backup = Instance.new("Folder")
	backup.Name = "FishJumpBackup"
	backup:SetAttribute(TAG, true)
	backup:SetAttribute("OriginalPath", client:GetFullName())
	table.insert(created, backup)
	local originalCopy = client:Clone()
	originalCopy.Name = "FishSwimClient_original"
	originalCopy.Enabled = false
	originalCopy.Parent = backup
	local target = Instance.new("ObjectValue")
	target.Name = "Target"
	target.Value = client
	target.Parent = backup
	backup.Parent = ServerStorage

	client.Source = PATCHED
	local patchedCopy = client:Clone()
	patchedCopy.Name = "FishSwimClient_patched"
	patchedCopy.Enabled = false
	patchedCopy.Parent = backup

	local module = Instance.new("ModuleScript")
	module.Name = "FishJump"
	module.Source = MODULE
	module:SetAttribute(TAG, true)
	table.insert(created, module)
	module.Parent = ReplicatedStorage
end)

if not built then
	pcall(function()
		client.Source = originalSource
	end)
	for i = #created, 1, -1 do
		pcall(function()
			created[i]:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint("Install FishJump")
	end)
end

if not built then
	return warn("[InstallFishJump] Failed and rolled back: " .. tostring(buildErr))
end
print("[InstallFishJump] Installed:")
print("  patched " .. client:GetFullName() .. " (original backed up in ServerStorage.FishJumpBackup)")
print("  added   ReplicatedStorage.FishJump")
print("  tune    Workspace.SwimmingFish attributes JumpEnabled / JumpChance / JumpHeightScale (live)")
if not sourceMatches then
	warn("[InstallFishJump] Patched despite a source mismatch (ALLOW_SOURCE_MISMATCH).")
end
