--[[
	InstallHarpoonBlend.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Harpoon mid-jump fix. Fish jumps are drawn on each client; the harpoon aims
	at the fish's swim line. A fish struck in the air used to snap straight down
	to the water on the first frame of the pull. Now the pull starts from its
	height in the air and eases down onto the rope; the rest of the harpoon path
	and its timing are unchanged (the server's reel, toss and suck still match).
	Changes one LocalScript: FishSwimClient (the fish-jump version, or grinder
	dwell on top of it: the matching patch is picked by exact source).
	Requires: fish jumps (InstallFishJump.lua). If you use grinder dwell,
	install it FIRST (it refuses after this). Roll this back before either.

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.HarpoonBlendBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackHarpoonBlend.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallHarpoonBlend"
local BACKUP = "HarpoonBlendBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "FishJumpBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "HarpoonBlendBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "FishSwimClient", where = "localscript:FishSwimClient", class = "LocalScript", variants = { { label = "jump", old = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
--
-- [FishJump patch v1] Changes vs. the original are marked "FishJump". With
-- ReplicatedStorage.FishJump installed, fish occasionally jump out of the water
-- (visual only: the same x/z lane path, so net catches and rewards are
-- unchanged) with a small splash on takeoff and landing. Without the module
-- this script behaves exactly like the original.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

------------------------------------------------ jumps (FishJump)
local Jump, jumpCfg = nil, nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishJump")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Jump = m
			jumpCfg = m.config(function(name) return folder:GetAttribute(name) end)
		else
			warn("[FishSwimClient] FishJump failed to load; no jumps: " .. tostring(m))
		end
	end
end
local riverMinZ, riverMaxZ = folder:GetAttribute("MinZ"), folder:GetAttribute("MaxZ")
if Jump then
	-- JumpEnabled / JumpChance / JumpHeightScale on SwimmingFish apply live
	folder.AttributeChanged:Connect(function(name)
		if name:sub(1, 4) == "Jump" then
			local splashOn = jumpCfg.Splash
			jumpCfg = Jump.config(function(n) return folder:GetAttribute(n) end)
			jumpCfg.Splash = splashOn -- the splash pool is built once at startup
		end
	end)
end

-- pooled splash discs, reused (never more than SplashPool at once)
local SPLASH_TIME = 0.5
local splashPool, activeSplashes = {}, {}
if Jump and jumpCfg.Splash then
	local splashFolder = Instance.new("Folder")
	splashFolder.Name = "FishJumpSplashes"
	for _ = 1, jumpCfg.SplashPool do
		local ring = Instance.new("Part")
		ring.Name = "Splash"
		ring.Shape = Enum.PartType.Cylinder
		ring.Anchored = true
		ring.CanCollide = false
		ring.CanQuery = false
		ring.CanTouch = false
		ring.CastShadow = false
		ring.Material = Enum.Material.SmoothPlastic
		ring.Color = Color3.fromRGB(235, 248, 255)
		ring.Transparency = 1
		ring.Size = Vector3.new(0.08, 1, 1)
		ring.CFrame = CFrame.new(0, -1000, 0)
		ring.Parent = splashFolder
		table.insert(splashPool, ring)
	end
	splashFolder.Parent = workspace
	script.Destroying:Connect(function() splashFolder:Destroy() end)
end

local function splash(x, z, L)
	local ring = table.remove(splashPool)
	if not ring then return end
	table.insert(activeSplashes, { ring = ring, t0 = os.clock(), x = x, z = z, r = math.clamp(L * 0.5, 1, 3) })
end

local function updateSplashes()
	local now = os.clock()
	for i = #activeSplashes, 1, -1 do
		local s = activeSplashes[i]
		local u = (now - s.t0) / SPLASH_TIME
		if u >= 1 then
			s.ring.Transparency = 1
			s.ring.CFrame = CFrame.new(0, -1000, 0)
			table.insert(splashPool, s.ring)
			table.remove(activeSplashes, i)
		else
			local d = s.r * (1 + 3 * u)
			s.ring.Size = Vector3.new(0.08, d, d)
			s.ring.CFrame = CFrame.new(s.x, surfaceY + 0.05, s.z) * CFrame.Angles(0, 0, math.pi / 2)
			s.ring.Transparency = 0.35 + 0.65 * u
		end
	end
end

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

-- Jump-adjusted position/direction at `time` (pure: no splashes). x/z are
-- untouched; only height and nose pitch change. Returns pos, dir, u, cycle.
local function jumpAt(f, time, pos, dir)
	if f.snake and jumpCfg.SkipSnakes then return pos, dir, nil, nil end
	local u, cycle = Jump.phase(f.seed, time, jumpCfg)
	-- judge the river-end margin at takeoff, so a jump never gets cut off mid-air
	if not u or not Jump.allowed(pos.Z - f.speed * u * jumpCfg.Duration, riverMinZ, riverMaxZ, jumpCfg) then
		return pos, dir, nil, cycle
	end
	local dy, vy = Jump.offset(u, f.jumpH, jumpCfg)
	return pos + Vector3.new(0, dy, 0), Vector3.new(dir.X, vy, dir.Z), u, cycle
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	f.seed = seed -- FishJump
	f.jumpH = Jump and Jump.height(L, jumpCfg) -- FishJump
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	m:GetAttributeChangedSignal("HarpoonT"):Connect(function()
		f.hHit, f.hBack = m:GetAttribute("HarpoonHit"), m:GetAttribute("HarpoonBack")
		f.harpoonT = m:GetAttribute("HarpoonT")
	end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	if Jump then updateSplashes() end -- FishJump
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.harpoonT and f.hHit and f.hBack and grinder then
			-- HARPOONED: dragged back along the rope, tossed into the grinder, sucked in
			local PULL, TOSS, SUCK = 0.6, 0.8, 0.45
			local lt = t - f.harpoonT
			local pos, rot, s = nil, nil, 1
			local away = Vector3.new(f.hHit.X - f.hBack.X, 0, f.hHit.Z - f.hBack.Z).Unit
			if lt < PULL then
				local u = math.clamp(lt / PULL, 0, 1)
				u = u * u * (3 - 2 * u)
				pos = f.hHit:Lerp(f.hBack, u) + Vector3.new(0, math.sin(u * math.pi) * 2, 0)
				rot = CFrame.lookAt(Vector3.zero, away) * CFrame.Angles(0, math.sin(t * 30) * 0.5, math.sin(t * 22) * 0.3)
			elseif lt < PULL + TOSS then
				local u = (lt - PULL) / TOSS
				pos = f.hBack:Lerp(grinder, u) + Vector3.new(0, 12 * 4 * u * (1 - u), 0)
				rot = CFrame.fromAxisAngle(f.spinAxis, u * 12)
			else
				local u = math.clamp((lt - PULL - TOSS) / SUCK, 0, 1)
				local e = u * u
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * 1.2 * (1 - u), -3.2 * e, math.sin(a) * 1.2 * (1 - u))
				rot = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0)
				s = 1 - 0.92 * e
			end
			local base = rot + pos
			for i, p in ipairs(f.parts) do
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * rel)
			end
			continue
		end

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			-- FishJump: launch from wherever the fish was in its jump (no snap back to the water)
			if Jump then p0, dir0 = jumpAt(f, f.caughtT, p0, dir0) end
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, math.max(0, lt - LAUNCH_RISE) * 11)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		if Jump then -- FishJump
			local u, cycle
			pos, dir, u, cycle = jumpAt(f, t, pos, dir)
			if u then
				if f.jumpCycle ~= cycle then
					f.jumpCycle = cycle
					-- splash only for jumps seen taking off, not ones already in the air on join
					f.splashCycle = if u < 0.25 then cycle else nil
					if f.splashCycle and jumpCfg.Splash then splash(pos.X, pos.Z, L) end
				end
				f.airborne = true
			elseif f.airborne then
				f.airborne = false
				if jumpCfg.Splash and f.splashCycle ~= nil and f.splashCycle == f.jumpCycle then splash(pos.X, pos.Z, L) end
			end
		end
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]], new = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
--
-- [HarpoonBlend patch] A fish harpooned mid-jump starts its pull from where it
-- is in the air and eases down onto the rope, instead of snapping to the
-- water. Changes marked "HarpoonBlend".
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
--
-- [FishJump patch v1] Changes vs. the original are marked "FishJump". With
-- ReplicatedStorage.FishJump installed, fish occasionally jump out of the water
-- (visual only: the same x/z lane path, so net catches and rewards are
-- unchanged) with a small splash on takeoff and landing. Without the module
-- this script behaves exactly like the original.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

------------------------------------------------ jumps (FishJump)
local Jump, jumpCfg = nil, nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishJump")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Jump = m
			jumpCfg = m.config(function(name) return folder:GetAttribute(name) end)
		else
			warn("[FishSwimClient] FishJump failed to load; no jumps: " .. tostring(m))
		end
	end
end
local riverMinZ, riverMaxZ = folder:GetAttribute("MinZ"), folder:GetAttribute("MaxZ")
if Jump then
	-- JumpEnabled / JumpChance / JumpHeightScale on SwimmingFish apply live
	folder.AttributeChanged:Connect(function(name)
		if name:sub(1, 4) == "Jump" then
			local splashOn = jumpCfg.Splash
			jumpCfg = Jump.config(function(n) return folder:GetAttribute(n) end)
			jumpCfg.Splash = splashOn -- the splash pool is built once at startup
		end
	end)
end

-- pooled splash discs, reused (never more than SplashPool at once)
local SPLASH_TIME = 0.5
local splashPool, activeSplashes = {}, {}
if Jump and jumpCfg.Splash then
	local splashFolder = Instance.new("Folder")
	splashFolder.Name = "FishJumpSplashes"
	for _ = 1, jumpCfg.SplashPool do
		local ring = Instance.new("Part")
		ring.Name = "Splash"
		ring.Shape = Enum.PartType.Cylinder
		ring.Anchored = true
		ring.CanCollide = false
		ring.CanQuery = false
		ring.CanTouch = false
		ring.CastShadow = false
		ring.Material = Enum.Material.SmoothPlastic
		ring.Color = Color3.fromRGB(235, 248, 255)
		ring.Transparency = 1
		ring.Size = Vector3.new(0.08, 1, 1)
		ring.CFrame = CFrame.new(0, -1000, 0)
		ring.Parent = splashFolder
		table.insert(splashPool, ring)
	end
	splashFolder.Parent = workspace
	script.Destroying:Connect(function() splashFolder:Destroy() end)
end

local function splash(x, z, L)
	local ring = table.remove(splashPool)
	if not ring then return end
	table.insert(activeSplashes, { ring = ring, t0 = os.clock(), x = x, z = z, r = math.clamp(L * 0.5, 1, 3) })
end

local function updateSplashes()
	local now = os.clock()
	for i = #activeSplashes, 1, -1 do
		local s = activeSplashes[i]
		local u = (now - s.t0) / SPLASH_TIME
		if u >= 1 then
			s.ring.Transparency = 1
			s.ring.CFrame = CFrame.new(0, -1000, 0)
			table.insert(splashPool, s.ring)
			table.remove(activeSplashes, i)
		else
			local d = s.r * (1 + 3 * u)
			s.ring.Size = Vector3.new(0.08, d, d)
			s.ring.CFrame = CFrame.new(s.x, surfaceY + 0.05, s.z) * CFrame.Angles(0, 0, math.pi / 2)
			s.ring.Transparency = 0.35 + 0.65 * u
		end
	end
end

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

-- Jump-adjusted position/direction at `time` (pure: no splashes). x/z are
-- untouched; only height and nose pitch change. Returns pos, dir, u, cycle.
local function jumpAt(f, time, pos, dir)
	if f.snake and jumpCfg.SkipSnakes then return pos, dir, nil, nil end
	local u, cycle = Jump.phase(f.seed, time, jumpCfg)
	-- judge the river-end margin at takeoff, so a jump never gets cut off mid-air
	if not u or not Jump.allowed(pos.Z - f.speed * u * jumpCfg.Duration, riverMinZ, riverMaxZ, jumpCfg) then
		return pos, dir, nil, cycle
	end
	local dy, vy = Jump.offset(u, f.jumpH, jumpCfg)
	return pos + Vector3.new(0, dy, 0), Vector3.new(dir.X, vy, dir.Z), u, cycle
end

-- HarpoonBlend: the server aims at the swim line; if the fish was mid-jump at
-- the hit, its height above that line (cached per hit). Zero without jumps.
local function harpoonLift(f)
	if not Jump then return Vector3.zero end
	if f.hLiftT ~= f.harpoonT then
		f.hLiftT = f.harpoonT
		local sp, sd = swimPos(f, f.harpoonT)
		local jp = jumpAt(f, f.harpoonT, sp, sd)
		f.hLift = Vector3.new(0, math.max(0, jp.Y - sp.Y), 0)
	end
	return f.hLift
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	f.seed = seed -- FishJump
	f.jumpH = Jump and Jump.height(L, jumpCfg) -- FishJump
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	m:GetAttributeChangedSignal("HarpoonT"):Connect(function()
		f.hHit, f.hBack = m:GetAttribute("HarpoonHit"), m:GetAttribute("HarpoonBack")
		f.harpoonT = m:GetAttribute("HarpoonT")
	end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	if Jump then updateSplashes() end -- FishJump
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.harpoonT and f.hHit and f.hBack and grinder then
			-- HARPOONED: dragged back along the rope, tossed into the grinder, sucked in
			local PULL, TOSS, SUCK = 0.6, 0.8, 0.45
			local lt = t - f.harpoonT
			local pos, rot, s = nil, nil, 1
			local away = Vector3.new(f.hHit.X - f.hBack.X, 0, f.hHit.Z - f.hBack.Z).Unit
			if lt < PULL then
				local u = math.clamp(lt / PULL, 0, 1)
				u = u * u * (3 - 2 * u)
				pos = f.hHit:Lerp(f.hBack, u) + Vector3.new(0, math.sin(u * math.pi) * 2, 0)
					+ harpoonLift(f) * (1 - u) -- HarpoonBlend: from the air down onto the rope
				rot = CFrame.lookAt(Vector3.zero, away) * CFrame.Angles(0, math.sin(t * 30) * 0.5, math.sin(t * 22) * 0.3)
			elseif lt < PULL + TOSS then
				local u = (lt - PULL) / TOSS
				pos = f.hBack:Lerp(grinder, u) + Vector3.new(0, 12 * 4 * u * (1 - u), 0)
				rot = CFrame.fromAxisAngle(f.spinAxis, u * 12)
			else
				local u = math.clamp((lt - PULL - TOSS) / SUCK, 0, 1)
				local e = u * u
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * 1.2 * (1 - u), -3.2 * e, math.sin(a) * 1.2 * (1 - u))
				rot = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0)
				s = 1 - 0.92 * e
			end
			local base = rot + pos
			for i, p in ipairs(f.parts) do
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * rel)
			end
			continue
		end

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			-- FishJump: launch from wherever the fish was in its jump (no snap back to the water)
			if Jump then p0, dir0 = jumpAt(f, f.caughtT, p0, dir0) end
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, math.max(0, lt - LAUNCH_RISE) * 11)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		if Jump then -- FishJump
			local u, cycle
			pos, dir, u, cycle = jumpAt(f, t, pos, dir)
			if u then
				if f.jumpCycle ~= cycle then
					f.jumpCycle = cycle
					-- splash only for jumps seen taking off, not ones already in the air on join
					f.splashCycle = if u < 0.25 then cycle else nil
					if f.splashCycle and jumpCfg.Splash then splash(pos.X, pos.Z, L) end
				end
				f.airborne = true
			elseif f.airborne then
				f.airborne = false
				if jumpCfg.Splash and f.splashCycle ~= nil and f.splashCycle == f.jumpCycle then splash(pos.X, pos.Z, L) end
			end
		end
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]] }, { label = "dwell-jump", old = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
--
-- [GrinderDwell patch v1] Changes marked "GrinderDwell": with
-- ReplicatedStorage.GrinderDwell installed, a launched fish lands on the
-- rollers, tumbles/shudders there for about a second, then spirals in and
-- shrinks. The timeline comes from that module (NetLiftScript uses the same
-- numbers). Without it the launch is exactly the original.
--
-- [FishJump patch v1] Changes vs. the original are marked "FishJump". With
-- ReplicatedStorage.FishJump installed, fish occasionally jump out of the water
-- (visual only: the same x/z lane path, so net catches and rewards are
-- unchanged) with a small splash on takeoff and landing. Without the module
-- this script behaves exactly like the original.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

-- GrinderDwell: optional ~1 s tumble on the rollers before the pull-in
-- (missing module -> original timing)
local Dwell = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("GrinderDwell")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Dwell = m
		else
			warn("[GrinderDwell] failed to load, using original timing: " .. tostring(m))
		end
	end
end
if Dwell then LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = Dwell.Rise, Dwell.Fly, Dwell.Drop end
local DWELL = if Dwell then Dwell.Dwell else 0
local TUMBLE = if Dwell then Dwell.TumbleSpeed else 0

------------------------------------------------ jumps (FishJump)
local Jump, jumpCfg = nil, nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishJump")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Jump = m
			jumpCfg = m.config(function(name) return folder:GetAttribute(name) end)
		else
			warn("[FishSwimClient] FishJump failed to load; no jumps: " .. tostring(m))
		end
	end
end
local riverMinZ, riverMaxZ = folder:GetAttribute("MinZ"), folder:GetAttribute("MaxZ")
if Jump then
	-- JumpEnabled / JumpChance / JumpHeightScale on SwimmingFish apply live
	folder.AttributeChanged:Connect(function(name)
		if name:sub(1, 4) == "Jump" then
			local splashOn = jumpCfg.Splash
			jumpCfg = Jump.config(function(n) return folder:GetAttribute(n) end)
			jumpCfg.Splash = splashOn -- the splash pool is built once at startup
		end
	end)
end

-- pooled splash discs, reused (never more than SplashPool at once)
local SPLASH_TIME = 0.5
local splashPool, activeSplashes = {}, {}
if Jump and jumpCfg.Splash then
	local splashFolder = Instance.new("Folder")
	splashFolder.Name = "FishJumpSplashes"
	for _ = 1, jumpCfg.SplashPool do
		local ring = Instance.new("Part")
		ring.Name = "Splash"
		ring.Shape = Enum.PartType.Cylinder
		ring.Anchored = true
		ring.CanCollide = false
		ring.CanQuery = false
		ring.CanTouch = false
		ring.CastShadow = false
		ring.Material = Enum.Material.SmoothPlastic
		ring.Color = Color3.fromRGB(235, 248, 255)
		ring.Transparency = 1
		ring.Size = Vector3.new(0.08, 1, 1)
		ring.CFrame = CFrame.new(0, -1000, 0)
		ring.Parent = splashFolder
		table.insert(splashPool, ring)
	end
	splashFolder.Parent = workspace
	script.Destroying:Connect(function() splashFolder:Destroy() end)
end

local function splash(x, z, L)
	local ring = table.remove(splashPool)
	if not ring then return end
	table.insert(activeSplashes, { ring = ring, t0 = os.clock(), x = x, z = z, r = math.clamp(L * 0.5, 1, 3) })
end

local function updateSplashes()
	local now = os.clock()
	for i = #activeSplashes, 1, -1 do
		local s = activeSplashes[i]
		local u = (now - s.t0) / SPLASH_TIME
		if u >= 1 then
			s.ring.Transparency = 1
			s.ring.CFrame = CFrame.new(0, -1000, 0)
			table.insert(splashPool, s.ring)
			table.remove(activeSplashes, i)
		else
			local d = s.r * (1 + 3 * u)
			s.ring.Size = Vector3.new(0.08, d, d)
			s.ring.CFrame = CFrame.new(s.x, surfaceY + 0.05, s.z) * CFrame.Angles(0, 0, math.pi / 2)
			s.ring.Transparency = 0.35 + 0.65 * u
		end
	end
end

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

-- Jump-adjusted position/direction at `time` (pure: no splashes). x/z are
-- untouched; only height and nose pitch change. Returns pos, dir, u, cycle.
local function jumpAt(f, time, pos, dir)
	if f.snake and jumpCfg.SkipSnakes then return pos, dir, nil, nil end
	local u, cycle = Jump.phase(f.seed, time, jumpCfg)
	-- judge the river-end margin at takeoff, so a jump never gets cut off mid-air
	if not u or not Jump.allowed(pos.Z - f.speed * u * jumpCfg.Duration, riverMinZ, riverMaxZ, jumpCfg) then
		return pos, dir, nil, cycle
	end
	local dy, vy = Jump.offset(u, f.jumpH, jumpCfg)
	return pos + Vector3.new(0, dy, 0), Vector3.new(dir.X, vy, dir.Z), u, cycle
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	f.seed = seed -- FishJump
	f.jumpH = Jump and Jump.height(L, jumpCfg) -- FishJump
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	m:GetAttributeChangedSignal("HarpoonT"):Connect(function()
		f.hHit, f.hBack = m:GetAttribute("HarpoonHit"), m:GetAttribute("HarpoonBack")
		f.harpoonT = m:GetAttribute("HarpoonT")
	end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	if Jump then updateSplashes() end -- FishJump
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.harpoonT and f.hHit and f.hBack and grinder then
			-- HARPOONED: dragged back along the rope, tossed into the grinder, sucked in
			local PULL, TOSS, SUCK = 0.6, 0.8, 0.45
			local lt = t - f.harpoonT
			local pos, rot, s = nil, nil, 1
			local away = Vector3.new(f.hHit.X - f.hBack.X, 0, f.hHit.Z - f.hBack.Z).Unit
			if lt < PULL then
				local u = math.clamp(lt / PULL, 0, 1)
				u = u * u * (3 - 2 * u)
				pos = f.hHit:Lerp(f.hBack, u) + Vector3.new(0, math.sin(u * math.pi) * 2, 0)
				rot = CFrame.lookAt(Vector3.zero, away) * CFrame.Angles(0, math.sin(t * 30) * 0.5, math.sin(t * 22) * 0.3)
			elseif lt < PULL + TOSS then
				local u = (lt - PULL) / TOSS
				pos = f.hBack:Lerp(grinder, u) + Vector3.new(0, 12 * 4 * u * (1 - u), 0)
				rot = CFrame.fromAxisAngle(f.spinAxis, u * 12)
			elseif lt < PULL + TOSS + DWELL then
				-- GrinderDwell: a harpooned fish rests and tumbles on the rollers too
				local d = lt - PULL - TOSS
				local ox, oy, oz = Dwell.dwellOffset(d, f.phase)
				pos = grinder + Vector3.new(ox, oy, oz)
				rot = CFrame.fromAxisAngle(f.spinAxis, 12 + d * TUMBLE)
			else
				local u = math.clamp((lt - PULL - TOSS - DWELL) / SUCK, 0, 1) -- GrinderDwell: after the rest
				local e = u * u
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * 1.2 * (1 - u), -3.2 * e, math.sin(a) * 1.2 * (1 - u))
				if Dwell then -- GrinderDwell: spiral in from where the rest ended
					local ox, oy, oz = Dwell.dropOffset(u)
					pos = grinder + Vector3.new(ox, oy, oz)
				end
				rot = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0)
				s = 1 - 0.92 * e
			end
			local base = rot + pos
			for i, p in ipairs(f.parts) do
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * rel)
			end
			continue
		end

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			-- FishJump: launch from wherever the fish was in its jump (no snap back to the water)
			if Jump then p0, dir0 = jumpAt(f, f.caughtT, p0, dir0) end
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY + DWELL then
				-- GrinderDwell: settle onto the rollers, tumble and shudder there
				local ox, oy, oz = Dwell.dwellOffset(lt - LAUNCH_RISE - LAUNCH_FLY, f.phase)
				pos = grinder + Vector3.new(ox, oy, oz)
			elseif Dwell then
				-- GrinderDwell: spiral in from the rollers while shrinking
				local ox, oy, oz, scale = Dwell.dropOffset((lt - LAUNCH_RISE - LAUNCH_FLY - DWELL) / LAUNCH_DROP)
				pos = grinder + Vector3.new(ox, oy, oz)
				f.suck = scale
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY - DWELL) / LAUNCH_DROP, 0, 1) -- GrinderDwell
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11 + DWELL * TUMBLE)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				-- GrinderDwell: fast spin in flight, slower tumble on the rollers
				local flight = math.min(math.max(0, lt - LAUNCH_RISE), LAUNCH_FLY)
				local tumble = math.max(0, lt - LAUNCH_RISE - LAUNCH_FLY)
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, flight * 11 + tumble * TUMBLE)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		if Jump then -- FishJump
			local u, cycle
			pos, dir, u, cycle = jumpAt(f, t, pos, dir)
			if u then
				if f.jumpCycle ~= cycle then
					f.jumpCycle = cycle
					-- splash only for jumps seen taking off, not ones already in the air on join
					f.splashCycle = if u < 0.25 then cycle else nil
					if f.splashCycle and jumpCfg.Splash then splash(pos.X, pos.Z, L) end
				end
				f.airborne = true
			elseif f.airborne then
				f.airborne = false
				if jumpCfg.Splash and f.splashCycle ~= nil and f.splashCycle == f.jumpCycle then splash(pos.X, pos.Z, L) end
			end
		end
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]], new = [[
-- Animates the fish stream: every fish swims up the river (toward +Z) with a body-wave wiggle.
--
-- [HarpoonBlend patch] A fish harpooned mid-jump starts its pull from where it
-- is in the air and eases down onto the rope, instead of snapping to the
-- water. Changes marked "HarpoonBlend".
-- Position comes from server time + attributes set by FishSpawner, so all players see the same thing.
-- Fish that get a CaughtT attribute (set by the net) are launched in an arc into the grinder.
--
-- [GrinderDwell patch v1] Changes marked "GrinderDwell": with
-- ReplicatedStorage.GrinderDwell installed, a launched fish lands on the
-- rollers, tumbles/shudders there for about a second, then spirals in and
-- shrinks. The timeline comes from that module (NetLiftScript uses the same
-- numbers). Without it the launch is exactly the original.
--
-- [FishJump patch v1] Changes vs. the original are marked "FishJump". With
-- ReplicatedStorage.FishJump installed, fish occasionally jump out of the water
-- (visual only: the same x/z lane path, so net catches and rewards are
-- unchanged) with a small splash on takeoff and landing. Without the module
-- this script behaves exactly like the original.
local RunService = game:GetService("RunService")
local folder = workspace:WaitForChild("SwimmingFish")
local surfaceY = folder:GetAttribute("SurfaceY")

local LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = 0.12, 0.95, 0.55

-- GrinderDwell: optional ~1 s tumble on the rollers before the pull-in
-- (missing module -> original timing)
local Dwell = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("GrinderDwell")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Dwell = m
		else
			warn("[GrinderDwell] failed to load, using original timing: " .. tostring(m))
		end
	end
end
if Dwell then LAUNCH_RISE, LAUNCH_FLY, LAUNCH_DROP = Dwell.Rise, Dwell.Fly, Dwell.Drop end
local DWELL = if Dwell then Dwell.Dwell else 0
local TUMBLE = if Dwell then Dwell.TumbleSpeed else 0

------------------------------------------------ jumps (FishJump)
local Jump, jumpCfg = nil, nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishJump")
	if mod and mod:IsA("ModuleScript") then
		local ok, m = pcall(require, mod)
		if ok and type(m) == "table" then
			Jump = m
			jumpCfg = m.config(function(name) return folder:GetAttribute(name) end)
		else
			warn("[FishSwimClient] FishJump failed to load; no jumps: " .. tostring(m))
		end
	end
end
local riverMinZ, riverMaxZ = folder:GetAttribute("MinZ"), folder:GetAttribute("MaxZ")
if Jump then
	-- JumpEnabled / JumpChance / JumpHeightScale on SwimmingFish apply live
	folder.AttributeChanged:Connect(function(name)
		if name:sub(1, 4) == "Jump" then
			local splashOn = jumpCfg.Splash
			jumpCfg = Jump.config(function(n) return folder:GetAttribute(n) end)
			jumpCfg.Splash = splashOn -- the splash pool is built once at startup
		end
	end)
end

-- pooled splash discs, reused (never more than SplashPool at once)
local SPLASH_TIME = 0.5
local splashPool, activeSplashes = {}, {}
if Jump and jumpCfg.Splash then
	local splashFolder = Instance.new("Folder")
	splashFolder.Name = "FishJumpSplashes"
	for _ = 1, jumpCfg.SplashPool do
		local ring = Instance.new("Part")
		ring.Name = "Splash"
		ring.Shape = Enum.PartType.Cylinder
		ring.Anchored = true
		ring.CanCollide = false
		ring.CanQuery = false
		ring.CanTouch = false
		ring.CastShadow = false
		ring.Material = Enum.Material.SmoothPlastic
		ring.Color = Color3.fromRGB(235, 248, 255)
		ring.Transparency = 1
		ring.Size = Vector3.new(0.08, 1, 1)
		ring.CFrame = CFrame.new(0, -1000, 0)
		ring.Parent = splashFolder
		table.insert(splashPool, ring)
	end
	splashFolder.Parent = workspace
	script.Destroying:Connect(function() splashFolder:Destroy() end)
end

local function splash(x, z, L)
	local ring = table.remove(splashPool)
	if not ring then return end
	table.insert(activeSplashes, { ring = ring, t0 = os.clock(), x = x, z = z, r = math.clamp(L * 0.5, 1, 3) })
end

local function updateSplashes()
	local now = os.clock()
	for i = #activeSplashes, 1, -1 do
		local s = activeSplashes[i]
		local u = (now - s.t0) / SPLASH_TIME
		if u >= 1 then
			s.ring.Transparency = 1
			s.ring.CFrame = CFrame.new(0, -1000, 0)
			table.insert(splashPool, s.ring)
			table.remove(activeSplashes, i)
		else
			local d = s.r * (1 + 3 * u)
			s.ring.Size = Vector3.new(0.08, d, d)
			s.ring.CFrame = CFrame.new(s.x, surfaceY + 0.05, s.z) * CFrame.Angles(0, 0, math.pi / 2)
			s.ring.Transparency = 0.35 + 0.65 * u
		end
	end
end

local fishes = {}

local function swimPos(f, t)
	local age = t - f.spawnT
	local z = f.startZ + f.speed * age
	local x = f.laneX + f.weaveA * math.sin(f.weaveF * t + f.phase)
	local y = surfaceY - 0.6 + 0.12 * math.sin(t * 1.7 + f.phase)
	local dx = f.weaveA * f.weaveF * math.cos(f.weaveF * t + f.phase)
	return Vector3.new(x, y, z), Vector3.new(dx, 0, f.speed)
end

-- Jump-adjusted position/direction at `time` (pure: no splashes). x/z are
-- untouched; only height and nose pitch change. Returns pos, dir, u, cycle.
local function jumpAt(f, time, pos, dir)
	if f.snake and jumpCfg.SkipSnakes then return pos, dir, nil, nil end
	local u, cycle = Jump.phase(f.seed, time, jumpCfg)
	-- judge the river-end margin at takeoff, so a jump never gets cut off mid-air
	if not u or not Jump.allowed(pos.Z - f.speed * u * jumpCfg.Duration, riverMinZ, riverMaxZ, jumpCfg) then
		return pos, dir, nil, cycle
	end
	local dy, vy = Jump.offset(u, f.jumpH, jumpCfg)
	return pos + Vector3.new(0, dy, 0), Vector3.new(dir.X, vy, dir.Z), u, cycle
end

-- HarpoonBlend: the server aims at the swim line; if the fish was mid-jump at
-- the hit, its height above that line (cached per hit). Zero without jumps.
local function harpoonLift(f)
	if not Jump then return Vector3.zero end
	if f.hLiftT ~= f.harpoonT then
		f.hLiftT = f.harpoonT
		local sp, sd = swimPos(f, f.harpoonT)
		local jp = jumpAt(f, f.harpoonT, sp, sd)
		f.hLift = Vector3.new(0, math.max(0, jp.Y - sp.Y), 0)
	end
	return f.hLift
end

local function addFish(m)
	if fishes[m] then return end
	local root = m:WaitForChild("Root", 5)
	if not root or not m.Parent then return end
	local L = m:GetAttribute("SwimLen") or 4
	local seed = m:GetAttribute("Seed") or 1
	local f = {
		model = m, L = L,
		vertical = m:GetAttribute("Vertical") == true,
		snake = m.Name == "CrystalSerpent",
		spawnT = m:GetAttribute("SpawnT"), startZ = m:GetAttribute("StartZ"),
		speed = m:GetAttribute("Speed"), laneX = m:GetAttribute("LaneX"),
		caughtT = m:GetAttribute("CaughtT"),
		weaveA = 0.8 + (seed % 7) * 0.15, weaveF = 0.35 + (seed % 5) * 0.08, phase = seed * 1.7,
		spinAxis = Vector3.new(math.sin(seed), 0.6, math.cos(seed * 1.3)).Unit,
		parts = {}, rels = {}, zs = {}, sizes = {},
	}
	f.omega = math.clamp(7 * math.sqrt(3 / L), 3, 9)
	f.k = 2 * math.pi / (L * 1.2)
	f.B = (f.snake and 0.13 or 0.08) * L
	f.seed = seed -- FishJump
	f.jumpH = Jump and Jump.height(L, jumpCfg) -- FishJump
	local rootCF = root.CFrame
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") then
			local rel = rootCF:ToObjectSpace(p.CFrame)
			table.insert(f.parts, p)
			table.insert(f.rels, rel)
			table.insert(f.zs, rel.Position.Z)
			table.insert(f.sizes, p.Size)
		end
	end
	m:GetAttributeChangedSignal("SpawnT"):Connect(function() f.spawnT = m:GetAttribute("SpawnT") end)
	m:GetAttributeChangedSignal("CaughtT"):Connect(function() f.caughtT = m:GetAttribute("CaughtT") end)
	m:GetAttributeChangedSignal("HarpoonT"):Connect(function()
		f.hHit, f.hBack = m:GetAttribute("HarpoonHit"), m:GetAttribute("HarpoonBack")
		f.harpoonT = m:GetAttribute("HarpoonT")
	end)
	fishes[m] = f
end

for _, m in ipairs(folder:GetChildren()) do task.spawn(addFish, m) end
folder.ChildAdded:Connect(function(m) task.spawn(addFish, m) end)
folder.ChildRemoved:Connect(function(m) fishes[m] = nil end)

local allParts, allCFs = {}, {}
local function push(p, cf) table.insert(allParts, p) table.insert(allCFs, cf) end

RunService.RenderStepped:Connect(function()
	local t = workspace:GetServerTimeNow()
	local grinder = folder:GetAttribute("GrinderPos")
	table.clear(allParts) table.clear(allCFs)
	if Jump then updateSplashes() end -- FishJump
	for m, f in pairs(fishes) do
		if not m.Parent then fishes[m] = nil continue end
		local L, B, k, w = f.L, f.B, f.k, f.omega

		if f.harpoonT and f.hHit and f.hBack and grinder then
			-- HARPOONED: dragged back along the rope, tossed into the grinder, sucked in
			local PULL, TOSS, SUCK = 0.6, 0.8, 0.45
			local lt = t - f.harpoonT
			local pos, rot, s = nil, nil, 1
			local away = Vector3.new(f.hHit.X - f.hBack.X, 0, f.hHit.Z - f.hBack.Z).Unit
			if lt < PULL then
				local u = math.clamp(lt / PULL, 0, 1)
				u = u * u * (3 - 2 * u)
				pos = f.hHit:Lerp(f.hBack, u) + Vector3.new(0, math.sin(u * math.pi) * 2, 0)
					+ harpoonLift(f) * (1 - u) -- HarpoonBlend: from the air down onto the rope
				rot = CFrame.lookAt(Vector3.zero, away) * CFrame.Angles(0, math.sin(t * 30) * 0.5, math.sin(t * 22) * 0.3)
			elseif lt < PULL + TOSS then
				local u = (lt - PULL) / TOSS
				pos = f.hBack:Lerp(grinder, u) + Vector3.new(0, 12 * 4 * u * (1 - u), 0)
				rot = CFrame.fromAxisAngle(f.spinAxis, u * 12)
			elseif lt < PULL + TOSS + DWELL then
				-- GrinderDwell: a harpooned fish rests and tumbles on the rollers too
				local d = lt - PULL - TOSS
				local ox, oy, oz = Dwell.dwellOffset(d, f.phase)
				pos = grinder + Vector3.new(ox, oy, oz)
				rot = CFrame.fromAxisAngle(f.spinAxis, 12 + d * TUMBLE)
			else
				local u = math.clamp((lt - PULL - TOSS - DWELL) / SUCK, 0, 1) -- GrinderDwell: after the rest
				local e = u * u
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * 1.2 * (1 - u), -3.2 * e, math.sin(a) * 1.2 * (1 - u))
				if Dwell then -- GrinderDwell: spiral in from where the rest ended
					local ox, oy, oz = Dwell.dropOffset(u)
					pos = grinder + Vector3.new(ox, oy, oz)
				end
				rot = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0)
				s = 1 - 0.92 * e
			end
			local base = rot + pos
			for i, p in ipairs(f.parts) do
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * rel)
			end
			continue
		end

		if f.caughtT and grinder then
			-- LAUNCHED: pop up with the net, arc into the grinder, tumble, drop in
			local lt = t - f.caughtT
			local p0, dir0 = swimPos(f, f.caughtT)
			-- FishJump: launch from wherever the fish was in its jump (no snap back to the water)
			if Jump then p0, dir0 = jumpAt(f, f.caughtT, p0, dir0) end
			local top = p0 + Vector3.new(0, 6, 0)
			local pos
			if lt < LAUNCH_RISE then
				local e = 1 - (1 - lt / LAUNCH_RISE) ^ 3
				pos = p0:Lerp(top, e)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY then
				local u = (lt - LAUNCH_RISE) / LAUNCH_FLY
				pos = top:Lerp(grinder, u) + Vector3.new(0, 9 * 4 * u * (1 - u), 0)
			elseif lt < LAUNCH_RISE + LAUNCH_FLY + DWELL then
				-- GrinderDwell: settle onto the rollers, tumble and shudder there
				local ox, oy, oz = Dwell.dwellOffset(lt - LAUNCH_RISE - LAUNCH_FLY, f.phase)
				pos = grinder + Vector3.new(ox, oy, oz)
			elseif Dwell then
				-- GrinderDwell: spiral in from the rollers while shrinking
				local ox, oy, oz, scale = Dwell.dropOffset((lt - LAUNCH_RISE - LAUNCH_FLY - DWELL) / LAUNCH_DROP)
				pos = grinder + Vector3.new(ox, oy, oz)
				f.suck = scale
			else
				-- SUCKED IN: spiral down into the rollers while spinning and shrinking
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY) / LAUNCH_DROP, 0, 1)
				local e = u * u
				local r = 1.2 * (1 - u)
				local a = u * math.pi * 5
				pos = grinder + Vector3.new(math.cos(a) * r, -3.2 * e, math.sin(a) * r)
				f.suck = 1 - 0.92 * e
			end
			local s = f.suck or 1
			local startRot = CFrame.lookAt(p0, p0 + dir0).Rotation
			local rot
			if f.suck then
				local u = math.clamp((lt - LAUNCH_RISE - LAUNCH_FLY - DWELL) / LAUNCH_DROP, 0, 1) -- GrinderDwell
				local flightEnd = startRot * CFrame.fromAxisAngle(f.spinAxis, LAUNCH_FLY * 11 + DWELL * TUMBLE)
				local dive = CFrame.Angles(0, u * math.pi * 6, 0) * CFrame.Angles(math.rad(-80), 0, 0) -- whirl nose-first down
				rot = flightEnd:Lerp(dive, math.min(1, u * 2.5))
			else
				-- GrinderDwell: fast spin in flight, slower tumble on the rollers
				local flight = math.min(math.max(0, lt - LAUNCH_RISE), LAUNCH_FLY)
				local tumble = math.max(0, lt - LAUNCH_RISE - LAUNCH_FLY)
				rot = startRot * CFrame.fromAxisAngle(f.spinAxis, flight * 11 + tumble * TUMBLE)
			end
			local base = rot + pos
			local flap = math.sin(t * 25) * 0.35 -- panicked tail flap
			for i, p in ipairs(f.parts) do
				local zr = f.zs[i]
				local weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1)
				local rel = f.rels[i]
				if s < 1 then
					p.Size = f.sizes[i] * s
					rel = CFrame.new(rel.Position * s) * rel.Rotation
				end
				push(p, base * CFrame.new(flap * weight * L * 0.12 * s, 0, 0) * rel)
			end
			continue
		end

		local pos, dir = swimPos(f, t)
		if Jump then -- FishJump
			local u, cycle
			pos, dir, u, cycle = jumpAt(f, t, pos, dir)
			if u then
				if f.jumpCycle ~= cycle then
					f.jumpCycle = cycle
					-- splash only for jumps seen taking off, not ones already in the air on join
					f.splashCycle = if u < 0.25 then cycle else nil
					if f.splashCycle and jumpCfg.Splash then splash(pos.X, pos.Z, L) end
				end
				f.airborne = true
			elseif f.airborne then
				f.airborne = false
				if jumpCfg.Splash and f.splashCycle ~= nil and f.splashCycle == f.jumpCycle then splash(pos.X, pos.Z, L) end
			end
		end
		local base = CFrame.lookAt(pos, pos + dir)
		for i, p in ipairs(f.parts) do
			local zr = f.zs[i]
			local weight
			if f.snake then
				weight = 0.35 + 0.65 * math.clamp((zr + L / 2) / L, 0, 1)
			else
				weight = math.clamp((zr + 0.1 * L) / (0.6 * L), 0, 1) ^ 1.5
			end
			local phase = w * t - k * zr
			local off = B * weight * math.sin(phase)
			local ang = -B * weight * k * math.cos(phase)
			local rel = f.rels[i]
			local cf
			if f.vertical then
				cf = CFrame.new(0, off, 0) * CFrame.new(rel.Position) * CFrame.Angles(ang, 0, 0) * rel.Rotation
			else
				cf = CFrame.new(off, 0, 0) * CFrame.new(rel.Position) * CFrame.Angles(0, -ang, 0) * rel.Rotation
			end
			push(p, base * cf)
		end
	end
	if #allParts > 0 then
		workspace:BulkMoveTo(allParts, allCFs, Enum.BulkMoveMode.FireCFrameChanged)
	end
end)
]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {
	{ key = "FishJump", where = "ReplicatedStorage/FishJump", class = "ModuleScript", source = [[
--!strict
-- FishJump (ModuleScript in ReplicatedStorage). Pure, visual-only jump
-- schedule for river fish, used by the patched FishSwimClient.
--
-- Each fish gets its own period and time offset from its Seed; in every
-- period it jumps with probability Chance, decided by an integer hash of
-- (Seed, cycle number). Everything is a pure function of server time and
-- Seed, so every client sees the same fish jump at the same moment, jumps are
-- sparse and staggered, and a player joining mid-jump computes the same arc.
-- The hash uses exact 32-bit integer ops (not sin()) because server time is
-- ~1.7e9 and large-argument sin() can differ between devices.
--
-- Nothing here touches the server: net catch eligibility (NetLiftScript's
-- fishPos uses only x/z from the spawn attributes) and rewards are unchanged,
-- and the jump never moves the fish's x/z, so it stays in its lane.

local FishJump = {}

export type Config = {
	Enabled: boolean,
	Chance: number, -- probability a fish jumps in one of its periods
	PeriodMin: number, -- seconds; each fish's period is in [PeriodMin, PeriodMin + PeriodSpread)
	PeriodSpread: number,
	Duration: number, -- seconds in the air
	HeightPerStud: number, -- jump height per stud of SwimLen
	MinHeight: number,
	MaxHeight: number,
	PitchScale: number, -- 1 = nose follows the arc exactly; lower = gentler pitch
	EdgeMargin: number, -- no jumps this close to the river's MinZ/MaxZ
	SkipSnakes: boolean, -- CrystalSerpent-style long fish don't jump
	Splash: boolean,
	SplashPool: number, -- max simultaneous splash rings
}

FishJump.Defaults = {
	Enabled = true,
	Chance = 0.35,
	PeriodMin = 16,
	PeriodSpread = 12,
	Duration = 0.9,
	HeightPerStud = 0.45,
	MinHeight = 1.2,
	MaxHeight = 3.2,
	PitchScale = 0.6,
	EdgeMargin = 6,
	SkipSnakes = true,
	Splash = true,
	SplashPool = 10,
} :: Config

local TWO32 = 4294967296

local function u32(v: number): number
	return math.floor(v) % TWO32
end

local function xorshift(h: number): number
	h = bit32.bxor(h, bit32.lshift(h, 13))
	h = bit32.bxor(h, bit32.rshift(h, 17))
	h = bit32.bxor(h, bit32.lshift(h, 5))
	return h
end

-- Deterministic hash of two integers to [0, 1).
function FishJump.hash01(a: number, b: number): number
	local h = bit32.bxor(u32(a), bit32.lrotate(u32(b), 16), 0x9E3779B9)
	if h == 0 then
		h = 0x6D2B79F5
	end
	h = xorshift(xorshift(xorshift(h)))
	return h / TWO32
end

-- Reads optional overrides from attributes on the river folder:
-- JumpEnabled (bool), JumpChance (0..1), JumpHeightScale (multiplier).
function FishJump.config(get: (string) -> any): Config
	local cfg = table.clone(FishJump.Defaults)
	local enabled = get("JumpEnabled")
	if type(enabled) == "boolean" then
		cfg.Enabled = enabled
	end
	local chance = get("JumpChance")
	if type(chance) == "number" and chance == chance then
		cfg.Chance = math.clamp(chance, 0, 1)
	end
	local scale = get("JumpHeightScale")
	if type(scale) == "number" and scale == scale and scale > 0 then
		cfg.HeightPerStud *= scale
		cfg.MinHeight *= scale
		cfg.MaxHeight *= scale
	end
	return cfg
end

function FishJump.period(seed: number, cfg: Config): number
	return cfg.PeriodMin + cfg.PeriodSpread * FishJump.hash01(seed, 1)
end

-- Returns (u, cycle): u in [0, 1) while this fish is in the air at time t,
-- otherwise nil. `cycle` identifies the current period (for splash bookkeeping).
function FishJump.phase(seed: number, t: number, cfg: Config): (number?, number)
	local period = FishJump.period(seed, cfg)
	local offset = FishJump.hash01(seed, 2) * period
	local x = (t - offset) / period
	local cycle = math.floor(x)
	local into = (x - cycle) * period
	if not cfg.Enabled or into >= cfg.Duration then
		return nil, cycle
	end
	if FishJump.hash01(seed, cycle + 3) >= cfg.Chance then
		return nil, cycle
	end
	return into / cfg.Duration, cycle
end

-- Size-aware, modest jump height.
function FishJump.height(swimLen: any, cfg: Config): number
	local L = if type(swimLen) == "number" and swimLen > 0 then swimLen else 4
	return math.clamp(L * cfg.HeightPerStud, cfg.MinHeight, cfg.MaxHeight)
end

-- Vertical offset and (pitch-scaled) vertical velocity along the arc.
function FishJump.offset(u: number, height: number, cfg: Config): (number, number)
	u = math.clamp(u, 0, 1)
	local dy = height * 4 * u * (1 - u)
	local vy = height * 4 * (1 - 2 * u) / cfg.Duration * cfg.PitchScale
	return dy, vy
end

-- Jumps only away from the ends of the river, so the arc stays in bounds.
function FishJump.allowed(z: number, minZ: any, maxZ: any, cfg: Config): boolean
	if type(minZ) ~= "number" or type(maxZ) ~= "number" then
		return false
	end
	return z >= minZ + cfg.EdgeMargin and z <= maxZ - cfg.EdgeMargin
end

return FishJump
]] },
}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackHarpoonBlend.lua restores the previous sources)")
