--[[
	InstallMoneyHud.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Money HUD: both MoneyController LocalScripts (StarterGui.Money.MoneyFrame
	and StarterGui.ScreenGui.Buttons.Frames.MoneyFrame) show leaderstats.Money,
	the balance EconomyService keeps. They used to wait forever on the missing
	ReplicatedStorage.FormatModule and LocalPlayer.Money, so the labels never
	updated.
	  * "Loading..." until the player's Money has loaded, then the balance,
	    following every change ($1.23K style, never rounded up; FormatModule is
	    used if it exists and works)
	  * the multiplier labels keep their old formulas WHEN their inputs exist
	    (Rebirths + Modules.RebirthDefinitions, Upgrades.RobuxMultiplier,
	    FriendsMultiplier, VIP); a label whose inputs are missing is hidden.
	    Display only: no payout applies any multiplier.
	Changes only those two LocalScripts. Nothing server side.
	Requires: rod offers (EconomyService makes leaderstats.Money). Independent
	of every other install here.

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyMoneyHudBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackMoneyHud.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallMoneyHud"
local BACKUP = "EconomyMoneyHudBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomyRodOffersBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyMoneyHudBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "MoneyHud", where = "StarterGui/Money/MoneyFrame/MoneyController", class = "LocalScript", variants = { { label = "live", old = [[
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Decompiled with Potassium's decompiler.

local Players = game:GetService("Players");
local ReplicatedStorage = game:GetService("ReplicatedStorage");
local LocalPlayer = Players.LocalPlayer;
local FormatModule = require(ReplicatedStorage:WaitForChild("FormatModule"));
local RebirthDefinitions = require(ReplicatedStorage:WaitForChild("Modules"):WaitForChild("RebirthDefinitions"));
local Money = script.Parent:WaitForChild("Money");
local FriendsMulti = script.Parent:WaitForChild("FriendsMulti");
local VIPMulti = script.Parent:WaitForChild("VIPMulti");
local u1 = {};
local u2 = {};

for _, child in ipairs(script.Parent:GetChildren()) do
    if child:IsA("TextLabel") and child.Name == "RebirthMulti" then
        table.insert(u2, child);
    elseif child:IsA("TextLabel") and child.Name == "RobuxMulti" then
        table.insert(u1, child);
    end;
end;

local function formatMoney(p3) -- Line: 20
    -- upvalues: FormatModule (copy)
    return "$" .. FormatModule:AbbreviateNumbers(p3);
end;

local Money2 = LocalPlayer:WaitForChild("Money");
local Rebirths = LocalPlayer:WaitForChild("Rebirths");
local FriendsMultiplier = LocalPlayer:WaitForChild("FriendsMultiplier");
local VIP = LocalPlayer:WaitForChild("VIP");
local RobuxMultiplier = LocalPlayer:WaitForChild("Upgrades"):WaitForChild("RobuxMultiplier");

if not Money2:IsA("NumberValue") then
    warn("[MoneyController] Player.Money must be a NumberValue");

    return;
end;

local function formatMultiplier(p4) -- Line: 35
    local v5 = tonumber(p4) or 1;

    if v5 == math.floor(v5) then
        local v6 = math.floor(v5);

        return tostring(v6);
    end;

    local v7 = string.format("%.2f", v5);
    local v8 = string.gsub(v7, "0+$", "");

    return string.gsub(v8, "%.$", "");
end;

local function updateMultipliers() -- Line: 50
    -- upvalues: RebirthDefinitions (copy), Rebirths (copy), RobuxMultiplier (copy), VIP (copy), u2 (copy), formatMultiplier (copy), FriendsMulti (copy), FriendsMultiplier (copy), VIPMulti (copy), u1 (copy)
    local v9 = RebirthDefinitions:GetMultiplier(Rebirths.Value);
    local v10 = math.floor(RobuxMultiplier.Value);
    local v11 = 2 ^ math.clamp(v10, 0, 15);
    local v12 = VIP.Value and 1.25 or 1;

    for _, v in ipairs(u2) do
        v.Text = "x" .. formatMultiplier(v9);
    end;

    FriendsMulti.Text = "x" .. formatMultiplier(FriendsMultiplier.Value);
    VIPMulti.Text = "x" .. formatMultiplier(v12);

    for _, v in ipairs(u1) do
        v.Text = "x" .. formatMultiplier(v11);
    end;
end;

Money.Text = "$" .. FormatModule:AbbreviateNumbers(Money2.Value);
updateMultipliers();
Money2:GetPropertyChangedSignal("Value"):Connect(function() -- Line: 46, Name: updateMoney
    -- upvalues: Money (copy), Money2 (copy), FormatModule (copy)
    Money.Text = "$" .. FormatModule:AbbreviateNumbers(Money2.Value);
end);
Rebirths:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
RobuxMultiplier:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
FriendsMultiplier:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
VIP:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
]], new = [[
-- MoneyController (LocalScript in a MoneyFrame; the same source runs in
-- StarterGui.Money.MoneyFrame and StarterGui.ScreenGui.Buttons.Frames.MoneyFrame).
--
-- The Money label shows leaderstats.Money: EconomyService's authoritative
-- balance, created once the player's Money has loaded. Until then (and if it
-- never loads) the label says "Loading..." instead of a number.
--
-- The multiplier labels (RebirthMulti, RobuxMulti, FriendsMulti, VIPMulti)
-- work as before WHEN their inputs exist (Rebirths + Modules.RebirthDefinitions,
-- Upgrades.RobuxMultiplier, FriendsMultiplier, VIP on the player). A label
-- whose inputs are missing is hidden: nothing is shown or assumed. These are
-- display only; EconomyService applies no multipliers to any payout.
--
-- Uses ReplicatedStorage.FormatModule for the number if it exists and works,
-- else its own abbreviation. Never waits on anything that may not exist.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local LocalPlayer = Players.LocalPlayer
local frame = script.Parent
local moneyLabel = frame:WaitForChild("Money")
local CURRENCY = "Money" -- EconomyService Config.CurrencyName
local LOADING = "Loading..."

------------------------------------------------------------ number format

local function optionalModule(inst: Instance?): any
	if inst and inst:IsA("ModuleScript") then
		local ok, mod = pcall(require, inst)
		if ok and type(mod) == "table" then
			return mod
		end
	end
	return nil
end

local FormatModule = optionalModule(ReplicatedStorage:FindFirstChild("FormatModule"))

local SUFFIXES = { "K", "M", "B", "T", "Qa", "Qi" }
-- 1234 -> "1.23K"; truncated, never rounded up (999999 -> "999.99K")
local function abbreviate(n: number): string
	n = math.floor(n)
	if n < 1000 then
		return tostring(n)
	end
	local i = 0
	while i < #SUFFIXES and n >= 1000 ^ (i + 1) do
		i += 1
	end
	local hundredths = n // (1000 ^ i / 100)
	local text = string.format("%d.%02d", hundredths // 100, hundredths % 100)
	text = string.gsub(text, "%.?0+$", "")
	return text .. SUFFIXES[i]
end

local function formatMoney(n: number): string
	if FormatModule and type(FormatModule.AbbreviateNumbers) == "function" then
		local ok, text = pcall(FormatModule.AbbreviateNumbers, FormatModule, n)
		if ok and (type(text) == "string" or type(text) == "number") then
			return "$" .. tostring(text)
		end
	end
	return "$" .. abbreviate(n)
end

------------------------------------------------------------ Money (leaderstats.Money)

local moneyValue: Instance? = nil
local moneyConn: RBXScriptConnection? = nil
local statsConns: { RBXScriptConnection } = {}

local function renderMoney()
	local v = moneyValue
	local n = if v and v.Parent then (v :: any).Value else nil
	if type(n) == "number" and n == n and n >= 0 and n ~= math.huge then
		moneyLabel.Text = formatMoney(n)
	else
		moneyLabel.Text = LOADING
	end
end

local function bindMoney()
	local stats = LocalPlayer:FindFirstChild("leaderstats")
	local v = stats and stats:FindFirstChild(CURRENCY)
	if v and not (v:IsA("IntValue") or v:IsA("NumberValue")) then
		v = nil
	end
	if v ~= moneyValue then
		if moneyConn then
			moneyConn:Disconnect()
			moneyConn = nil
		end
		moneyValue = v
		if v then
			moneyConn = v.Changed:Connect(renderMoney)
		end
	end
	renderMoney()
end

local function bindStats()
	for _, c in ipairs(statsConns) do
		c:Disconnect()
	end
	table.clear(statsConns)
	local stats = LocalPlayer:FindFirstChild("leaderstats")
	if stats then
		table.insert(statsConns, stats.ChildAdded:Connect(bindMoney))
		table.insert(statsConns, stats.ChildRemoved:Connect(bindMoney))
	end
	bindMoney()
end

------------------------------------------------------------ multipliers (only when their inputs exist)

local rebirthLabels, robuxLabels = {}, {}
for _, child in ipairs(frame:GetChildren()) do
	if child:IsA("TextLabel") and child.Name == "RebirthMulti" then
		table.insert(rebirthLabels, child)
	elseif child:IsA("TextLabel") and child.Name == "RobuxMulti" then
		table.insert(robuxLabels, child)
	end
end
local friendsLabel = frame:FindFirstChild("FriendsMulti")
local vipLabel = frame:FindFirstChild("VIPMulti")
local shownAtStart = {}
for _, label in ipairs(frame:GetChildren()) do
	shownAtStart[label] = label:IsA("GuiObject") and label.Visible
end

local RebirthDefinitions = nil
do
	local modules = ReplicatedStorage:FindFirstChild("Modules")
	RebirthDefinitions = optionalModule(modules and modules:FindFirstChild("RebirthDefinitions"))
end

local function formatMultiplier(p: any): string
	local n = tonumber(p) or 1
	if n == math.floor(n) then
		return tostring(math.floor(n))
	end
	local text = string.format("%.2f", n)
	text = string.gsub(text, "0+$", "")
	text = string.gsub(text, "%.$", "")
	return text
end

local function numberIn(parent: Instance?, name: string): number?
	local v = parent and parent:FindFirstChild(name)
	local value = v and (v:IsA("IntValue") or v:IsA("NumberValue")) and (v :: any).Value
	return if type(value) == "number" and value == value then value else nil
end

-- text = nil hides the label (its input is missing)
local function setLabel(label: Instance?, text: string?)
	if label and label:IsA("TextLabel") then
		if text then
			label.Text = text
			label.Visible = shownAtStart[label] ~= false
		else
			label.Visible = false
		end
	end
end

local function updateMultipliers()
	local rebirth = nil
	local rebirths = numberIn(LocalPlayer, "Rebirths")
	if rebirths and RebirthDefinitions and type(RebirthDefinitions.GetMultiplier) == "function" then
		local ok, m = pcall(RebirthDefinitions.GetMultiplier, RebirthDefinitions, rebirths)
		if ok and type(m) == "number" then
			rebirth = "x" .. formatMultiplier(m)
		end
	end
	for _, label in ipairs(rebirthLabels) do
		setLabel(label, rebirth)
	end

	local robuxLevel = numberIn(LocalPlayer:FindFirstChild("Upgrades"), "RobuxMultiplier")
	local robux = if robuxLevel then "x" .. formatMultiplier(2 ^ math.clamp(math.floor(robuxLevel), 0, 15)) else nil
	for _, label in ipairs(robuxLabels) do
		setLabel(label, robux)
	end

	local friends = numberIn(LocalPlayer, "FriendsMultiplier")
	setLabel(friendsLabel, if friends then "x" .. formatMultiplier(friends) else nil)

	local vipValue = LocalPlayer:FindFirstChild("VIP")
	local vip = if vipValue and vipValue:IsA("BoolValue") then (vipValue :: any).Value else nil
	setLabel(vipLabel, if type(vip) == "boolean" then "x" .. formatMultiplier(if vip then 1.25 else 1) else nil)
end

-- inputs may appear later; each one's changes redraw the labels
local watched = {}
local watchInputs: () -> ()
local function watch(v: Instance?, onChildren: boolean?)
	if v and not watched[v] then
		watched[v] = true
		v.Changed:Connect(updateMultipliers)
		if onChildren then
			v.ChildAdded:Connect(watchInputs)
			v.ChildRemoved:Connect(updateMultipliers)
		end
	end
end
watchInputs = function()
	for _, name in ipairs({ "Rebirths", "FriendsMultiplier", "VIP" }) do
		watch(LocalPlayer:FindFirstChild(name))
	end
	local upgrades = LocalPlayer:FindFirstChild("Upgrades")
	watch(upgrades, true)
	watch(upgrades and upgrades:FindFirstChild("RobuxMultiplier"))
	updateMultipliers()
end

------------------------------------------------------------ start

LocalPlayer.ChildAdded:Connect(function(child)
	if child.Name == "leaderstats" then
		bindStats()
	else
		watchInputs()
	end
end)
LocalPlayer.ChildRemoved:Connect(function(child)
	if child.Name == "leaderstats" then
		bindStats()
	else
		updateMultipliers()
	end
end)
bindStats()
watchInputs()
]] } } },
	{ key = "ButtonsMoneyHud", where = "StarterGui/ScreenGui/Buttons/Frames/MoneyFrame/MoneyController", class = "LocalScript", variants = { { label = "live", old = [[
-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Decompiled with Potassium's decompiler.

local Players = game:GetService("Players");
local ReplicatedStorage = game:GetService("ReplicatedStorage");
local LocalPlayer = Players.LocalPlayer;
local FormatModule = require(ReplicatedStorage:WaitForChild("FormatModule"));
local RebirthDefinitions = require(ReplicatedStorage:WaitForChild("Modules"):WaitForChild("RebirthDefinitions"));
local Money = script.Parent:WaitForChild("Money");
local FriendsMulti = script.Parent:WaitForChild("FriendsMulti");
local VIPMulti = script.Parent:WaitForChild("VIPMulti");
local u1 = {};
local u2 = {};

for _, child in ipairs(script.Parent:GetChildren()) do
    if child:IsA("TextLabel") and child.Name == "RebirthMulti" then
        table.insert(u2, child);
    elseif child:IsA("TextLabel") and child.Name == "RobuxMulti" then
        table.insert(u1, child);
    end;
end;

local function formatMoney(p3) -- Line: 20
    -- upvalues: FormatModule (copy)
    return "$" .. FormatModule:AbbreviateNumbers(p3);
end;

local Money2 = LocalPlayer:WaitForChild("Money");
local Rebirths = LocalPlayer:WaitForChild("Rebirths");
local FriendsMultiplier = LocalPlayer:WaitForChild("FriendsMultiplier");
local VIP = LocalPlayer:WaitForChild("VIP");
local RobuxMultiplier = LocalPlayer:WaitForChild("Upgrades"):WaitForChild("RobuxMultiplier");

if not Money2:IsA("NumberValue") then
    warn("[MoneyController] Player.Money must be a NumberValue");

    return;
end;

local function formatMultiplier(p4) -- Line: 35
    local v5 = tonumber(p4) or 1;

    if v5 == math.floor(v5) then
        local v6 = math.floor(v5);

        return tostring(v6);
    end;

    local v7 = string.format("%.2f", v5);
    local v8 = string.gsub(v7, "0+$", "");

    return string.gsub(v8, "%.$", "");
end;

local function updateMultipliers() -- Line: 50
    -- upvalues: RebirthDefinitions (copy), Rebirths (copy), RobuxMultiplier (copy), VIP (copy), u2 (copy), formatMultiplier (copy), FriendsMulti (copy), FriendsMultiplier (copy), VIPMulti (copy), u1 (copy)
    local v9 = RebirthDefinitions:GetMultiplier(Rebirths.Value);
    local v10 = math.floor(RobuxMultiplier.Value);
    local v11 = 2 ^ math.clamp(v10, 0, 15);
    local v12 = VIP.Value and 1.25 or 1;

    for _, v in ipairs(u2) do
        v.Text = "x" .. formatMultiplier(v9);
    end;

    FriendsMulti.Text = "x" .. formatMultiplier(FriendsMultiplier.Value);
    VIPMulti.Text = "x" .. formatMultiplier(v12);

    for _, v in ipairs(u1) do
        v.Text = "x" .. formatMultiplier(v11);
    end;
end;

Money.Text = "$" .. FormatModule:AbbreviateNumbers(Money2.Value);
updateMultipliers();
Money2:GetPropertyChangedSignal("Value"):Connect(function() -- Line: 46, Name: updateMoney
    -- upvalues: Money (copy), Money2 (copy), FormatModule (copy)
    Money.Text = "$" .. FormatModule:AbbreviateNumbers(Money2.Value);
end);
Rebirths:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
RobuxMultiplier:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
FriendsMultiplier:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
VIP:GetPropertyChangedSignal("Value"):Connect(updateMultipliers);
]], new = [[
-- MoneyController (LocalScript in a MoneyFrame; the same source runs in
-- StarterGui.Money.MoneyFrame and StarterGui.ScreenGui.Buttons.Frames.MoneyFrame).
--
-- The Money label shows leaderstats.Money: EconomyService's authoritative
-- balance, created once the player's Money has loaded. Until then (and if it
-- never loads) the label says "Loading..." instead of a number.
--
-- The multiplier labels (RebirthMulti, RobuxMulti, FriendsMulti, VIPMulti)
-- work as before WHEN their inputs exist (Rebirths + Modules.RebirthDefinitions,
-- Upgrades.RobuxMultiplier, FriendsMultiplier, VIP on the player). A label
-- whose inputs are missing is hidden: nothing is shown or assumed. These are
-- display only; EconomyService applies no multipliers to any payout.
--
-- Uses ReplicatedStorage.FormatModule for the number if it exists and works,
-- else its own abbreviation. Never waits on anything that may not exist.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local LocalPlayer = Players.LocalPlayer
local frame = script.Parent
local moneyLabel = frame:WaitForChild("Money")
local CURRENCY = "Money" -- EconomyService Config.CurrencyName
local LOADING = "Loading..."

------------------------------------------------------------ number format

local function optionalModule(inst: Instance?): any
	if inst and inst:IsA("ModuleScript") then
		local ok, mod = pcall(require, inst)
		if ok and type(mod) == "table" then
			return mod
		end
	end
	return nil
end

local FormatModule = optionalModule(ReplicatedStorage:FindFirstChild("FormatModule"))

local SUFFIXES = { "K", "M", "B", "T", "Qa", "Qi" }
-- 1234 -> "1.23K"; truncated, never rounded up (999999 -> "999.99K")
local function abbreviate(n: number): string
	n = math.floor(n)
	if n < 1000 then
		return tostring(n)
	end
	local i = 0
	while i < #SUFFIXES and n >= 1000 ^ (i + 1) do
		i += 1
	end
	local hundredths = n // (1000 ^ i / 100)
	local text = string.format("%d.%02d", hundredths // 100, hundredths % 100)
	text = string.gsub(text, "%.?0+$", "")
	return text .. SUFFIXES[i]
end

local function formatMoney(n: number): string
	if FormatModule and type(FormatModule.AbbreviateNumbers) == "function" then
		local ok, text = pcall(FormatModule.AbbreviateNumbers, FormatModule, n)
		if ok and (type(text) == "string" or type(text) == "number") then
			return "$" .. tostring(text)
		end
	end
	return "$" .. abbreviate(n)
end

------------------------------------------------------------ Money (leaderstats.Money)

local moneyValue: Instance? = nil
local moneyConn: RBXScriptConnection? = nil
local statsConns: { RBXScriptConnection } = {}

local function renderMoney()
	local v = moneyValue
	local n = if v and v.Parent then (v :: any).Value else nil
	if type(n) == "number" and n == n and n >= 0 and n ~= math.huge then
		moneyLabel.Text = formatMoney(n)
	else
		moneyLabel.Text = LOADING
	end
end

local function bindMoney()
	local stats = LocalPlayer:FindFirstChild("leaderstats")
	local v = stats and stats:FindFirstChild(CURRENCY)
	if v and not (v:IsA("IntValue") or v:IsA("NumberValue")) then
		v = nil
	end
	if v ~= moneyValue then
		if moneyConn then
			moneyConn:Disconnect()
			moneyConn = nil
		end
		moneyValue = v
		if v then
			moneyConn = v.Changed:Connect(renderMoney)
		end
	end
	renderMoney()
end

local function bindStats()
	for _, c in ipairs(statsConns) do
		c:Disconnect()
	end
	table.clear(statsConns)
	local stats = LocalPlayer:FindFirstChild("leaderstats")
	if stats then
		table.insert(statsConns, stats.ChildAdded:Connect(bindMoney))
		table.insert(statsConns, stats.ChildRemoved:Connect(bindMoney))
	end
	bindMoney()
end

------------------------------------------------------------ multipliers (only when their inputs exist)

local rebirthLabels, robuxLabels = {}, {}
for _, child in ipairs(frame:GetChildren()) do
	if child:IsA("TextLabel") and child.Name == "RebirthMulti" then
		table.insert(rebirthLabels, child)
	elseif child:IsA("TextLabel") and child.Name == "RobuxMulti" then
		table.insert(robuxLabels, child)
	end
end
local friendsLabel = frame:FindFirstChild("FriendsMulti")
local vipLabel = frame:FindFirstChild("VIPMulti")
local shownAtStart = {}
for _, label in ipairs(frame:GetChildren()) do
	shownAtStart[label] = label:IsA("GuiObject") and label.Visible
end

local RebirthDefinitions = nil
do
	local modules = ReplicatedStorage:FindFirstChild("Modules")
	RebirthDefinitions = optionalModule(modules and modules:FindFirstChild("RebirthDefinitions"))
end

local function formatMultiplier(p: any): string
	local n = tonumber(p) or 1
	if n == math.floor(n) then
		return tostring(math.floor(n))
	end
	local text = string.format("%.2f", n)
	text = string.gsub(text, "0+$", "")
	text = string.gsub(text, "%.$", "")
	return text
end

local function numberIn(parent: Instance?, name: string): number?
	local v = parent and parent:FindFirstChild(name)
	local value = v and (v:IsA("IntValue") or v:IsA("NumberValue")) and (v :: any).Value
	return if type(value) == "number" and value == value then value else nil
end

-- text = nil hides the label (its input is missing)
local function setLabel(label: Instance?, text: string?)
	if label and label:IsA("TextLabel") then
		if text then
			label.Text = text
			label.Visible = shownAtStart[label] ~= false
		else
			label.Visible = false
		end
	end
end

local function updateMultipliers()
	local rebirth = nil
	local rebirths = numberIn(LocalPlayer, "Rebirths")
	if rebirths and RebirthDefinitions and type(RebirthDefinitions.GetMultiplier) == "function" then
		local ok, m = pcall(RebirthDefinitions.GetMultiplier, RebirthDefinitions, rebirths)
		if ok and type(m) == "number" then
			rebirth = "x" .. formatMultiplier(m)
		end
	end
	for _, label in ipairs(rebirthLabels) do
		setLabel(label, rebirth)
	end

	local robuxLevel = numberIn(LocalPlayer:FindFirstChild("Upgrades"), "RobuxMultiplier")
	local robux = if robuxLevel then "x" .. formatMultiplier(2 ^ math.clamp(math.floor(robuxLevel), 0, 15)) else nil
	for _, label in ipairs(robuxLabels) do
		setLabel(label, robux)
	end

	local friends = numberIn(LocalPlayer, "FriendsMultiplier")
	setLabel(friendsLabel, if friends then "x" .. formatMultiplier(friends) else nil)

	local vipValue = LocalPlayer:FindFirstChild("VIP")
	local vip = if vipValue and vipValue:IsA("BoolValue") then (vipValue :: any).Value else nil
	setLabel(vipLabel, if type(vip) == "boolean" then "x" .. formatMultiplier(if vip then 1.25 else 1) else nil)
end

-- inputs may appear later; each one's changes redraw the labels
local watched = {}
local watchInputs: () -> ()
local function watch(v: Instance?, onChildren: boolean?)
	if v and not watched[v] then
		watched[v] = true
		v.Changed:Connect(updateMultipliers)
		if onChildren then
			v.ChildAdded:Connect(watchInputs)
			v.ChildRemoved:Connect(updateMultipliers)
		end
	end
end
watchInputs = function()
	for _, name in ipairs({ "Rebirths", "FriendsMultiplier", "VIP" }) do
		watch(LocalPlayer:FindFirstChild(name))
	end
	local upgrades = LocalPlayer:FindFirstChild("Upgrades")
	watch(upgrades, true)
	watch(upgrades and upgrades:FindFirstChild("RobuxMultiplier"))
	updateMultipliers()
end

------------------------------------------------------------ start

LocalPlayer.ChildAdded:Connect(function(child)
	if child.Name == "leaderstats" then
		bindStats()
	else
		watchInputs()
	end
end)
LocalPlayer.ChildRemoved:Connect(function(child)
	if child.Name == "leaderstats" then
		bindStats()
	else
		updateMultipliers()
	end
end)
bindStats()
watchInputs()
]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {

}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackMoneyHud.lua restores the previous sources)")
