--[[
	InstallUpgrades.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Paid aquarium upgrades: Tank Capacity and Release Rate are bought with Money
	at the aquarium's upgrade prompts, at the aquarium's own prices
	(capacity 50 / 150 / 400, release rate 40 / 120 / 350). The player who
	triggers the prompt pays; the level applies to the one shared tank for this
	server session (not saved, never per player). Not enough Money or money not
	loaded: nothing charged, nothing applied. Nothing is ever free.
	Changes one module (ServerScriptService.AquariumEconomy: it used to return
	nil = "upgrades unavailable").
	Requires: sale payouts (InstallSales.lua) and aquarium v1.2.

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyUpgradesBackup (Target ObjectValue + disabled Before/After
	copies) and writes the new sources. It adds and deletes nothing else.
	RollbackUpgrades.lua restores every Before source.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallUpgrades"
local BACKUP = "EconomyUpgradesBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomyRodOffersBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyUpgradesBackup", "EconomyVariantsBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes
local CHANGES = {
	{ key = "AquariumEconomy", where = "ServerScriptService/AquariumEconomy", class = "ModuleScript", tag = "AquariumCycleOwned", old = [[
-- AquariumEconomy (ModuleScript in ServerScriptService).
--
-- The currency binding for aquarium upgrades. This place currently has no
-- currency the aquarium can charge (no script references leaderstats, and
-- CustomerSystem's CustomerBought event has no consumer), so this returns nil
-- and the upgrade prompts say upgrades are unavailable. Upgrades are never
-- granted for free, and nothing here creates a currency.
--
-- To connect a real currency later, return a table like:
--
--   return {
--       -- Take `amount` from `player`. Must be atomic: return true only if
--       -- the whole amount was taken, false (and take nothing) otherwise.
--       tryCharge = function(player: Player, amount: number, reason: string): boolean
--           ...
--       end,
--   }
--
-- The price always comes from the aquarium's own upgrade tables.

return nil
]], new = [[
-- AquariumEconomy (ModuleScript in ServerScriptService) - Economy version.
--
-- The aquarium's currency binding. Upgrades are charged to the player who
-- triggers the upgrade prompt, through EconomyService (leaderstats.Money).
-- Returns nil (upgrades "unavailable", never free) if EconomyService is
-- missing or not running.
--
-- Shared tank upgrades are SESSION-SCOPED: the one physical tank's levels
-- live only in this server and reset when the server closes. They are not
-- saved to anyone's data, and capacity is never per player. Whoever buys a
-- level pays for it; everyone in the server shares the tank.
--
-- tryCharge is synchronous (no yields), so the aquarium's charge-then-apply
-- can't interleave with another purchase.

local ServerScriptService = game:GetService("ServerScriptService")

local mod = ServerScriptService:FindFirstChild("EconomyService")
if not (mod and mod:IsA("ModuleScript")) then
	return nil
end
local ok, Economy = pcall(require, mod)
if not ok or type(Economy) ~= "table" then
	warn("[AquariumEconomy] EconomyService failed to load: " .. tostring(Economy))
	return nil
end
local started, running = pcall(Economy.start)
if not (started and running) then
	return nil
end

return {
	tryCharge = function(player: Player, amount: number, reason: string): boolean
		local paid, why = Economy.tryDebit(player, amount, reason)
		if not paid and why == "notLoaded" then
			Economy.notify(player, "Money is still loading - try again in a moment", "warn")
		end
		return paid == true
	end,
}
]] },
}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {
	{ key = "GrinderProcessor (sales)", where = "script:GrinderProcessor", class = "Script", source = [[
-- GRINDER -> PIPE -> BLENDER -> CONVEYOR -> STACK
-- 1) Fish land in the grinder: it blends 4s (fast rollers + shake), then meat pops out of the pipe into the blender (Pit).
-- 2) In the blender the blade spins and knocks the meat around (it can't leave the bowl).
-- 3) After 5s in the blender each piece goes onto the conveyor, ONE at a time, rides slowly to the end,
--    and stacks up neatly in the box at the end.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- With ServerScriptService.EconomyService running, every meat piece gets a ledger
-- record (PieceId; owner and value fixed here) that is paid once when it sells.
-- Nothing is destroyed unpaid any more: when the pit or the stack is full, pieces
-- wait (in the blender queue, or as held ledger data) and come back out of the
-- pipe when there is room. Without EconomyService this runs exactly as before.
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local grinder = workspace:WaitForChild("FishGrinder")
local housing = grinder:WaitForChild("Housing")
local caught = workspace:WaitForChild("NetLift"):WaitForChild("FishCaught")
local meatTemplate = ServerStorage:WaitForChild("MeatTemplate")
local pitMeat = workspace:WaitForChild("PitMeat")
local pit = workspace:WaitForChild("Pit")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[GrinderProcessor] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[GrinderProcessor] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- tuning
local GRIND_TIME = 4        -- seconds in the grinder
local GRIND_RPM = 170
local BLEND_TIME = 5        -- seconds each piece spends in the blender
local BLADE_SPEED = 2.5       -- radians / second
local BELT_SPEED = 2.5      -- studs / second (slow)
local BELT_GAP = 4          -- studs between pieces on the belt
local MAX_STACK = 96

local pipeExit = grinder:GetAttribute("PipeExit")
local center = pit:GetAttribute("BlenderCenter")
local radius = pit:GetAttribute("BlenderRadius")
local beltStart = pit:GetAttribute("BeltStart")
local beltEnd = pit:GetAttribute("BeltEnd")
local stackOrigin = pit:GetAttribute("StackOrigin")
local normalRPM = grinder:GetAttribute("RPM") or 18
local housingRest = housing:GetPivot()
local rng = Random.new()

local function meatFor(tier)
	tier = tier or 1
	if tier <= 5 then return 1 elseif tier <= 13 then return 2 elseif tier <= 18 then return 3 else return 5 end
end

-- small helper: animate a part along an arc
local function hop(part, from, to, height, dur, spin)
	local t = 0
	local r0 = part.CFrame.Rotation
	while t < dur do
		t += RunService.Heartbeat:Wait()
		local u = math.min(t / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * r0 * CFrame.Angles(0, u * (spin or 0), 0)
	end
end

------------------------------------------------------------------ BLADE
local blade = workspace:WaitForChild(pit:GetAttribute("BladeName") or "BladeCommon")
local bladeRest = blade:GetPivot()
local bladeAngle = 0
RunService.Heartbeat:Connect(function(dt)
	bladeAngle = (bladeAngle + dt * BLADE_SPEED) % (math.pi * 2)
	blade:PivotTo(bladeRest * CFrame.Angles(0, bladeAngle, 0))
end)

------------------------------------------------------------------ BLENDER SIM
local inBlender = {} -- meat -> state
local beltQueue = {}

local function addToBlender(meat)
	local rel = meat.Position - center
	inBlender[meat] = {
		r = math.clamp(Vector3.new(rel.X, 0, rel.Z).Magnitude, 0.8, radius),
		a = math.atan2(rel.Z, rel.X),
		vr = 0, y = 0, vy = 0,
		spinV = rng:NextNumber(-8, 8),
		rot = meat.CFrame.Rotation,
		nextHit = rng:NextNumber(0.2, 0.6),
		enter = os.clock(),
	}
end

RunService.Heartbeat:Connect(function(dt)
	local now = os.clock()
	for meat, s in pairs(inBlender) do
		if not meat.Parent then inBlender[meat] = nil continue end
		-- swirl with the blade
		s.a += dt * BLADE_SPEED * 0.55
		-- blade whacks: random hop + push in/out
		s.nextHit -= dt
		if s.nextHit <= 0 then
			s.nextHit = rng:NextNumber(0.25, 0.7)
			s.vy = rng:NextNumber(5, 9)
			s.vr = rng:NextNumber(-6, 6)
			s.spinV = rng:NextNumber(-14, 14)
		end
		s.vy -= 40 * dt
		s.y = math.max(0, s.y + s.vy * dt)
		if s.y == 0 then s.vy = 0 end
		s.r += s.vr * dt
		s.vr *= (1 - math.min(1, dt * 3))
		-- keep it inside the bowl
		if s.r > radius then s.r = radius s.vr = -math.abs(s.vr) * 0.6 end
		if s.r < 0.7 then s.r = 0.7 s.vr = math.abs(s.vr) * 0.6 end
		s.rot = s.rot * CFrame.Angles(s.spinV * dt * 0.3, s.spinV * dt, 0)
		local flat = CFrame.Angles(0, select(2, s.rot:ToEulerAnglesYXZ()), 0)
		local tilt = s.y > 0.05 and s.rot or flat
		meat.CFrame = CFrame.new(center + Vector3.new(math.cos(s.a) * s.r, 0.14 + s.y, math.sin(s.a) * s.r)) * tilt
		-- done blending -> queue for the belt
		if now - s.enter >= BLEND_TIME and s.y == 0 and not s.queued then
			s.queued = true
			table.insert(beltQueue, meat)
		end
	end
end)

------------------------------------------------------------------ STACK
local stacked = {}
local function stackSlot(n)
	local layer = n // 8
	local i = n % 8
	return stackOrigin + Vector3.new((i % 4) * 1.75, layer * 0.3, (i // 4) * 2.9)
end

-- Economy: backpressure. A piece goes onto the belt only if the stack will
-- have room for it, and new pieces are shot into the pit only while the pit
-- has room; otherwise they wait (blender queue / held ledger data).
local onBelt = 0
local function stackHasRoom()
	if not Economy then return true end
	local stackFolder = workspace:FindFirstChild("MeatStack") or pitMeat
	return #stackFolder:GetChildren() + onBelt < MAX_STACK
end
local function pitHasRoom()
	local n = 0
	for _, m in ipairs(pitMeat:GetChildren()) do
		if m:GetAttribute("StackIndex") == nil then n += 1 end
	end
	return n < Economy.pipeline().MaxPitObjects
end

------------------------------------------------------------------ BELT (one at a time)
local beltLen = (beltEnd - beltStart).Magnitude
local beltDir = (beltEnd - beltStart).Unit
local lastOnBelt = nil -- {part, startT}

local function runBelt(meat)
	local s = inBlender[meat]
	inBlender[meat] = nil
	if not meat.Parent then return end
	-- flick out of the blender onto the start of the belt
	local flat = CFrame.lookAt(Vector3.zero, beltDir).Rotation
	meat.CFrame = CFrame.new(meat.Position) * flat
	hop(meat, meat.Position, beltStart, 2.5, 0.5, 0)
	local info = { part = meat, t0 = os.clock() }
	lastOnBelt = info
	-- ride the belt slowly
	local d = 0
	while d < beltLen do
		d = math.min(beltLen, d + BELT_SPEED * RunService.Heartbeat:Wait())
		meat.CFrame = CFrame.new(beltStart + beltDir * d) * flat
	end
	-- drop onto the stack (players pick from the top, so the next slot = current count)
	local stackFolder = workspace:FindFirstChild("MeatStack") or pitMeat
	local count = #stackFolder:GetChildren()
	if count >= MAX_STACK then
		-- Economy: never lose unpaid meat - keep the piece as held ledger data
		if Economy then Economy.hold(meat:GetAttribute("PieceId")) end
		meat:Destroy() -- stack is full
		return
	end
	local slot = stackSlot(count)
	meat:SetAttribute("StackIndex", count)
	meat.Parent = stackFolder
	hop(meat, meat.Position, slot, 2, 0.45, 0)
	if meat.Parent == stackFolder then
		meat.CFrame = CFrame.new(slot)
	end
end

task.spawn(function()
	while true do
		task.wait(0.1)
		local first = beltQueue[1]
		if first then
			-- only release when the belt is clear enough
			local clear = true
			if lastOnBelt and lastOnBelt.part.Parent then
				local traveled = (os.clock() - lastOnBelt.t0) * BELT_SPEED
				clear = traveled >= BELT_GAP
			end
			if clear and stackHasRoom() then -- Economy: wait while the stack is full
				table.remove(beltQueue, 1)
				lastOnBelt = { part = first, t0 = os.clock() + 0.5 } -- reserve while it hops on
				onBelt += 1
				task.spawn(function()
					local ok, err = pcall(runBelt, first)
					onBelt -= 1
					if not ok then warn("[GrinderProcessor] belt: " .. tostring(err)) end
				end)
			end
		end
	end
end)

------------------------------------------------------------------ GRINDER -> PIPE -> BLENDER
local function shootMeat(info, pieceId)
	local meat = meatTemplate:Clone()
	meat.Name = "Meat"
	meat:SetAttribute("FromFish", info.fishName)
	meat:SetAttribute("Tier", info.tier)
	if info.player then meat:SetAttribute("OwnerId", info.player.UserId) end
	if Economy and pieceId then Economy.stamp(meat, pieceId) end -- Economy: PieceId, owner, value, variant
	meat.CFrame = CFrame.new(pipeExit) * CFrame.Angles(rng:NextNumber(0, 6), rng:NextNumber(0, 6), 0)
	meat.Parent = pitMeat
	local ang = rng:NextNumber(0, math.pi * 2)
	local land = center + Vector3.new(math.cos(ang), 0, math.sin(ang)) * rng:NextNumber(1.5, radius - 0.3) + Vector3.new(0, 0.14, 0)
	hop(meat, pipeExit, land, 3, 0.55, 8)
	addToBlender(meat)
end

local pending = {}
local grinding = false
local function grind()
	grinding = true
	grinder:SetAttribute("RPM", GRIND_RPM)
	grinder:SetAttribute("Blending", true)
	local t = 0
	local conn = RunService.Heartbeat:Connect(function(dt)
		t += dt
		local amp = 0.12
		housing:PivotTo(housingRest * CFrame.new(
			math.noise(t * 25, 1) * amp, math.abs(math.noise(t * 30, 2)) * amp, math.noise(t * 25, 3) * amp
		) * CFrame.Angles(0, math.noise(t * 20, 4) * 0.02, math.noise(t * 20, 5) * 0.015))
	end)
	task.wait(GRIND_TIME)
	conn:Disconnect()
	housing:PivotTo(housingRest)
	grinder:SetAttribute("RPM", normalRPM)
	grinder:SetAttribute("Blending", false)
	local batch = pending
	pending = {}
	grinding = false
	for _, info in ipairs(batch) do
		if Economy then
			-- Economy: one ledger piece per meat piece (same count as meatFor);
			-- pieces the pit has no room for are held as data, not dropped
			for _, pieceId in ipairs(Economy.issueFish(info.player, info.fishName, info.tier, info.meta)) do
				if pitHasRoom() then
					task.spawn(shootMeat, info, pieceId)
					task.wait(0.22)
				else
					Economy.hold(pieceId)
				end
			end
		else
			for i = 1, meatFor(info.tier) do
				task.spawn(shootMeat, info)
				task.wait(0.22)
			end
		end
	end
	if #pending > 0 and not grinding then task.spawn(grind) end
end

caught.Event:Connect(function(player, fishName, tier, meta) -- Economy: meta = { OwnerId, Variant, Source }
	table.insert(pending, { player = player, fishName = fishName, tier = tier, meta = meta })
	if not grinding then task.spawn(grind) end
end)

-- Economy: held pieces (pit/stack was full, or a carrier left) come back out
-- of the pipe, oldest first, whenever the pit has room again.
if Economy then
	task.spawn(function()
		while true do
			task.wait(0.5)
			while pitHasRoom() do
				local piece = Economy.takeHeld()
				if not piece then break end
				task.spawn(shootMeat, { fishName = piece.fishName, tier = piece.tier }, piece.id)
				task.wait(0.22)
			end
		end
	end)
end
]] },
	{ key = "TruckSystem (sales)", where = "script:TruckSystem", class = "Script", source = [[
-- Delivery trucks: a line of trucks comes out of Cave1, waits at the U-turn next to the dock,
-- players carry meat from the stack at the end of the conveyor and drop it in the front truck's bucket.
-- When a truck has all the meat it needs it drives around the U-turn into Cave2 and the line moves up.
-- (Trucks are drawn/moved on each client by TruckClient using the "S" attribute; server keeps the logic.)
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- Players carry the ledger ids of the meat they pick up. Dropping a piece in a
-- truck is that piece's one sale (paid to the piece's owner, not the carrier).
-- If a carrier leaves or respawns, their pieces are held and come back out of
-- the grinder pipe instead of vanishing unpaid. Truck UI is unchanged.
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")
local RS = game:GetService("ReplicatedStorage")
local SS = game:GetService("ServerStorage")

local Path = require(RS:WaitForChild("TruckPath"))
local truckTypes = SS:WaitForChild("TruckTypes") -- each has Weight / NeedMin / NeedMax attributes
local meatTemplate = SS:WaitForChild("MeatTemplate")
local trucksFolder = workspace:WaitForChild("Trucks")
local meatStack = workspace:WaitForChild("MeatStack")
local events = SS:WaitForChild("TruckEvents")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[TruckSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[TruckSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- tuning
local MAX_TRUCKS = 5
local TRUCK_DELAY = { 6, 14 } -- seconds between new trucks pulling in
local nextTruckAt = 0
local NEED_MIN, NEED_MAX = 2, 5
local DRIVE_SPEED = 12
local MAX_CARRY = 10
local TRANSFER_EVERY = 0.15
local STACK_CENTER = Vector3.new(-78.4, 10.05, 160)
local STACK_HALF = Vector3.new(6.3, 0, 5.5)   -- pickup area around the end box
local DELIVER_RANGE = 9

local function pickType()
	local list, total = truckTypes:GetChildren(), 0
	for _, t in ipairs(list) do total += t:GetAttribute("Weight") or 1 end
	local r = Random.new():NextNumber(0, total)
	for _, t in ipairs(list) do
		r -= t:GetAttribute("Weight") or 1
		if r <= 0 then return t end
	end
	return list[1]
end
local rng = Random.new()
local queue = {}      -- waiting / loading trucks, front first
local departing = {}

------------------------------------------------------------ GUI
local MEAT_IMAGE = "rbxassetid://128058252479007"
local DOTS = 16
local FILLED, EMPTY = Color3.fromRGB(90, 225, 80), Color3.fromRGB(205, 210, 220)

-- cartoon order bubble: white disc, progress dots around the edge, meat picture, green count badge
local function makeGui(truck)
	local floor = truck:FindFirstChild("TubInnerFloor") or truck.PrimaryPart
	local bb = Instance.new("BillboardGui")
	bb.Name = "NeedGui"
	bb.Size = UDim2.fromScale(4.2, 4.2)
	bb.StudsOffsetWorldSpace = Vector3.new(0, 6.2, 0)
	bb.LightInfluence = 0
	bb.MaxDistance = 150
	bb.Parent = floor

	local shadow = Instance.new("Frame")
	shadow.Size = UDim2.fromScale(0.9, 0.9)
	shadow.Position = UDim2.fromScale(0.08, 0.1)
	shadow.BackgroundColor3 = Color3.new(0, 0, 0)
	shadow.BackgroundTransparency = 0.7
	shadow.Parent = bb
	Instance.new("UICorner", shadow).CornerRadius = UDim.new(1, 0)

	local circle = Instance.new("Frame")
	circle.Name = "Circle"
	circle.Size = UDim2.fromScale(0.9, 0.9)
	circle.Position = UDim2.fromScale(0.05, 0.05)
	circle.BackgroundColor3 = Color3.new(1, 1, 1)
	circle.Parent = bb
	Instance.new("UICorner", circle).CornerRadius = UDim.new(1, 0)
	local grad = Instance.new("UIGradient", circle)
	grad.Rotation = 90
	grad.Color = ColorSequence.new(Color3.fromRGB(255, 255, 255), Color3.fromRGB(215, 232, 255))
	local stroke = Instance.new("UIStroke", circle)
	stroke.Color = Color3.fromRGB(20, 20, 25)
	stroke.Thickness = 4

	local dots = {}
	for i = 1, DOTS do
		local a = (i - 1) / DOTS * math.pi * 2 - math.pi / 2
		local d = Instance.new("Frame")
		d.AnchorPoint = Vector2.new(0.5, 0.5)
		d.Size = UDim2.fromScale(0.1, 0.1)
		d.Position = UDim2.fromScale(0.5 + math.cos(a) * 0.4, 0.5 + math.sin(a) * 0.4)
		d.BackgroundColor3 = EMPTY
		d.Parent = circle
		Instance.new("UICorner", d).CornerRadius = UDim.new(1, 0)
		local ds = Instance.new("UIStroke", d)
		ds.Color = Color3.fromRGB(20, 20, 25)
		ds.Thickness = 1.5
		dots[i] = d
	end

	local meat = Instance.new("ImageLabel")
	meat.Name = "Meat"
	meat.AnchorPoint = Vector2.new(0.5, 0.5)
	meat.Position = UDim2.fromScale(0.5, 0.48)
	meat.Size = UDim2.fromScale(0.58, 0.58)
	meat.BackgroundTransparency = 1
	meat.Image = MEAT_IMAGE
	meat.ScaleType = Enum.ScaleType.Fit
	meat.Parent = circle

	local badge = Instance.new("Frame")
	badge.Name = "Badge"
	badge.Size = UDim2.fromScale(0.44, 0.44)
	badge.Position = UDim2.fromScale(0.62, 0.62)
	badge.BackgroundColor3 = Color3.new(1, 1, 1)
	badge.Parent = bb
	Instance.new("UICorner", badge).CornerRadius = UDim.new(1, 0)
	local bg = Instance.new("UIGradient", badge)
	bg.Rotation = 90
	bg.Color = ColorSequence.new(Color3.fromRGB(150, 255, 90), Color3.fromRGB(40, 185, 50))
	local bs = Instance.new("UIStroke", badge)
	bs.Color = Color3.fromRGB(20, 20, 25)
	bs.Thickness = 3.5
	local num = Instance.new("TextLabel")
	num.Name = "Num"
	num.Size = UDim2.fromScale(0.8, 0.8)
	num.Position = UDim2.fromScale(0.1, 0.08)
	num.BackgroundTransparency = 1
	num.Font = Enum.Font.FredokaOne
	num.TextScaled = true
	num.TextColor3 = Color3.new(1, 1, 1)
	num.Parent = badge
	local ns = Instance.new("UIStroke", num)
	ns.Color = Color3.fromRGB(20, 20, 25)
	ns.Thickness = 2.5

	local function setProgress(frac)
		local n = math.floor(frac * DOTS + 0.5)
		for i, d in ipairs(dots) do d.BackgroundColor3 = i <= n and FILLED or EMPTY end
	end
	setProgress(0)
	return num, setProgress
end

------------------------------------------------------------ TRUCKS
local function spawnTruck()
	local tpl = pickType()
	local m = tpl:Clone()
	local need = rng:NextInteger(tpl:GetAttribute("NeedMin") or NEED_MIN, tpl:GetAttribute("NeedMax") or NEED_MAX)
	m:SetAttribute("Need", need)
	m:SetAttribute("Loaded", 0)
	m:SetAttribute("S", 0)
	m:PivotTo(Path.truckCF(0))
	local t = { model = m, s = 0, need = need, loaded = 0, lastSent = -1, bucketOffset = tpl:GetAttribute("BucketOffset") }
	t.num, t.setProgress = makeGui(m)
	t.num.Text = tostring(need)
	m.Parent = trucksFolder
	table.insert(queue, t)
end

local function depart(t)
	local gui = t.model:FindFirstChild("NeedGui", true)
	if gui then gui:Destroy() end
	for i, q in ipairs(queue) do if q == t then table.remove(queue, i) break end end
	table.insert(departing, t)
end

local function step(t, target, dt)
	local d = target - t.s
	if math.abs(d) < 0.01 then t.s = target return end
	local v = math.min(DRIVE_SPEED, math.abs(d) * 2.5 + 0.5)
	t.s += math.sign(d) * math.min(math.abs(d), v * dt)
end

local sendClock = 0
RunService.Heartbeat:Connect(function(dt)
	for i, t in ipairs(queue) do
		step(t, Path.slot(i), dt)
	end
	for i = #departing, 1, -1 do
		local t = departing[i]
		step(t, Path.TOTAL, dt)
		if t.s >= Path.TOTAL - 0.05 then
			t.model:Destroy()
			table.remove(departing, i)
		end
	end
	sendClock += dt
	if sendClock >= 0.066 then
		sendClock = 0
		for _, list in ipairs({ queue, departing }) do
			for _, t in ipairs(list) do
				if t.s ~= t.lastSent then
					t.lastSent = t.s
					t.model:SetAttribute("S", t.s)
				end
			end
		end
	end
	-- keep the line full
	local last = queue[#queue]
	if #queue + #departing < MAX_TRUCKS + 2 and #queue < MAX_TRUCKS and (not last or last.s >= Path.SPACING) and os.clock() >= nextTruckAt then
		spawnTruck()
		nextTruckAt = os.clock() + rng:NextNumber(TRUCK_DELAY[1], TRUCK_DELAY[2])
	end
end)

------------------------------------------------------------ CARRYING
local carry = {} -- player -> {count, parts, ids}

-- Economy: ledger ids of the meat a player carries (false = untracked piece).
-- A carrier who leaves or respawns gives them back as held pieces.
local function dropCarried(c)
	if Economy and c and c.ids then
		for _, id in ipairs(c.ids) do
			if id then Economy.hold(id) end
		end
		table.clear(c.ids)
	end
end

local function carryVisual(player)
	local c = carry[player]
	local char = player.Character
	local hrp = char and char:FindFirstChild("HumanoidRootPart")
	if not hrp then return end
	local folder = char:FindFirstChild("CarriedMeat")
	if not folder then folder = Instance.new("Folder") folder.Name = "CarriedMeat" folder.Parent = char end
	while #c.parts < c.count do
		local p = meatTemplate:Clone()
		p.Anchored = false
		p.Massless = true
		p.CanCollide = false
		local i = #c.parts
		p.CFrame = hrp.CFrame * CFrame.new(0, 0.1 + i * 0.3, -1.7) * CFrame.Angles(0, math.rad(90), 0)
		local w = Instance.new("WeldConstraint")
		w.Part0 = hrp w.Part1 = p w.Parent = p
		p.Parent = folder
		table.insert(c.parts, p)
	end
	while #c.parts > c.count do
		table.remove(c.parts):Destroy()
	end
	player:SetAttribute("CarryMeat", c.count)
end

local function flyPart(from, to, height, dur)
	local p = meatTemplate:Clone()
	p.CFrame = CFrame.new(from)
	p.Parent = workspace
	task.spawn(function()
		local t = 0
		while t < dur do
			t += RunService.Heartbeat:Wait()
			local u = math.min(t / dur, 1)
			p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
		end
		p:Destroy()
	end)
	return dur
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function addMeatToTruck(t, n) -- n = 0-based slot
	local layer = n // 4
	local i = n % 4
	local off = t.bucketOffset + Vector3.new((i % 2 - 0.5) * 1.6, 0.16 + layer * 0.3, (i // 2 - 0.5) * 1.9)
	local p = meatTemplate:Clone()
	p.Name = "LoadedMeat"
	-- server-side the truck stays at its spawn pose; the client moves everything together
	p.CFrame = Path.truckCF(0) * CFrame.new(off) * CFrame.Angles(0, rng:NextNumber(-0.3, 0.3), 0)
	p.Parent = t.model
end

local timers = {}
task.spawn(function()
	while true do
		task.wait(TRANSFER_EVERY)
		local front = queue[1]
		local loading = front and math.abs(front.s - Path.LOAD_S) < 0.3 and front.loaded < front.need
		local bucketPos = front and (Path.truckCF(Path.LOAD_S) * CFrame.new(front.bucketOffset)).Position
		for _, player in ipairs(Players:GetPlayers()) do
			local char = player.Character
			local hrp = char and char:FindFirstChild("HumanoidRootPart")
			local hum = char and char:FindFirstChildOfClass("Humanoid")
			if not hrp or not hum or hum.Health <= 0 then continue end
			carry[player] = carry[player] or { count = 0, parts = {}, ids = {} }
			local c = carry[player]
			local pos = hrp.Position
			local rel = pos - STACK_CENTER
			-- pick up from the stack
			if math.abs(rel.X) <= STACK_HALF.X and math.abs(rel.Z) <= STACK_HALF.Z and math.abs(rel.Y) < 8 and c.count < MAX_CARRY then
				local meat = topOfStack()
				if meat then
					local from = meat.Position
					local pieceId = meat:GetAttribute("PieceId") -- Economy
					meat:Destroy()
					if Economy then
						table.insert(c.ids, if pieceId and Economy.carry(pieceId) then pieceId else false)
					end
					flyPart(from, pos + Vector3.new(0, 0.5 + c.count * 0.3, 0), 2, 0.2)
					c.count += 1
					carryVisual(player)
				end
			-- drop into the front truck
			elseif loading and c.count > 0 then
				local d = Vector3.new(pos.X - bucketPos.X, 0, pos.Z - bucketPos.Z).Magnitude
				if d <= DELIVER_RANGE then
					c.count -= 1
					if Economy then Economy.settle(table.remove(c.ids), "Truck") end -- Economy: the one sale
					carryVisual(player)
					local truck = front
					local slotLoaded = truck.loaded
					truck.loaded += 1
					truck.model:SetAttribute("Loaded", truck.loaded)
					truck.num.Text = tostring(truck.need - truck.loaded)
					if truck.setProgress then truck.setProgress(truck.loaded / truck.need) end
					events.MeatDelivered:Fire(player, truck.model)
					local dur = flyPart(pos + Vector3.new(0, 1.5, 0), bucketPos + Vector3.new(0, 0.5, 0), 4, 0.35)
					task.delay(dur, function()
						if truck.model.Parent then addMeatToTruck(truck, slotLoaded) end
					end)
					if truck.loaded >= truck.need then
						events.TruckFilled:Fire(player, truck.need)
						loading = false
						task.delay(0.8, function() depart(truck) end)
					end
				end
			end
		end
	end
end)

Players.PlayerRemoving:Connect(function(p) dropCarried(carry[p]) carry[p] = nil end)
-- Economy: loading EconomyService (top of this script) can yield, so players
-- may already be in the server here; bind every player exactly once.
local bound = {}
local function bindPlayer(p)
	if bound[p] then return end
	bound[p] = true
	p.CharacterAdded:Connect(function()
		dropCarried(carry[p]) -- Economy: a respawned carrier's pieces are held, not lost
		carry[p] = { count = 0, parts = {}, ids = {} }
		p:SetAttribute("CarryMeat", 0)
	end)
end
Players.PlayerAdded:Connect(bindPlayer)
for _, p in ipairs(Players:GetPlayers()) do bindPlayer(p) end
Players.PlayerRemoving:Connect(function(p) bound[p] = nil end)
]] },
	{ key = "EconomyService", where = "ServerScriptService/EconomyService", class = "ModuleScript", tag = "EconomyOwned", source = [[
-- EconomyService (ModuleScript in ServerScriptService; its children are the
-- pure core modules Config, Pricing, Ledger, MoneyStore, Offers, PieceTags).
--
-- The ONE money service. Binds the pure core to Roblox:
--   * loads/saves each player's Money (DataStore, session-locked) and shows
--     it as leaderstats.Money once - and only once - it has loaded
--   * the meat ledger: GrinderProcessor issues pieces, BotSystem copies
--     their identity, CustomerSystem / TruckSystem settle them (one payment
--     per piece, to its owner), full pipelines hold pieces as data
--   * charging (aquarium upgrades, rod shop, rod-fish offers)
--
-- Every patched live script loads this with FindFirstChild + pcall(require)
-- and calls start(); if it is missing or fails, those scripts behave
-- exactly as before. ServerScriptService.EconomyBoot also calls start() so
-- money loads even before anything is sold.
--
-- It never creates Cash or a Money attribute, never grants anything except
-- the one-time starting grant for a player with no saved record, and never
-- saves a player whose money failed to load.

local DataStoreService = game:GetService("DataStoreService")
local HttpService = game:GetService("HttpService")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local Config = require(script.Config)
local Pricing = require(script.Pricing)
local Ledger = require(script.Ledger)
local MoneyStore = require(script.MoneyStore)
local PieceTags = require(script.PieceTags)
local Sales = require(script.Sales)
local Offers = require(script.Offers)

local M = {}
M.Config = Config
M.Pricing = Pricing

local started = false
local starting = false -- start() yields (Studio DataStore probe); other callers wait
local startOk = false

local money: MoneyStore.MoneyStore
local ledger: Ledger.Ledger
local root: Folder -- ReplicatedStorage.Economy (installed)
local notice: RemoteEvent
local storeKind = "DataStore"
local offers: Offers.Offers
local offersFolder: Folder -- ReplicatedStorage.Economy.Offers (kept empty; offers live on buy stands)
local standsFolder: Folder -- Workspace.EconomyBuyStands: one invisible buy-stand part per open offer
local offerAction: RemoteFunction
local offerRecs = {} -- offer id -> { stand, reservationOk, deliver }
local lastOfferAction: { [Player]: number } = {}
local lastLockWarn = {}

------------------------------------------------------------ helpers

local function log(msg: string)
	print("[Economy] " .. msg)
end

local function userIdOf(who: any): number?
	if typeof(who) == "Instance" and who:IsA("Player") then
		return who.UserId
	end
	return Ledger.validOwner(who)
end

function M.notify(player: Player?, text: string, kind: string?)
	if player and notice and player.Parent == Players then
		notice:FireClient(player, text, kind or "info")
	end
end

------------------------------------------------------------ stores

local function dataStoreStore(): MoneyStore.Store
	local ds = DataStoreService:GetDataStore(Config.DataStoreName)
	return {
		update = function(key: string, transform: (any) -> any): any
			return ds:UpdateAsync(key, transform)
		end,
	}
end

-- Studio-only, non-persistent. Never used in a live server.
local function memoryStore(): MoneyStore.Store
	local data = {}
	return {
		update = function(key: string, transform: (any) -> any): any
			local result = transform(data[key])
			if result ~= nil then
				data[key] = result
			end
			return data[key]
		end,
	}
end

local function pickStore(): MoneyStore.Store
	local ok, result = pcall(dataStoreStore)
	local err: any = if ok then nil else result
	if ok and RunService:IsStudio() then
		-- Studio: is DataStore access actually on for this place?
		local probed, probeErr = pcall(function()
			DataStoreService:GetDataStore(Config.DataStoreName):GetAsync("__probe")
		end)
		if not probed then
			ok, err = false, probeErr
		end
	end
	if ok then
		return result
	end
	if RunService:IsStudio() and Config.StudioMemoryStoreFallback then
		storeKind = "Memory"
		warn(
			"[Economy] DataStore unavailable in Studio ("
				.. tostring(err)
				.. "); using a TEMPORARY in-memory store - Money will not persist"
		)
		return memoryStore()
	end
	error("DataStore unavailable: " .. tostring(err))
end

------------------------------------------------------------ leaderstats

local moneyValues: { [Player]: IntValue } = {}

local function sync(player: Player)
	local v = moneyValues[player]
	local bal = money:balance(player.UserId)
	if v and bal then
		v.Value = bal
	end
end

local function showMoney(player: Player)
	if moneyValues[player] or not player.Parent then
		return
	end
	local stats = player:FindFirstChild("leaderstats")
	if not stats then
		stats = Instance.new("Folder")
		stats.Name = "leaderstats"
		stats.Parent = player
	end
	local v = Instance.new("IntValue")
	v.Name = Config.CurrencyName
	v.Value = money:balance(player.UserId) or 0
	-- Display only: the balance lives in this service. Revert outside writes.
	v.Changed:Connect(function()
		local bal = money:balance(player.UserId)
		if bal and v.Value ~= bal then
			warn("[Economy] leaderstats.Money was changed outside EconomyService; reverted")
			v.Value = bal
		end
	end)
	moneyValues[player] = v
	v.Parent = stats
end

------------------------------------------------------------ load / save

local function loadPlayer(player: Player)
	local userId = player.UserId
	money:begin(userId)
	local attempt = 0
	while true do
		attempt += 1
		local result, detail = money:attemptLoad(userId)
		if result == "ready" then
			if not player.Parent then
				money:save(userId, true)
				money:forget(userId)
				return
			end
			showMoney(player)
			if detail == "new" then
				M.notify(player, string.format("Welcome! %d Money to start", Config.StartingGrant), "success")
			end
			log(string.format("%s money loaded (%s store)", player.Name, storeKind))
			return
		elseif result == "corrupt" then
			warn("[Economy] " .. player.Name .. "'s saved money is not valid; left untouched, money unavailable")
			M.notify(player, "Your money couldn't be loaded. Buying is off this session.", "warn")
			return
		elseif result == "notLoading" then
			return
		end
		-- "locked" or "error": retry, then keep retrying slowly in the background
		if attempt >= Config.LoadAttempts then
			money:markFailed(userId, result)
			warn(string.format("[Economy] %s money not loaded (%s): %s", player.Name, result, tostring(detail)))
			M.notify(player, "Money is still loading. Buying is paused; retrying...", "warn")
			while player.Parent do
				task.wait(Config.LoadRetryEverySeconds)
				if not player.Parent or not money:reopen(userId) then
					return
				end
				local r2, d2 = money:attemptLoad(userId)
				if r2 == "ready" then
					if not player.Parent then
						money:save(userId, true)
						money:forget(userId)
						return
					end
					showMoney(player)
					if d2 == "new" then
						M.notify(player, string.format("Welcome! %d Money to start", Config.StartingGrant), "success")
					end
					M.notify(player, "Money loaded", "success")
					return
				elseif r2 == "corrupt" or r2 == "notLoading" then
					return
				end
				money:markFailed(userId, r2)
			end
			return
		end
		task.wait(Config.LoadRetryDelays[attempt] or 4)
	end
end

local function saveWithRetry(userId: number, release: boolean): boolean
	for i = 1, 3 do
		while money:isSaving(userId) do
			task.wait(0.1)
		end
		local ok, why = money:save(userId, release)
		if ok then
			return true
		end
		if why == "notLoaded" or why == "lockLost" then
			if why == "lockLost" and not lastLockWarn[userId] then
				lastLockWarn[userId] = true
				warn("[Economy] session lock lost for " .. userId .. "; not saving over the other server")
			end
			return false
		end
		warn(string.format("[Economy] save %d failed (try %d): %s", userId, i, tostring(why)))
		task.wait(i)
	end
	return false
end

local function unloadPlayer(player: Player)
	local userId = player.UserId
	moneyValues[player] = nil
	local state = money:state(userId)
	if state == "Ready" then
		if not saveWithRetry(userId, true) then
			warn("[Economy] final save for " .. player.Name .. " did not complete")
		end
	end
	money:forget(userId)
	lastLockWarn[userId] = nil
end

------------------------------------------------------------ start

function M.start(): boolean
	if started then
		while starting do
			task.wait()
		end
		return startOk
	end
	started = true
	starting = true
	local ok, result = pcall(M._start)
	starting = false
	if not ok then
		warn("[Economy] failed to start: " .. tostring(result))
		startOk = false
		return false
	end
	return startOk
end

function M._start(): boolean
	local folder = ReplicatedStorage:FindFirstChild("Economy")
	if not (folder and folder:IsA("Folder")) then
		warn("[Economy] ReplicatedStorage.Economy not installed; economy off")
		return false
	end
	root = folder
	local okConfig, why = Config.check()
	if not okConfig then
		warn("[Economy] config check failed: " .. tostring(why) .. "; economy off")
		return false
	end
	local n = root:FindFirstChild("Notice")
	if not (n and n:IsA("RemoteEvent")) then
		n = Instance.new("RemoteEvent")
		n.Name = "Notice"
		n.Parent = root
	end
	notice = n :: RemoteEvent
	local of = root:FindFirstChild("Offers")
	if not (of and of:IsA("Folder")) then
		of = Instance.new("Folder")
		of.Name = "Offers"
		of.Parent = root
	end
	offersFolder = of :: Folder
	for _, old in ipairs(offersFolder:GetChildren()) do
		old:Destroy() -- nothing from a previous run survives
	end
	-- runtime folder (Play only, never saved): the caster's client puts its
	-- buy prompt on these parts
	if workspace:FindFirstChild("EconomyBuyStands") then
		-- ours is created here and never saved: an existing one is someone else's
		warn("[Economy] Workspace.EconomyBuyStands already exists and isn't ours; economy off")
		return false
	end
	local sf = Instance.new("Folder")
	sf.Name = "EconomyBuyStands"
	sf.Archivable = false
	sf.Parent = workspace
	standsFolder = sf :: Folder
	local oa = root:FindFirstChild("OfferAction")
	if not (oa and oa:IsA("RemoteFunction")) then
		oa = Instance.new("RemoteFunction")
		oa.Name = "OfferAction"
		oa.Parent = root
	end
	offerAction = oa :: RemoteFunction
	offers = Offers.new(Config.Offer.TimeoutSeconds, RunService:IsStudio())
	offerAction.OnServerInvoke = function(player, offerId, action)
		return M._offerAction(player, offerId, action)
	end
	root:GetAttributeChangedSignal(Config.RodOffersAttribute):Connect(function()
		if root:GetAttribute(Config.RodOffersAttribute) == false then
			offers:cancelAll("disabled") -- nothing charged, nothing delivered
		end
	end)
	table.insert(M._onLeave, function(player: Player)
		offers:cancelForUser(player.UserId, "left") -- nothing charged, nothing delivered
		lastOfferAction[player] = nil
	end)

	-- Studio test clients (negative UserIds) always use a memory store, so
	-- local multi-client tests never write keys to the real DataStore.
	local real = pickStore()
	local testStore = memoryStore()
	local store: MoneyStore.Store = {
		update = function(key: string, transform: (any) -> any): any
			if string.sub(key, #Config.KeyPrefix + 1, #Config.KeyPrefix + 1) == "-" then
				return testStore.update(key, transform)
			end
			return real.update(key, transform)
		end,
	}
	local sessionId = MoneyStore.sessionId(game.JobId, function()
		return HttpService:GenerateGUID(false)
	end)
	money = MoneyStore.new(store, sessionId, os.time)
	ledger = Ledger.new("P", RunService:IsStudio())

	Players.PlayerAdded:Connect(function(p)
		task.spawn(loadPlayer, p)
	end)
	for _, p in ipairs(Players:GetPlayers()) do
		task.spawn(loadPlayer, p)
	end
	Players.PlayerRemoving:Connect(function(p)
		for _, fn in ipairs(M._onLeave) do
			pcall(fn, p)
		end
		unloadPlayer(p)
	end)
	task.spawn(function()
		while true do
			task.wait(Config.AutosaveSeconds)
			for _, userId in ipairs(money:users()) do
				if money:state(userId) == "Ready" then
					task.spawn(saveWithRetry, userId, false)
				end
			end
		end
	end)
	game:BindToClose(function()
		local waiting = 0
		for _, userId in ipairs(money:users()) do
			if money:state(userId) == "Ready" then
				waiting += 1
				task.spawn(function()
					saveWithRetry(userId, true)
					waiting -= 1
				end)
			end
		end
		local t0 = os.clock()
		while waiting > 0 and os.clock() - t0 < 25 do
			task.wait(0.1)
		end
	end)

	startOk = true
	root:SetAttribute("Running", true)
	root:SetAttribute("Store", storeKind)
	log("running (" .. storeKind .. " store)")
	return true
end

function M.running(): boolean
	return startOk
end

M._onLeave = {} :: { (Player) -> () }
function M.onPlayerLeaving(fn: (Player) -> ())
	table.insert(M._onLeave, fn)
end

------------------------------------------------------------ money API

function M.balance(player: Player): number?
	if not startOk then
		return nil
	end
	return money:balance(player.UserId)
end

-- Takes exactly `amount` from the player or nothing. Synchronous (no
-- yields). Returns (ok, reason) with reason "funds" | "notLoaded" | ...
function M.tryDebit(player: Player, amount: number, reason: string): (boolean, string?)
	if not startOk then
		return false, "notLoaded"
	end
	if typeof(player) ~= "Instance" or not player:IsA("Player") or player.Parent ~= Players then
		return false, "notLoaded"
	end
	local ok, why = money:tryDebit(player.UserId, amount)
	if ok then
		sync(player)
	end
	return ok, why
end

-- Pays `amount` to a player (Player or UserId). Returns "paid" | "pending"
-- | "dropped" | "absent" (not in this server: not paid).
function M.credit(who: any, amount: number, reason: string): string
	if not startOk then
		return "dropped"
	end
	local userId = userIdOf(who)
	local player = userId and Players:GetPlayerByUserId(userId)
	if not player then
		return "absent"
	end
	local result = money:credit(userId :: number, amount)
	if result == "paid" then
		sync(player)
	end
	return result
end

function M.refund(player: Player, amount: number, reason: string)
	local r = M.credit(player, amount, "refund:" .. reason)
	if r ~= "paid" and r ~= "pending" then
		warn(string.format("[Economy] refund of %d to %s not applied (%s)", amount, player.Name, r))
	end
end

function M.rodShopOpen(): boolean
	return startOk and Config.RodShopOpen == true
end

------------------------------------------------------------ meat ledger

-- GrinderProcessor: cut one fish into ledger pieces. Returns their ids
-- (count = meat yield for the tier). `player` is the net-pad player (nil
-- for the harpoon); `meta` is the catch payload ({ OwnerId, Variant, Source }).
function M.issueFish(player: Player?, fishName: any, tier: any, meta: any): { string }
	if not startOk then
		return {}
	end
	local playerId = if player then player.UserId else nil
	return Sales.issue(ledger, playerId, fishName, tier, meta)
end

-- Stamps a piece's identity on the object that stands for it.
function M.stamp(obj: Instance, pieceId: string)
	local piece = startOk and ledger:get(pieceId)
	if piece then
		PieceTags.stamp(obj, piece)
	end
end

-- BotSystem: copy identity from the picked meat to its carried clone.
function M.readPiece(obj: Instance): { [string]: any }?
	return PieceTags.read(obj)
end
function M.writePiece(obj: Instance, tags: { [string]: any }?)
	PieceTags.write(obj, tags)
end

-- TruckSystem: a player picked a piece up to carry to a truck.
function M.carry(pieceId: any): boolean
	return startOk and ledger:carry(pieceId)
end

-- The one sale of a piece: pays its owner (if in the server). Returns
-- (paid, amount). An unknown / already-settled id pays nothing.
function M.settle(pieceId: any, route: string): (boolean, number)
	if not startOk then
		return false, 0
	end
	local paid, amount = Sales.settle(ledger, pieceId, function(ownerId, value)
		return M.credit(ownerId, value, "sale:" .. route)
	end)
	return paid, amount
end

-- The object for a piece is gone without a sale: keep the piece as data.
function M.hold(pieceId: any): boolean
	return startOk and ledger:hold(pieceId)
end

-- Oldest held piece back to Live; the grinder makes its object.
function M.takeHeld(): Ledger.Piece?
	if not startOk then
		return nil
	end
	return ledger:takeHeld()
end

function M.heldCount(): number
	return if startOk then ledger.heldCount else 0
end

-- Too much meat waiting: the harpoon skips shots and the net pad refuses.
function M.saturated(): boolean
	return startOk and ledger.heldCount >= Config.Pipeline.MaxHeld
end

function M.pipeline()
	return Config.Pipeline
end

------------------------------------------------------------ rod-fish offers

-- Offers are on while the service runs, unless ReplicatedStorage.Economy's
-- RodOffersEnabled attribute is false.
function M.rodOffersEnabled(): boolean
	return startOk and root:GetAttribute(Config.RodOffersAttribute) ~= false
end

local VARIANT_TEXT = { Silver = "SILVER ", Gold = "GOLD " }
local LIME = Color3.fromRGB(120, 255, 40)
local OUTLINE = Color3.fromRGB(10, 10, 12)

local function outlinedLabel(
	parent: Instance,
	name: string,
	text: string,
	color: Color3,
	y: number,
	h: number
): TextLabel
	local label = Instance.new("TextLabel")
	label.Name = name
	label.BackgroundTransparency = 1
	label.Position = UDim2.fromScale(0, y)
	label.Size = UDim2.fromScale(1, h)
	label.Font = Enum.Font.FredokaOne
	label.TextScaled = true
	label.TextColor3 = color
	label.Text = text
	local stroke = Instance.new("UIStroke")
	stroke.Color = OUTLINE
	stroke.Thickness = 2.5
	stroke.Parent = label
	label.Parent = parent
	return label
end

-- Everyone sees the catch's label above the fish: the real roll chance (only
-- when the rod supplied it), the species and the server price. It follows the
-- fish as clients animate it (adorned to the fish's part).
local function offerBillboard(
	fish: Model,
	fishName: string,
	variant: string?,
	price: number,
	chance: any
): BillboardGui?
	local adornee = fish.PrimaryPart or fish:FindFirstChildWhichIsA("BasePart", true)
	if not adornee then
		return nil
	end
	local gui = Instance.new("BillboardGui")
	gui.Name = "OfferGui"
	gui.Size = UDim2.fromOffset(200, 96)
	gui.StudsOffsetWorldSpace = Vector3.new(0, 3.4, 0)
	gui.AlwaysOnTop = true
	gui.MaxDistance = 140
	gui.LightInfluence = 0
	gui.Adornee = adornee
	local chanceText = Offers.chanceText(chance)
	if chanceText then
		outlinedLabel(gui, "Chance", "\u{1F340} " .. chanceText, LIME, 0, 0.24)
	end
	local nameColor = if variant == "Gold"
		then Color3.fromRGB(255, 205, 60)
		elseif variant == "Silver" then Color3.fromRGB(215, 230, 245)
		else Color3.new(1, 1, 1)
	outlinedLabel(gui, "FishName", (VARIANT_TEXT[variant or ""] or "") .. fishName, nameColor, 0.24, 0.32)
	outlinedLabel(gui, "Price", "$" .. tostring(price), LIME, 0.56, 0.44)
	gui.Parent = adornee
	return gui
end

-- The caster's buy point: an invisible anchored part at the rod stand. The
-- caster's EconomyClient puts a ProximityPrompt on it (only the caster's);
-- its attributes carry the offer for that client. Destroyed with the offer.
local function standAnchor(offer: Offers.Offer, stand: Vector3, expiresAt: number): Part
	local part = Instance.new("Part")
	part.Name = "BuyStand" .. offer.id
	part.Size = Vector3.new(1, 1, 1)
	part.Transparency = 1
	part.Anchored = true
	part.CanCollide = false
	part.CanQuery = false
	part.CanTouch = false
	part.CastShadow = false
	part.Archivable = false
	part.CFrame = CFrame.new(stand)
	part:SetAttribute("OfferId", offer.id)
	part:SetAttribute("CasterUserId", offer.casterId)
	part:SetAttribute("FishName", offer.fishName)
	part:SetAttribute("Variant", offer.variant)
	part:SetAttribute("Price", offer.price)
	part:SetAttribute("ExpiresAt", expiresAt)
	part:SetAttribute("PromptDistance", Config.Offer.PromptDistance)
	part.Parent = standsFolder
	return part
end

local function alive(player: Player): boolean
	local character = player.Character
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	return humanoid ~= nil and humanoid.Health > 0
end

local RESULT_TEXT = {
	bought = "Bought! It's going to the aquarium",
	alreadyBought = "Already bought",
	closed = "That fish is gone",
	unknown = "That fish is gone",
	notYours = "Only the player who cast can buy this fish",
	expired = "Too late - it slipped off the hook",
	tooFar = "Walk up to the rod to buy",
	tankUnavailable = "The aquarium can't take it - not charged",
	funds = "Not enough Money",
	notLoaded = "Money is still loading - try again",
	deliveryFailed = "Couldn't reach the aquarium - refunded",
	passed = "Passed - it swims off",
}

function M._offerAction(player: Player, offerId: any, action: any): (boolean, string)
	if not startOk or typeof(player) ~= "Instance" or player.Parent ~= Players then
		return false, "Not available"
	end
	if type(offerId) ~= "number" or (action ~= "buy" and action ~= "pass") then
		return false, "Bad request"
	end
	local now = os.clock()
	local last = lastOfferAction[player]
	if last and now - last < Config.Offer.ActionCooldown then
		return false, "Slow down"
	end
	lastOfferAction[player] = now
	local rec = offerRecs[offerId]
	if action == "pass" then
		local r = offers:pass(offerId, player.UserId)
		return r == "passed", RESULT_TEXT[r] or r
	end
	if not rec then
		return false, RESULT_TEXT.unknown
	end
	-- One synchronous sequence (Offers.buy): no yields between the checks,
	-- the debit and the delivery.
	local r = offers:buy(offerId, player.UserId, now, {
		inRange = function(): boolean
			-- measured from the rod stand (where the prompt is), not the fish
			local character = player.Character
			local hrp = character and character:FindFirstChild("HumanoidRootPart")
			if not (hrp and hrp:IsA("BasePart") and alive(player)) then
				return false
			end
			return Offers.inReach(
				(hrp.Position - rec.stand).Magnitude,
				Config.Offer.PromptDistance,
				Config.Offer.ReachSlack
			)
		end,
		reservationOk = function(): boolean
			return rec.reservationOk() == true
		end,
		debit = function(amount: number): (boolean, string?)
			return M.tryDebit(player, amount, "RodFish")
		end,
		deliver = function(): boolean
			return rec.deliver() == true
		end,
		refund = function(amount: number)
			M.refund(player, amount, "RodFish")
		end,
	})
	local text = RESULT_TEXT[r] or r
	M.notify(player, text, if r == "bought" then "success" elseif r == "alreadyBought" then "info" else "warn")
	return r == "bought" or r == "alreadyBought", text
end

export type RodOfferParams = {
	rodKey: any,
	caster: Player,
	fishName: string,
	tier: number,
	variant: string?,
	chance: number?, -- the fish's real roll chance on the rods (display only)
	fish: Model, -- the revealed fish on the line (price label)
	stand: Vector3, -- the rod stand's lowest point (buy prompt + range check)
	stillValid: () -> boolean, -- false = the aquarium can no longer take it
	reservationOk: () -> boolean, -- checked right before charging
	deliver: () -> boolean, -- puts the fish in the aquarium; false = failed (refund)
}

-- RodFishingSystem: offer a revealed fish to its caster and WAIT (yields)
-- until they buy it at the rod stand, it times out, they die or leave, or
-- the offer can't continue. Returns true only if it was paid for AND
-- delivered to the aquarium.
function M.runRodOffer(p: RodOfferParams): boolean
	if not M.rodOffersEnabled() then
		return false
	end
	local caster = p.caster
	if not (typeof(caster) == "Instance" and caster:IsA("Player") and caster.Parent == Players) then
		return false
	end
	if typeof(p.stand) ~= "Vector3" then
		warn("[Economy] rod offer not opened: no rod stand position")
		return false
	end
	if not alive(caster) then
		return false -- knocked out while reeling: it slips off, nothing charged
	end
	local variant = Pricing.variant(p.variant)
	local tier = if type(p.tier) == "number" then p.tier else 1
	local price = Pricing.offerPrice(tier, variant)
	local offer, why = offers:open(p.rodKey, caster.UserId, p.fishName, tier, variant, price, os.clock())
	if not offer then
		warn("[Economy] rod offer not opened: " .. tostring(why))
		return false
	end
	local standPos = p.stand + Vector3.new(0, Config.Offer.StandHeight, 0)
	local okGui, gui = pcall(offerBillboard, p.fish, p.fishName, variant, price, p.chance)
	local okStand, stand =
		pcall(standAnchor, offer, standPos, workspace:GetServerTimeNow() + Config.Offer.TimeoutSeconds)
	if not okStand then
		offers:cancel(offer.id, "error")
		warn("[Economy] buy stand failed: " .. tostring(stand))
	end
	offerRecs[offer.id] = { stand = standPos, reservationOk = p.reservationOk, deliver = p.deliver }

	while offer.status == "Open" or offer.status == "Delivering" do
		task.wait(0.1)
		if offer.status == "Open" then
			if os.clock() >= offer.expiresAt then
				offers:expire(os.clock())
			elseif caster.Parent ~= Players then
				offers:cancel(offer.id, "left")
			elseif not alive(caster) then
				offers:cancel(offer.id, "died")
			elseif not M.rodOffersEnabled() then
				offers:cancel(offer.id, "disabled")
			elseif not p.stillValid() or not p.fish.Parent then
				offers:cancel(offer.id, "tankUnavailable")
			end
		end
	end

	local bought = offer.status == "Bought"
	if offer.status == "Expired" then
		M.notify(caster, p.fishName .. " slipped off the hook (not bought)", "info")
	elseif offer.status == "Cancelled" and offer.reason == "died" then
		M.notify(caster, p.fishName .. " slipped off the hook - not charged", "info")
	elseif offer.status == "Cancelled" and offer.reason == "tankUnavailable" then
		M.notify(caster, "The aquarium closed - " .. p.fishName .. " was not charged", "warn")
	end
	offerRecs[offer.id] = nil
	offers:forget(offer.id)
	if okStand and stand then
		stand:Destroy()
	end
	if okGui and gui then
		gui:Destroy()
	end
	return bought
end

-- Rod task failed: cancel its open offer (no charge). Safe to call any time.
function M.cancelRodOffer(rodKey: any)
	if startOk then
		local id = offers.byRod[rodKey]
		if id then
			offers:cancel(id, "error")
		end
	end
end

-- Diagnostics (Command Bar during Play): require(...).stats()
function M.stats()
	if not startOk then
		return nil
	end
	local c = ledger:counts()
	return {
		store = storeKind,
		live = c.live,
		carried = c.carried,
		held = c.held,
		totals = table.clone(ledger.totals),
	}
end

return M
]] },
	{ key = "aquarium AquariumCycleServer", where = "ServerScriptService/AquariumCycleServer", class = "ModuleScript", tag = "AquariumCycleOwned", source = [[
-- AquariumCycleServer (ModuleScript in ServerScriptService).
--
-- Server side of the dock rod -> aquarium -> river cycle for the live shared
-- scene (one FishTank, five shared FishingRod1 rods, one BigButton). The
-- patched RodFishingSystem is the only caller; this module never starts on
-- its own. All game rules live in the pure ReplicatedStorage.AquariumCycle
-- modules; this file only binds them to the scene.
--
-- API used by RodFishingSystem:
--   start(rodKeys)          -> (ok, reason)  reason "disabled" when switched off
--   active()                -> bool
--   reserve(rods, player)   -> rods allowed to cast (a tank spot is reserved for each)
--   hasFreeSpot(player)     -> bool (tells the player when the tank is full)
--   hook(rodKey, fishName, meta?) -> bool  (meta: e.g. { Variant = "Gold", OwnerId = 123 }, carried unchanged)
--   land(rodKey)            -> bool
--   abort(rodKey)           -- frees the rod's spot; safe to call any time
--   entryPoint()            -> Vector3 above the tank water
--   toTankSeconds, toTankHeight
--
-- Everything this module creates or changes at runtime is undone by stop(),
-- which runs when the "Enabled" attribute on ReplicatedStorage.AquariumCycle
-- is switched off during play. Nothing it does at runtime is saved to the
-- place. It never grants currency.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local ServerScriptService = game:GetService("ServerScriptService")

local FOLDER_NAME = "AquariumCycle"

local M = {}
M.toTankSeconds = 1.3
M.toTankHeight = 12

local startedOnce = false
local running = false

local root: Folder
local Config, Upgrades, SharedTank, RiverRelease, Messages
local scene
local tank

local water: BasePart
local river: Instance
local riverBounds
local swimTemplates: Instance
local economy = nil -- { tryCharge = function(player, amount, reason) -> bool } or nil

local runtimeFolder: Folder
local tankFishFolder: Folder
local notice: RemoteEvent
local countUi = nil -- { amount = TextLabel, color = Color3 }
local prompts = {} -- id -> ProximityPrompt
local markers = {} -- fish id -> Configuration

local owned = {} -- runtime instances to destroy on stop()
local restore = {} -- functions undoing runtime changes to existing objects
local connections = {}
local lastAction = {}
local seedCounter = 0
local rng = Random.new()

local function clock(): number
	return os.clock()
end

local function own<T>(inst: T): T
	table.insert(owned, inst)
	return inst
end

local function notify(player: Player?, text: string, kind: string?)
	if player and notice and player.Parent then
		notice:FireClient(player, text, kind or "info")
	end
end

------------------------------------------------------------ bindings

local function binding(bindings: Instance, name: string, required: boolean): (Instance?, string?)
	local value = bindings:FindFirstChild(name)
	if not value or not value:IsA("ObjectValue") then
		return nil, if required then "missing binding " .. name else nil
	end
	if not value.Value then
		return nil, if required then "binding " .. name .. " is empty" else nil
	end
	return value.Value, nil
end

-- The placeholder count UI: Workspace.Model.Road.ProximityPrompt.BillboardGui
-- with TextLabel "Fish available" and TextLabel Amount. Bound only if that
-- exact structure and text are present; otherwise left untouched.
local function bindCountUi(prompt: Instance?)
	if not prompt or not prompt:IsA("ProximityPrompt") then
		return nil
	end
	local gui = prompt:FindFirstChild("BillboardGui")
	local title = gui and gui:FindFirstChild("TextLabel")
	local amount = gui and gui:FindFirstChild("Amount")
	if
		not (
			gui
			and gui:IsA("BillboardGui")
			and title
			and title:IsA("TextLabel")
			and amount
			and amount:IsA("TextLabel")
		)
	then
		warn("[AquariumCycle] count UI structure not as expected; leaving it untouched")
		return nil
	end
	if title.Text ~= "Fish available" then
		warn("[AquariumCycle] count UI title is '" .. title.Text .. "', not 'Fish available'; leaving it untouched")
		return nil
	end
	local original = {
		title = title.Text,
		amount = amount.Text,
		color = amount.TextColor3,
		enabled = prompt.Enabled,
	}
	table.insert(restore, function()
		title.Text = original.title
		amount.Text = original.amount
		amount.TextColor3 = original.color
		prompt.Enabled = original.enabled
	end)
	title.Text = scene.TitleText
	if scene.HidePlaceholderPrompt then
		-- The "E / NEW CAR / PLACE CAR" prompt is a placeholder; hide it while
		-- the aquarium runs so it can't be confused with Release Fish.
		prompt.Enabled = false
	end
	return { amount = amount, color = original.color }
end

-- Own billboard when the placeholder UI isn't bound.
local function makeCountUi()
	local gui = own(Instance.new("BillboardGui"))
	gui.Name = "AquariumCount"
	gui.Size = UDim2.fromOffset(160, 60)
	gui.StudsOffsetWorldSpace = Vector3.new(0, water.Size.Y / 2 + 3, 0)
	gui.MaxDistance = 120
	gui.Adornee = water
	local title = Instance.new("TextLabel")
	title.Size = UDim2.fromScale(1, 0.45)
	title.BackgroundTransparency = 1
	title.Font = Enum.Font.FredokaOne
	title.TextScaled = true
	title.TextColor3 = Color3.new(1, 1, 1)
	title.TextStrokeTransparency = 0.3
	title.Text = scene.TitleText
	title.Parent = gui
	local amount = title:Clone()
	amount.Name = "Amount"
	amount.Position = UDim2.fromScale(0, 0.45)
	amount.Size = UDim2.fromScale(1, 0.55)
	amount.Parent = gui
	gui.Parent = runtimeFolder
	return { amount = amount, color = amount.TextColor3 }
end

------------------------------------------------------------ display

local function upgradeText(id: string, level: number): (string, string)
	local def = Config.Upgrades[id]
	local current = Upgrades.value(Config, id, level)
	local cost = Upgrades.nextCost(Config, id, level)
	if cost == nil then
		return "Maxed", string.format("%s %d", def.DisplayName, current)
	end
	local nextValue = Upgrades.value(Config, id, level + 1)
	local price = if economy then tostring(cost) else "unavailable"
	return string.format("Upgrade %s", def.DisplayName), string.format("%d → %d (%s)", current, nextValue, price)
end

local function refresh()
	if not tank then
		return
	end
	local info = tank:info()
	if not info then
		return
	end
	if countUi then
		countUi.amount.Text = string.format("%d/%d", info.count, info.capacity)
		countUi.amount.TextColor3 = if info.full then Color3.fromRGB(table.unpack(scene.FullColor)) else countUi.color
	end
	for id, prompt in pairs(prompts) do
		if id ~= "Release" then
			prompt.ActionText, prompt.ObjectText = upgradeText(id, info.levels[id])
		end
	end
	root:SetAttribute("TankCount", info.count)
	root:SetAttribute("TankCapacity", info.capacity)
	root:SetAttribute("TankFull", info.full)
end

------------------------------------------------------------ fish

-- Optional ReplicatedStorage.FishVariantVisuals (installed by the variants
-- feature); without it, fish are released without extra effects.
local function variantVisuals()
	local mod = ReplicatedStorage:FindFirstChild("FishVariantVisuals")
	if not (mod and mod:IsA("ModuleScript")) then
		return nil
	end
	local ok, v = pcall(require, mod)
	return if ok and type(v) == "table" then v else nil
end

local function setMeta(inst: Instance, meta)
	if type(meta) ~= "table" then
		return
	end
	for _, key in ipairs(scene.PassthroughAttributes or {}) do
		if meta[key] ~= nil then
			inst:SetAttribute(key, meta[key])
		end
	end
end

local function addMarker(id: number, name: string, meta)
	local marker = Instance.new("Configuration")
	marker.Name = "Fish" .. id
	marker:SetAttribute("FishId", id)
	marker:SetAttribute("FishName", name)
	marker:SetAttribute("Seed", id)
	marker:SetAttribute("EnterT", workspace:GetServerTimeNow())
	marker:SetAttribute("State", "Tank")
	setMeta(marker, meta)
	marker.Parent = tankFishFolder
	markers[id] = marker
end

local function removeMarker(id: number)
	local marker = markers[id]
	markers[id] = nil
	if marker then
		marker:Destroy()
	end
end

-- Puts a fish back into Workspace.SwimmingFish exactly like FishSpawner does,
-- so FishSwimClient animates it and the net can catch it. Attributes are set
-- before parenting because FishSwimClient reads them on ChildAdded.
local function spawnIntoRiver(name: string?, meta)
	local template = name and swimTemplates:FindFirstChild(name)
	if not template then
		warn("[AquariumCycle] no SwimTemplate for released fish " .. tostring(name))
		return
	end
	local model = template:Clone()
	seedCounter += 1
	local s = RiverRelease.attributes(
		riverBounds,
		model:GetAttribute("SwimLen"),
		workspace:GetServerTimeNow(),
		scene.RiverSeedBase + seedCounter,
		rng:NextNumber(),
		rng:NextNumber(),
		scene.RiverSpeed
	)
	model:SetAttribute("SpawnT", s.SpawnT)
	model:SetAttribute("StartZ", s.StartZ)
	model:SetAttribute("Speed", s.Speed)
	model:SetAttribute("LaneX", s.LaneX)
	model:SetAttribute("Seed", s.Seed)
	model:SetAttribute("FromAquarium", true)
	setMeta(model, meta) -- e.g. Variant: kept from the original catch, never rerolled
	local visuals = variantVisuals()
	if visuals and model:GetAttribute("Variant") then
		pcall(visuals.applyToFish, model, model:GetAttribute("Variant"))
	end
	local at = Vector3.new(s.LaneX, s.y, s.StartZ)
	model:PivotTo(CFrame.lookAt(at, at + Vector3.new(0, 0, 1)))
	model.Parent = river
	task.delay(s.lifetime, function()
		-- v1.2: a fish the harpoon has already hit is the harpoon's to remove
		if model.Parent and not model:GetAttribute("CaughtT") and not model:GetAttribute("HarpoonT") then
			model:Destroy()
		end
	end)
end

local function handOff(list)
	for _, fish in ipairs(list) do
		removeMarker(fish.id)
		spawnIntoRiver(fish.name, fish.meta)
	end
end

------------------------------------------------------------ player actions

local function promptPosition(prompt: ProximityPrompt): Vector3
	local parent = prompt.Parent
	if parent and parent:IsA("Attachment") then
		return parent.WorldPosition
	elseif parent and parent:IsA("BasePart") then
		return parent.Position
	end
	return water.Position
end

-- Server-side check of the prompt trigger: live character, near the prompt,
-- and not spamming.
local function validPlayer(player: Player, prompt: ProximityPrompt): boolean
	local now = clock()
	if lastAction[player] and now - lastAction[player] < scene.PlayerActionCooldown then
		return false
	end
	lastAction[player] = now
	local character = player.Character
	local hrp = character and character:FindFirstChild("HumanoidRootPart")
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	if not (hrp and hrp:IsA("BasePart") and humanoid and humanoid.Health > 0) then
		return false
	end
	if (hrp.Position - promptPosition(prompt)).Magnitude > prompt.MaxActivationDistance + scene.PromptSlack then
		notify(player, Messages.forReason("tooFar"))
		return false
	end
	return true
end

local function onRelease(player: Player)
	if not running or not validPlayer(player, prompts.Release) then
		return
	end
	local ok, reason, fish = tank:release(clock())
	if not ok then
		notify(player, Messages.forReason(reason))
		return
	end
	local releaseT = workspace:GetServerTimeNow()
	for _, f in ipairs(fish) do
		local marker = markers[f.id]
		if marker then
			marker:SetAttribute("State", "Releasing")
			marker:SetAttribute("ReleaseT", releaseT)
			marker:SetAttribute("ReleaseDur", Config.ReleaseSwimSeconds)
		end
	end
	-- No payout: releasing never grants currency.
	notify(player, Messages.released(#fish), "success")
	refresh()
end

local function onUpgrade(player: Player, upgradeId: string)
	if not running or not validPlayer(player, prompts[upgradeId]) then
		return
	end
	-- The shared tank has no owner to bill, so the player who triggers the
	-- prompt pays through the economy binding (when one exists).
	local adapters = {}
	if economy then
		adapters.Economy = {
			tryCharge = function(_owner, amount, why)
				return economy.tryCharge(player, amount, why) == true
			end,
		}
	end
	local ok, reason, level = tank:buyUpgrade(adapters, upgradeId)
	if ok and level then
		local def = Config.Upgrades[upgradeId]
		notify(player, Messages.upgraded(def.DisplayName, Upgrades.value(Config, upgradeId, level)), "success")
	else
		notify(player, Messages.forReason(reason))
	end
	refresh()
end

local function makePrompt(parent: Instance, id: string, key: Enum.KeyCode, pad: Enum.KeyCode, offsetY: number)
	local prompt = own(Instance.new("ProximityPrompt"))
	prompt.Name = "Aquarium" .. id
	prompt.KeyboardKeyCode = key
	prompt.GamepadKeyCode = pad
	prompt.HoldDuration = 0
	prompt.RequiresLineOfSight = false
	prompt.MaxActivationDistance = scene.PromptDistance
	prompt.UIOffset = Vector2.new(0, offsetY)
	prompt.ObjectText = "Aquarium"
	prompt.ActionText = if id == "Release" then "Release Fish" else ""
	prompt.Parent = parent
	prompts[id] = prompt
	table.insert(
		connections,
		prompt.Triggered:Connect(function(player)
			if id == "Release" then
				onRelease(player)
			else
				onUpgrade(player, id)
			end
		end)
	)
	return prompt
end

------------------------------------------------------------ lifecycle

local function loadEconomy()
	local mod = ServerScriptService:FindFirstChild("AquariumEconomy")
	if not (mod and mod:IsA("ModuleScript")) then
		return nil
	end
	local ok, result = pcall(require, mod)
	if not ok then
		warn("[AquariumCycle] AquariumEconomy failed to load; upgrades unavailable: " .. tostring(result))
		return nil
	end
	if type(result) == "table" and type(result.tryCharge) == "function" then
		return result
	end
	return nil
end

function M.start(rodKeys: { any }): (boolean, string?)
	if startedOnce then
		return running, if running then nil else "already stopped"
	end
	startedOnce = true

	local folder = ReplicatedStorage:FindFirstChild(FOLDER_NAME)
	if not (folder and folder:IsA("Folder")) then
		return false, "ReplicatedStorage." .. FOLDER_NAME .. " not installed"
	end
	root = folder
	Config = require(root:WaitForChild("Config"))
	if not (Config.Enabled or root:GetAttribute("Enabled") == true) then
		return false, "disabled"
	end
	Upgrades = require(root:WaitForChild("Upgrades"))
	SharedTank = require(root:WaitForChild("SharedTank"))
	RiverRelease = require(root:WaitForChild("RiverRelease"))
	Messages = require(root:WaitForChild("Messages"))
	scene = Config.Scene
	M.toTankSeconds = scene.ToTankSeconds
	M.toTankHeight = scene.ToTankArcHeight

	-- Explicit bindings only (ObjectValues written by the installer).
	local bindings = root:FindFirstChild("Bindings")
	if not bindings then
		return false, "missing Bindings folder"
	end
	local problem
	local w, riv, templates
	w, problem = binding(bindings, "TankWater", true)
	if problem then
		return false, problem
	end
	riv, problem = binding(bindings, "River", true)
	if problem then
		return false, problem
	end
	templates, problem = binding(bindings, "SwimTemplates", true)
	if problem then
		return false, problem
	end
	if not (w and w:IsA("BasePart")) then
		return false, "TankWater binding is not a BasePart"
	end
	water = w
	river = riv :: Instance
	swimTemplates = templates :: Instance
	local b, why = RiverRelease.readBounds(function(name)
		return river:GetAttribute(name)
	end)
	if not b then
		return false, why
	end
	riverBounds = b

	tank = SharedTank.new(Config)
	if tank:registerRods(rodKeys) ~= #rodKeys or #rodKeys == 0 then
		return false, "could not register rods"
	end
	economy = loadEconomy()

	runtimeFolder = own(Instance.new("Folder"))
	runtimeFolder.Name = scene.RuntimeFolderName
	tankFishFolder = Instance.new("Folder")
	tankFishFolder.Name = "TankFish"
	tankFishFolder.Parent = runtimeFolder
	runtimeFolder.Parent = workspace

	notice = own(Instance.new("RemoteEvent"))
	notice.Name = "Notice"
	notice.Parent = root

	local countPrompt = binding(bindings, "CountPrompt", false)
	countUi = bindCountUi(countPrompt)
	if not countUi then
		countUi = makeCountUi()
	end

	-- Prompts sit where the placeholder prompt is (the spot players already
	-- walk to); otherwise at the bottom of the tank water.
	local promptParent: Instance
	local placeholderParent = countPrompt and countPrompt.Parent
	if placeholderParent and (placeholderParent:IsA("BasePart") or placeholderParent:IsA("Attachment")) then
		promptParent = placeholderParent
	else
		local att = own(Instance.new("Attachment"))
		att.Name = "AquariumPrompts"
		att.Position = Vector3.new(0, -water.Size.Y / 2 + 1, 0)
		att.Parent = water
		promptParent = att
	end
	makePrompt(promptParent, "Release", Enum.KeyCode.E, Enum.KeyCode.ButtonX, 0)
	makePrompt(promptParent, "Capacity", Enum.KeyCode.F, Enum.KeyCode.ButtonY, 80)
	makePrompt(promptParent, "ReleaseRate", Enum.KeyCode.G, Enum.KeyCode.ButtonB, 160)

	local acc = 0
	table.insert(
		connections,
		RunService.Heartbeat:Connect(function(dt)
			acc += dt
			if acc < scene.StepInterval then
				return
			end
			acc = 0
			local list = tank:step(clock())
			if #list > 0 then
				handOff(list)
				refresh()
			end
		end)
	)
	table.insert(
		connections,
		root:GetAttributeChangedSignal("Enabled"):Connect(function()
			if not Config.Enabled and root:GetAttribute("Enabled") ~= true then
				M.stop()
			end
		end)
	)
	table.insert(
		connections,
		Players.PlayerRemoving:Connect(function(player)
			lastAction[player] = nil
		end)
	)

	running = true
	root:SetAttribute("Running", true)
	refresh()
	if not economy then
		print("[AquariumCycle] running; upgrades unavailable (no currency binding in AquariumEconomy)")
	else
		print("[AquariumCycle] running")
	end
	return true, nil
end

function M.active(): boolean
	return running
end

function M.reserve(rods: { any }, player: Player?): { any }
	if not running then
		return rods
	end
	local keys, byKey = {}, {}
	for _, rod in ipairs(rods) do
		table.insert(keys, rod.key)
		byKey[rod.key] = rod
	end
	local reserved, reason = tank:reserve(keys, clock())
	local out = {}
	for _, key in ipairs(reserved) do
		table.insert(out, byKey[key])
	end
	if #out == 0 then
		notify(player, Messages.forReason(reason), "warn")
	end
	refresh()
	return out
end

function M.hasFreeSpot(player: Player?): boolean
	if not running then
		return true
	end
	local info = tank:info()
	if info and info.free > 0 then
		return true
	end
	notify(player, Messages.forReason("tankFull"), "warn")
	return false
end

function M.hook(rodKey: any, fishName: string, meta: any?): boolean
	if not running then
		return false
	end
	local ok, reason = tank:hook(rodKey, fishName, clock(), meta)
	if not ok and reason ~= "notWaiting" then
		warn("[AquariumCycle] hook refused for rod " .. tostring(rodKey) .. ": " .. tostring(reason))
	end
	return ok
end

function M.land(rodKey: any): boolean
	if not running then
		return false
	end
	local ok, reason, id, name, meta = tank:land(rodKey, clock())
	if not ok or not id then
		warn("[AquariumCycle] land refused for rod " .. tostring(rodKey) .. ": " .. tostring(reason))
		return false
	end
	addMarker(id, name or "", meta)
	refresh()
	return true
end

function M.abort(rodKey: any)
	if tank and running and tank:abort(rodKey) then
		refresh()
	end
end

function M.entryPoint(): Vector3
	return water.CFrame:PointToWorldSpace(Vector3.new(0, water.Size.Y / 2 + 1, 0))
end

-- Switch-off during play: every fish in the tank (or mid-release) is put back
-- into the river, rods in flight fall back to the grinder, and every runtime
-- change is undone.
function M.stop()
	if not running then
		return
	end
	running = false
	for _, c in ipairs(connections) do
		c:Disconnect()
	end
	table.clear(connections)
	handOff(tank:shutdown())
	for id in pairs(markers) do
		removeMarker(id)
	end
	for i = #restore, 1, -1 do
		pcall(restore[i])
	end
	table.clear(restore)
	for i = #owned, 1, -1 do
		local inst = owned[i]
		if inst and inst.Parent then
			inst:Destroy()
		end
	end
	table.clear(owned)
	table.clear(prompts)
	countUi = nil
	root:SetAttribute("Running", false)
	root:SetAttribute("TankCount", nil)
	root:SetAttribute("TankCapacity", nil)
	root:SetAttribute("TankFull", nil)
	print("[AquariumCycle] stopped; catches go to the grinder")
end

return M
]] },
}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; otherwise a path from a service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.old) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key, new = entry.new })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackUpgrades.lua restores the previous sources)")
