--[[
	InstallCustomerQueue.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Customer queue fix: customers stop jamming at the sale table.
	  * "At the counter" is a horizontal distance (<= 3 studs) to the slot plus a
	    vertical sanity bound (<= 6). The slots are ground points; a customer's
	    root part stands ~3 studs above, so the old 3-D check (> 3) could stay
	    false forever at the counter (live: 3.126) and block everyone behind.
	  * The front customer walks to the counter again once after 6 s and leaves
	    after 20 s without arriving, so the next one moves up.
	  * A customer that is removed, dies or whose script errors leaves the line.
	Changes only CustomerSystem (exactly the upgrade board release's version).
	Selling, prices and who is paid are unchanged.
	Requires: InstallBoardUpgrades (EconomyBoardUpgradesBackup).

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyCustomerQueueBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackCustomerQueue.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallCustomerQueue"
local BACKUP = "EconomyCustomerQueueBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomyBoardUpgradesBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyCustomerQueueBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "CustomerSystem", where = "script:CustomerSystem", class = "Script", variants = { { label = "board", old = [[
-- Customers: avatars of the server owner's friends walk out of the shops in the city,
-- down the sidewalk to the meat table at the end of the conveyor, buy a piece of meat
-- (if there is any), and walk back into the city.
--
-- [Economy board patch] Changes marked "Economy board": customers come for
-- EACH player in the server (EconomyService.customers(): Config.Customers),
-- never slower than the Car Sales upgrades publish. Without EconomyService
-- the spawn loop is exactly the original.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- A customer's purchase is the piece's one sale: EconomyService pays the piece's
-- owner its ledger value. The tier is read before the piece is destroyed.
local Players = game:GetService("Players")
local PhysicsService = game:GetService("PhysicsService")
local SS = game:GetService("ServerStorage")

local folder = workspace:WaitForChild("Customers")
local saleMeat = workspace:WaitForChild("SaleMeat")
local meatTemplate = SS:WaitForChild("MeatTemplate")
local bought = SS:WaitForChild("CustomerEvents"):WaitForChild("CustomerBought")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[CustomerSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[CustomerSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

-- tuning
local SPAWN_DELAY = { 10, 20 }   -- seconds between new customers
local MAX_IN_LINE = 4
local WAIT_FOR_MEAT = 18         -- how long they wait at the table before giving up
local WALK_SPEED = 9

-- route (sidewalk from the shop doors to the table)
local Y = 9.3
local DOORS = {
	{ door = Vector3.new(-125.6, Y, 185), out = Vector3.new(-126.1, Y, 184) },
	{ door = Vector3.new(-125.6, Y, 202), out = Vector3.new(-126.1, Y, 201) },
}
local CORNER = Vector3.new(-126.1, Y, 163.1)
local DOCK = Vector3.new(-94, Y, 163.1)
local SLOTS = { -- slot 1 is at the sale table, the rest line up behind
	Vector3.new(-94.8, Y, 152.5),
	Vector3.new(-94.8, Y, 157.5),
	Vector3.new(-94.6, Y, 162.4),
	Vector3.new(-98.5, Y, 163.1),
	Vector3.new(-102.5, Y, 163.1),
	Vector3.new(-106.5, Y, 163.1),
	Vector3.new(-110.5, Y, 163.1),
	Vector3.new(-114.5, Y, 163.1),
}
local TABLE_LOOK = Vector3.new(-80, Y, 152.5)

-- R15 default animations
local ANIM_IDLE = "rbxassetid://507766388"
local ANIM_WALK = "rbxassetid://507777826"

pcall(function()
	PhysicsService:RegisterCollisionGroup("Customers")
	PhysicsService:CollisionGroupSetCollidable("Customers", "Customers", false)
end)

------------------------------------------------ friends list
local friendIds = {}
local fetched = false
local function fetchFriends(player)
	if fetched then return end
	fetched = true
	local ok, pages = pcall(function() return Players:GetFriendsAsync(player.UserId) end)
	if ok and pages then
		while true do
			for _, f in ipairs(pages:GetCurrentPage()) do table.insert(friendIds, f.Id) end
			if pages.IsFinished or #friendIds >= 60 then break end
			local ok2 = pcall(function() pages:AdvanceToNextPageAsync() end)
			if not ok2 then break end
		end
	end
	if #friendIds == 0 then table.insert(friendIds, player.UserId) end
end
Players.PlayerAdded:Connect(fetchFriends)
for _, p in ipairs(Players:GetPlayers()) do task.spawn(fetchFriends, p) end

local descCache = {}
local function makeAvatar()
	local id = #friendIds > 0 and friendIds[math.random(1, #friendIds)] or nil
	local desc
	if id then
		desc = descCache[id]
		if not desc then
			local ok, d = pcall(function() return Players:GetHumanoidDescriptionFromUserId(id) end)
			if ok then desc = d descCache[id] = d end
		end
	end
	desc = desc or Instance.new("HumanoidDescription")
	local ok, model = pcall(function() return Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R15) end)
	if not ok or not model then return nil end
	if id then
		local ok2, name = pcall(function() return Players:GetNameFromUserIdAsync(id) end)
		model.Name = ok2 and name or "Customer"
	else
		model.Name = "Customer"
	end
	local anim = model:FindFirstChild("Animate") if anim then anim:Destroy() end
	for _, p in ipairs(model:GetDescendants()) do
		if p:IsA("BasePart") then p.CollisionGroup = "Customers" end
	end
	return model
end

------------------------------------------------ customer behaviour
local line = {}

local function walkTo(c, pos)
	local hum = c.hum
	if not hum.Parent or hum.Health <= 0 then return false end
	hum:MoveTo(pos)
	local done = false
	local conn = hum.MoveToFinished:Connect(function() done = true end)
	local t = 0
	while not done and t < 12 do t += task.wait(0.1) end
	conn:Disconnect()
	return true
end

local function face(c, target)
	local hrp = c.hrp
	local look = Vector3.new(target.X, hrp.Position.Y, target.Z)
	hrp.CFrame = CFrame.lookAt(hrp.Position, look)
end

local function topOfStack() -- nearest meat on the sale table
	local best, bd = nil, math.huge
	for _, m in ipairs(saleMeat:GetChildren()) do
		if not m:GetAttribute("Sold") then
			local d = (m.Position - SLOTS[1]).Magnitude
			if d < bd then best, bd = m, d end
		end
	end
	if best then best:SetAttribute("Sold", true) end
	return best
end

local function giveMeat(c, meat)
	local from = meat.Position
	local variant = meat:GetAttribute("Variant") -- MeatGlow: read before it goes
	meat:Destroy()
	local hand = c.model:FindFirstChild("RightHand") or c.hrp
	local p = meatTemplate:Clone()
	glow(p, variant) -- MeatGlow: in the customer's hand
	p.Anchored = true
	p.Parent = workspace
	local to = c.hrp.Position + c.hrp.CFrame.LookVector * 1.2 + Vector3.new(0, 0.3, 0)
	local t = 0
	while t < 0.35 do
		t += task.wait()
		local u = math.min(t / 0.35, 1)
		p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, 3 * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
	end
	-- hold it in front of them
	p.Anchored = false
	p.Massless = true
	p.CanCollide = false
	p.CFrame = c.hrp.CFrame * CFrame.new(0, 0.2, -1.1) * CFrame.Angles(0, math.rad(90), 0)
	local w = Instance.new("WeldConstraint")
	w.Part0 = c.hrp w.Part1 = p w.Parent = p
	p.Parent = c.model
end

local function reposition()
	for i, c in ipairs(line) do
		if c.state == "queued" and c.slot ~= i then
			c.slot = i
			task.spawn(function()
				walkTo(c, SLOTS[math.min(i, #SLOTS)])
				if i == 1 then face(c, TABLE_LOOK) end
			end)
		end
	end
end

local function leave(c)
	for i, x in ipairs(line) do if x == c then table.remove(line, i) break end end
	c.state = "leaving"
	reposition()
	walkTo(c, DOCK)
	walkTo(c, CORNER)
	walkTo(c, c.route.out)
	walkTo(c, c.route.door)
	c.model:Destroy()
end

local function runCustomer(c)
	walkTo(c, c.route.out)
	walkTo(c, CORNER)
	walkTo(c, DOCK)
	c.state = "queued"
	c.slot = nil
	reposition()
	-- wait until we're at the front and standing at the table
	while c.model.Parent and (line[1] ~= c or (c.hrp.Position - SLOTS[1]).Magnitude > 3) do task.wait(0.3) end
	if not c.model.Parent then return end
	face(c, TABLE_LOOK)
	task.wait(1.2)
	local waited = 0
	while waited < WAIT_FOR_MEAT do
		local meat = topOfStack()
		if meat then
			local tier = meat:GetAttribute("Tier") -- Economy: read before giveMeat destroys it
			if Economy then Economy.settle(meat:GetAttribute("PieceId"), "Customer") end -- Economy: the one sale
			giveMeat(c, meat)
			bought:Fire(c.model.Name, tier)
			task.wait(0.8)
			break
		end
		waited += task.wait(0.5)
	end
	leave(c)
end

local function spawnCustomer()
	local model = makeAvatar()
	if not model then return end
	local route = DOORS[math.random(1, #DOORS)]
	local hum = model:FindFirstChildOfClass("Humanoid")
	local hrp = model:FindFirstChild("HumanoidRootPart")
	hum.WalkSpeed = WALK_SPEED
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	local up = Vector3.new(0, 2.9, 0)
	model:PivotTo(CFrame.lookAt(route.door + up, route.out + up))
	model.Parent = folder
	pcall(function() hrp:SetNetworkOwner(nil) end)
	-- walk / idle animations
	local animator = hum:FindFirstChildOfClass("Animator") or Instance.new("Animator", hum)
	local idleA = Instance.new("Animation") idleA.AnimationId = ANIM_IDLE
	local walkA = Instance.new("Animation") walkA.AnimationId = ANIM_WALK
	local idle = animator:LoadAnimation(idleA)
	local walk = animator:LoadAnimation(walkA)
	idle.Looped = true walk.Looped = true
	idle:Play()
	hum.Running:Connect(function(speed)
		if speed > 0.5 then
			if not walk.IsPlaying then walk:Play(0.2) end
			walk:AdjustSpeed(speed / 12)
		else
			if walk.IsPlaying then walk:Stop(0.25) end
		end
	end)
	local c = { model = model, hum = hum, hrp = hrp, route = route, state = "walking" }
	table.insert(line, c)
	task.spawn(runCustomer, c)
end

task.wait(4)
while true do
	-- Economy board: a rate for each player (never below Car Sales' values)
	local rate, lineCap = nil, nil
	if Economy and Economy.customers then
		local ok, r, c = pcall(Economy.customers)
		if ok and type(r) == "number" and r > 0 and type(c) == "number" then
			rate, lineCap = r, c
		end
	end
	-- Customers upgrade (CarSalesServer) publishes rate + line cap on workspace
	local cap = lineCap or workspace:GetAttribute("CustomersLineCap") or MAX_IN_LINE
	if #Players:GetPlayers() > 0 and #line < cap then
		spawnCustomer()
	end
	local perMin = rate or workspace:GetAttribute("CustomersPerMin")
	if perMin then
		local gap = 60 / perMin
		task.wait(gap * (0.75 + math.random() * 0.5))
	else
		task.wait(math.random(SPAWN_DELAY[1] * 10, SPAWN_DELAY[2] * 10) / 10)
	end
end

]], new = [[
-- Customers: avatars of the server owner's friends walk out of the shops in the city,
-- down the sidewalk to the meat table at the end of the conveyor, buy a piece of meat
-- (if there is any), and walk back into the city.
--
-- [Queue fix] Changes marked "Queue fix": arriving at the counter is a
-- horizontal distance (the slots are ground points, a customer stands ~3
-- studs above them), the front customer gives up after a bounded time, and
-- removed / dead / errored customers leave the line - it can't jam.
--
-- [Economy board patch] Changes marked "Economy board": customers come for
-- EACH player in the server (EconomyService.customers(): Config.Customers),
-- never slower than the Car Sales upgrades publish. Without EconomyService
-- the spawn loop is exactly the original.
--
-- [MeatGlow patch] Changes marked "MeatGlow": Silver / Gold meat keeps its
-- glow when it is carried, laid out or loaded (display only; the value is in
-- the ledger). Needs ReplicatedStorage.FishVariantVisuals; without it this
-- script behaves exactly like its base version.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- A customer's purchase is the piece's one sale: EconomyService pays the piece's
-- owner its ledger value. The tier is read before the piece is destroyed.
local Players = game:GetService("Players")
local PhysicsService = game:GetService("PhysicsService")
local SS = game:GetService("ServerStorage")

local folder = workspace:WaitForChild("Customers")
local saleMeat = workspace:WaitForChild("SaleMeat")
local meatTemplate = SS:WaitForChild("MeatTemplate")
local bought = SS:WaitForChild("CustomerEvents"):WaitForChild("CustomerBought")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[CustomerSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[CustomerSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

-- MeatGlow: optional effects module (missing -> no glow, base behaviour)
local VariantFx = nil
do
	local mod = game:GetService("ReplicatedStorage"):FindFirstChild("FishVariantVisuals")
	if mod and mod:IsA("ModuleScript") then
		local ok, result = pcall(require, mod)
		if ok then
			VariantFx = result
		else
			warn("[MeatGlow] FishVariantVisuals failed to load: " .. tostring(result))
		end
	end
end
local function glow(part, variant)
	if VariantFx and variant then pcall(VariantFx.applyToPart, part, variant) end
end

-- tuning
local SPAWN_DELAY = { 10, 20 }   -- seconds between new customers
local MAX_IN_LINE = 4
local WAIT_FOR_MEAT = 18         -- how long they wait at the table before giving up
local WALK_SPEED = 9
-- Queue fix: arriving at a slot, and how long the front customer may try
local ARRIVE_XZ = 3 -- studs, horizontal, to the slot
local ARRIVE_Y = 6 -- studs, vertical sanity (the root part is ~3 above the slot)
local FRONT_RETRY = 6 -- s at the front without arriving: walk to the counter again
local FRONT_GIVE_UP = 20 -- s at the front without arriving: leave (the next moves up)

-- route (sidewalk from the shop doors to the table)
local Y = 9.3
local DOORS = {
	{ door = Vector3.new(-125.6, Y, 185), out = Vector3.new(-126.1, Y, 184) },
	{ door = Vector3.new(-125.6, Y, 202), out = Vector3.new(-126.1, Y, 201) },
}
local CORNER = Vector3.new(-126.1, Y, 163.1)
local DOCK = Vector3.new(-94, Y, 163.1)
local SLOTS = { -- slot 1 is at the sale table, the rest line up behind
	Vector3.new(-94.8, Y, 152.5),
	Vector3.new(-94.8, Y, 157.5),
	Vector3.new(-94.6, Y, 162.4),
	Vector3.new(-98.5, Y, 163.1),
	Vector3.new(-102.5, Y, 163.1),
	Vector3.new(-106.5, Y, 163.1),
	Vector3.new(-110.5, Y, 163.1),
	Vector3.new(-114.5, Y, 163.1),
}
local TABLE_LOOK = Vector3.new(-80, Y, 152.5)

-- R15 default animations
local ANIM_IDLE = "rbxassetid://507766388"
local ANIM_WALK = "rbxassetid://507777826"

pcall(function()
	PhysicsService:RegisterCollisionGroup("Customers")
	PhysicsService:CollisionGroupSetCollidable("Customers", "Customers", false)
end)

------------------------------------------------ friends list
local friendIds = {}
local fetched = false
local function fetchFriends(player)
	if fetched then return end
	fetched = true
	local ok, pages = pcall(function() return Players:GetFriendsAsync(player.UserId) end)
	if ok and pages then
		while true do
			for _, f in ipairs(pages:GetCurrentPage()) do table.insert(friendIds, f.Id) end
			if pages.IsFinished or #friendIds >= 60 then break end
			local ok2 = pcall(function() pages:AdvanceToNextPageAsync() end)
			if not ok2 then break end
		end
	end
	if #friendIds == 0 then table.insert(friendIds, player.UserId) end
end
Players.PlayerAdded:Connect(fetchFriends)
for _, p in ipairs(Players:GetPlayers()) do task.spawn(fetchFriends, p) end

local descCache = {}
local function makeAvatar()
	local id = #friendIds > 0 and friendIds[math.random(1, #friendIds)] or nil
	local desc
	if id then
		desc = descCache[id]
		if not desc then
			local ok, d = pcall(function() return Players:GetHumanoidDescriptionFromUserId(id) end)
			if ok then desc = d descCache[id] = d end
		end
	end
	desc = desc or Instance.new("HumanoidDescription")
	local ok, model = pcall(function() return Players:CreateHumanoidModelFromDescription(desc, Enum.HumanoidRigType.R15) end)
	if not ok or not model then return nil end
	if id then
		local ok2, name = pcall(function() return Players:GetNameFromUserIdAsync(id) end)
		model.Name = ok2 and name or "Customer"
	else
		model.Name = "Customer"
	end
	local anim = model:FindFirstChild("Animate") if anim then anim:Destroy() end
	for _, p in ipairs(model:GetDescendants()) do
		if p:IsA("BasePart") then p.CollisionGroup = "Customers" end
	end
	return model
end

------------------------------------------------ customer behaviour
local line = {}

local function walkTo(c, pos)
	local hum = c.hum
	if not hum.Parent or hum.Health <= 0 then return false end
	hum:MoveTo(pos)
	local done = false
	local conn = hum.MoveToFinished:Connect(function() done = true end)
	local t = 0
	while not done and t < 12 do t += task.wait(0.1) end
	conn:Disconnect()
	return true
end

local function face(c, target)
	local hrp = c.hrp
	local look = Vector3.new(target.X, hrp.Position.Y, target.Z)
	hrp.CFrame = CFrame.lookAt(hrp.Position, look)
end

local function topOfStack() -- nearest meat on the sale table
	local best, bd = nil, math.huge
	for _, m in ipairs(saleMeat:GetChildren()) do
		if not m:GetAttribute("Sold") then
			local d = (m.Position - SLOTS[1]).Magnitude
			if d < bd then best, bd = m, d end
		end
	end
	if best then best:SetAttribute("Sold", true) end
	return best
end

local function giveMeat(c, meat)
	local from = meat.Position
	local variant = meat:GetAttribute("Variant") -- MeatGlow: read before it goes
	meat:Destroy()
	local hand = c.model:FindFirstChild("RightHand") or c.hrp
	local p = meatTemplate:Clone()
	glow(p, variant) -- MeatGlow: in the customer's hand
	p.Anchored = true
	p.Parent = workspace
	local to = c.hrp.Position + c.hrp.CFrame.LookVector * 1.2 + Vector3.new(0, 0.3, 0)
	local t = 0
	while t < 0.35 do
		t += task.wait()
		local u = math.min(t / 0.35, 1)
		p.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, 3 * 4 * u * (1 - u), 0)) * CFrame.Angles(0, u * 6, 0)
	end
	-- hold it in front of them
	p.Anchored = false
	p.Massless = true
	p.CanCollide = false
	p.CFrame = c.hrp.CFrame * CFrame.new(0, 0.2, -1.1) * CFrame.Angles(0, math.rad(90), 0)
	local w = Instance.new("WeldConstraint")
	w.Part0 = c.hrp w.Part1 = p w.Parent = p
	p.Parent = c.model
end

local function reposition()
	for i, c in ipairs(line) do
		if c.state == "queued" and c.slot ~= i then
			c.slot = i
			task.spawn(function()
				walkTo(c, SLOTS[math.min(i, #SLOTS)])
				if i == 1 then face(c, TABLE_LOOK) end
			end)
		end
	end
end

-- Queue fix: at a slot = close horizontally, roughly at its height
local function atSlot(c, slot)
	local d = c.hrp.Position - slot
	return Vector3.new(d.X, 0, d.Z).Magnitude <= ARRIVE_XZ and math.abs(d.Y) <= ARRIVE_Y
end

-- Queue fix: still a customer that can walk and buy
local function alive(c)
	return c.model.Parent ~= nil and c.hum.Parent ~= nil and c.hum.Health > 0 and c.hrp.Parent ~= nil
end

-- Queue fix: out of the line for good (removed / dead / errored); idempotent
local function drop(c)
	for i, x in ipairs(line) do if x == c then table.remove(line, i) break end end
	c.state = "gone"
	reposition()
	if c.model.Parent then c.model:Destroy() end
end

local function leave(c)
	for i, x in ipairs(line) do if x == c then table.remove(line, i) break end end
	c.state = "leaving"
	reposition()
	walkTo(c, DOCK)
	walkTo(c, CORNER)
	walkTo(c, c.route.out)
	walkTo(c, c.route.door)
	c.model:Destroy()
end

local function runCustomer(c)
	walkTo(c, c.route.out)
	walkTo(c, CORNER)
	walkTo(c, DOCK)
	c.state = "queued"
	c.slot = nil
	reposition()
	-- wait until we're at the front and standing at the table
	-- Queue fix: horizontal arrival; bounded at the front; removed / dead -> dropped
	local frontFor, retried = 0, false
	while true do
		if not alive(c) then drop(c) return end
		if line[1] == c then
			if atSlot(c, SLOTS[1]) then break end
			if frontFor >= FRONT_GIVE_UP then leave(c) return end
			if frontFor >= FRONT_RETRY and not retried then
				retried = true
				task.spawn(walkTo, c, SLOTS[1])
			end
			frontFor += task.wait(0.3)
		else
			task.wait(0.3)
		end
	end
	face(c, TABLE_LOOK)
	task.wait(1.2)
	local waited = 0
	while waited < WAIT_FOR_MEAT do
		local meat = topOfStack()
		if meat then
			local tier = meat:GetAttribute("Tier") -- Economy: read before giveMeat destroys it
			if Economy then Economy.settle(meat:GetAttribute("PieceId"), "Customer") end -- Economy: the one sale
			giveMeat(c, meat)
			bought:Fire(c.model.Name, tier)
			task.wait(0.8)
			break
		end
		waited += task.wait(0.5)
	end
	leave(c)
end

local function spawnCustomer()
	local model = makeAvatar()
	if not model then return end
	local route = DOORS[math.random(1, #DOORS)]
	local hum = model:FindFirstChildOfClass("Humanoid")
	local hrp = model:FindFirstChild("HumanoidRootPart")
	hum.WalkSpeed = WALK_SPEED
	hum.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	local up = Vector3.new(0, 2.9, 0)
	model:PivotTo(CFrame.lookAt(route.door + up, route.out + up))
	model.Parent = folder
	pcall(function() hrp:SetNetworkOwner(nil) end)
	-- walk / idle animations
	local animator = hum:FindFirstChildOfClass("Animator") or Instance.new("Animator", hum)
	local idleA = Instance.new("Animation") idleA.AnimationId = ANIM_IDLE
	local walkA = Instance.new("Animation") walkA.AnimationId = ANIM_WALK
	local idle = animator:LoadAnimation(idleA)
	local walk = animator:LoadAnimation(walkA)
	idle.Looped = true walk.Looped = true
	idle:Play()
	hum.Running:Connect(function(speed)
		if speed > 0.5 then
			if not walk.IsPlaying then walk:Play(0.2) end
			walk:AdjustSpeed(speed / 12)
		else
			if walk.IsPlaying then walk:Stop(0.25) end
		end
	end)
	local c = { model = model, hum = hum, hrp = hrp, route = route, state = "walking" }
	table.insert(line, c)
	task.spawn(function() -- Queue fix: an error never leaves a stale place in the line
		local ok, err = pcall(runCustomer, c)
		if not ok then
			warn("[CustomerSystem] customer failed, removed from the line: " .. tostring(err))
			drop(c)
		end
	end)
end

task.wait(4)
while true do
	-- Economy board: a rate for each player (never below Car Sales' values)
	local rate, lineCap = nil, nil
	if Economy and Economy.customers then
		local ok, r, c = pcall(Economy.customers)
		if ok and type(r) == "number" and r > 0 and type(c) == "number" then
			rate, lineCap = r, c
		end
	end
	-- Customers upgrade (CarSalesServer) publishes rate + line cap on workspace
	local cap = lineCap or workspace:GetAttribute("CustomersLineCap") or MAX_IN_LINE
	for i = #line, 1, -1 do -- Queue fix: sweep removed / dead customers that still hold a place
		local c = line[i]
		if c.state ~= "walking" and not alive(c) then drop(c) end
	end
	if #Players:GetPlayers() > 0 and #line < cap then
		spawnCustomer()
	end
	local perMin = rate or workspace:GetAttribute("CustomersPerMin")
	if perMin then
		local gap = 60 / perMin
		task.wait(gap * (0.75 + math.random() * 0.5))
	else
		task.wait(math.random(SPAWN_DELAY[1] * 10, SPAWN_DELAY[2] * 10) / 10)
	end
end

]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {

}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackCustomerQueue.lua restores the previous sources)")
