--[[
	InstallRodShopUI.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Rod shop UI (StarterGui.ScreenGui.Buttons.Frames.RodShopFrame.RodShopController):
	  * each card shows the real price (or OWNED), the benefit ("Bites 15%
	    faster"), and a button that says what pressing does: BUY / EQUIP /
	    EQUIPPED / SOON (paid shop not open) / SOLD OUT - live from the
	    server's attributes, nothing captured once
	  * pressing: "..." while the server answers (one request per rod; the
	    equipped rod sends nothing), then the server's real result (BOUGHT! /
	    EQUIPPED / NEED $ / TOO FAR / NOT SAVED / ...) with the full message on
	    a status line under the cards (it used to show "NO $ YET" for most
	    refusals)
	  * the picture, restock countdown, open / close and scrolling are
	    unchanged; the client decides nothing (the server checks and charges)
	Changes one LocalScript (checked by its exact source and path).
	Requires: rods (InstallRods.lua, EconomyRodsBackup).

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyRodShopUIBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackRodShopUI.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallRodShopUI"
local BACKUP = "EconomyRodShopUIBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomyRodsBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyRodShopUIBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "RodShopController", where = "StarterGui/ScreenGui/Buttons/Frames/RodShopFrame/RodShopController", class = "LocalScript", variants = { { label = "live", old = [[
-- Rod shop UI: opens from the shop stand prompt, shows each rod with price + stock, restock countdown.
local Players = game:GetService("Players")
local RS = game:GetService("ReplicatedStorage")
local SoundService = game:GetService("SoundService")
local ProximityPromptService = game:GetService("ProximityPromptService")
local player = Players.LocalPlayer

local frame = script.Parent
local scroll = frame:WaitForChild("ScrollingFrame")
local template = scroll:WaitForChild("CarTemplate")
local timerLabel = frame:WaitForChild("RestockTimer"):WaitForChild("TextLabel")
local closeButton = frame:WaitForChild("CloseButton")
local rods = RS:WaitForChild("Rods")
local shop = RS:WaitForChild("RodShop")
local buyRemote = shop:WaitForChild("BuyRod")

local RARITY_COLORS = {
	Common = Color3.fromRGB(210, 210, 210), Uncommon = Color3.fromRGB(90, 230, 90), Rare = Color3.fromRGB(60, 150, 255),
	Epic = Color3.fromRGB(180, 80, 255), Legendary = Color3.fromRGB(255, 190, 40),
}

local function click() local s = SoundService:FindFirstChild("Click") if s then s:Play() end end
local function money(n)
	local s = tostring(math.floor(n))
	local out = s:reverse():gsub("(%d%d%d)", "%1,"):reverse()
	return "$" .. out:gsub("^,", "")
end

-- bright outlined rod picture, laid diagonally so it fills the square
local function fillViewport(vp, rodModel)
	vp.Ambient = Color3.new(1, 1, 1) vp.LightColor = Color3.new(1, 1, 1) vp.LightDirection = Vector3.new(-0.3, -1, -0.6)
	vp.BackgroundTransparency = 1
	local m = rodModel:Clone()
	for _, d in ipairs(m:GetDescendants()) do
		if d:IsA("BasePart") then d.Anchored = true if d.MaterialVariant ~= "" then d.MaterialVariant = "" d.Material = Enum.Material.SmoothPlastic end
		elseif d:IsA("LuaSourceContainer") then d:Destroy() end
	end
	m:PivotTo(CFrame.Angles(0, 0, math.rad(-42)) * CFrame.Angles(0, math.rad(90), 0))
	m.Parent = vp
	local cf = m:GetBoundingBox()
	local dir = Vector3.new(0, 0.1, 1).Unit
	local look = CFrame.lookAt(Vector3.zero, -dir)
	local R, U = look.RightVector, look.UpVector
	local t = math.tan(math.rad(15)) * 0.95
	local center, need = cf.Position, 0
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") and p.Transparency < 1 then
			local h = p.Size / 2
			for _, sx in ipairs({ -1, 1 }) do for _, sy in ipairs({ -1, 1 }) do for _, sz in ipairs({ -1, 1 }) do
				local q = p.CFrame * Vector3.new(sx * h.X, sy * h.Y, sz * h.Z) - center
				local along = q:Dot(dir)
				need = math.max(need, math.abs(q:Dot(R)) / t + along, math.abs(q:Dot(U)) / t + along)
			end end end
		end
	end
	local cam = Instance.new("Camera") cam.FieldOfView = 30
	cam.CFrame = CFrame.lookAt(center + dir * need, center)
	cam.Parent = vp vp.CurrentCamera = cam
	local z = vp.ZIndex vp.ZIndex = z + 1
	for _, d in ipairs({ { 1, 1 }, { -1, 1 }, { 1, -1 }, { -1, -1 } }) do
		local cp = vp:Clone() cp.Name = "Outline" cp.ImageColor3 = Color3.new(0, 0, 0) cp.ZIndex = z
		cp.Position = vp.Position + UDim2.fromOffset(d[1] * 3, d[2] * 3)
		cp.CurrentCamera = cp:FindFirstChildOfClass("Camera") cp.Parent = vp.Parent
	end
end

-- build cards (cheapest first)
local list = rods:GetChildren()
table.sort(list, function(a, b) return (a:GetAttribute("Order") or 0) < (b:GetAttribute("Order") or 0) end)
local cards = {}
for _, rod in ipairs(list) do
	local card = template:Clone()
	card.Name = rod.Name
	card.Visible = true
	card.LayoutOrder = rod:GetAttribute("Order") or 0
	local rarity = rod:GetAttribute("Rarity") or "Common"
	card.Rarity.Text = rarity
	card.Rarity.TextColor3 = RARITY_COLORS[rarity] or Color3.new(1, 1, 1)
	card.Mutation.Text = rod:GetAttribute("DisplayName") or rod.Name
	card.Price.Text = money(rod:GetAttribute("Price") or 0)
	local stock = card.Mutation:Clone()
	stock.Name = "Stock"
	stock.Position = UDim2.new(0.5, 0, 0.745, 0)
	stock.Parent = card
	fillViewport(card.ViewportFrame, rod)
	local buy = card.BuyButton
	buy.Activated:Connect(function()
		click()
		local ok, msg = buyRemote:InvokeServer(rod.Name)
		local label = buy.Price
		local before = label.Text
		label.Text = ok and "BOUGHT!" or (msg == "Not enough money" and "NEED $" or (msg == "Sold out" and "SOLD OUT" or "NO $ YET"))
		task.delay(1.2, function() if label.Parent then label.Text = before end end)
	end)
	card.Parent = scroll
	cards[rod.Name] = card
end

local function refresh()
	for name, card in pairs(cards) do
		local s = player:GetAttribute("RodStock_" .. name) or 0
		card.Stock.Text = s > 0 and ("x" .. s .. " Stock") or "Out of stock"
		card.Stock.TextColor3 = s > 0 and Color3.fromRGB(120, 255, 120) or Color3.fromRGB(255, 90, 90)
		card.BuyButton.Price.Text = s > 0 and "BUY" or "SOLD OUT"
	end
end
player.AttributeChanged:Connect(function(a) if a:sub(1, 9) == "RodStock_" then refresh() end end)
refresh()

-- restock countdown
task.spawn(function()
	while true do
		local nextAt = shop:GetAttribute("NextRestock")
		if nextAt then
			local left = math.max(0, math.floor(nextAt - workspace:GetServerTimeNow()))
			timerLabel.Text = string.format("Restock: %d:%02d", left // 60, left % 60)
		end
		task.wait(0.25)
	end
end)

-- open from the shop stand, close with X
ProximityPromptService.PromptTriggered:Connect(function(prompt)
	if prompt.Name == "OpenShopPrompt" then frame.Visible = true end
end)
closeButton.MouseButton1Click:Connect(function() frame.Visible = false end)

-- make sure the whole list can be scrolled (auto canvas size misses wrapped rows)
do
	local layout = scroll:FindFirstChildOfClass("UIListLayout") or scroll:FindFirstChildOfClass("UIGridLayout")
	local pad = scroll:FindFirstChildOfClass("UIPadding")
	scroll.AutomaticCanvasSize = Enum.AutomaticSize.None
	local function fit()
		local extra = 30
		if pad then extra += pad.PaddingTop.Offset + pad.PaddingBottom.Offset end
		scroll.CanvasSize = UDim2.fromOffset(0, layout.AbsoluteContentSize.Y + extra)
	end
	layout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(fit)
	scroll:GetPropertyChangedSignal("AbsoluteSize"):Connect(fit)
	fit()
end
]], new = [[
-- Rod shop UI: opens from the shop stand prompt, shows each rod with price + stock, restock countdown.
--
-- [Economy rods v1] Changes marked "Rods": each card shows the rod's real
-- price and benefit and whether you OWN it / have it EQUIPPED (the server's
-- RodOwned_<id> / EquippedRod attributes); the button says what pressing
-- does (BUY / EQUIP / EQUIPPED / SOON / SOLD OUT), shows "..." while the
-- server answers, then the server's real result; the full message appears
-- on a status line under the cards. The server checks and charges; nothing
-- here decides anything.
local Players = game:GetService("Players")
local RS = game:GetService("ReplicatedStorage")
local SoundService = game:GetService("SoundService")
local ProximityPromptService = game:GetService("ProximityPromptService")
local player = Players.LocalPlayer

local frame = script.Parent
local scroll = frame:WaitForChild("ScrollingFrame")
local template = scroll:WaitForChild("CarTemplate")
local timerLabel = frame:WaitForChild("RestockTimer"):WaitForChild("TextLabel")
local closeButton = frame:WaitForChild("CloseButton")
local rods = RS:WaitForChild("Rods")
local shop = RS:WaitForChild("RodShop")
local buyRemote = shop:WaitForChild("BuyRod")

-- Rods: the economy root (RodShopPaidOpen) and a status line under the cards
local econ = RS:FindFirstChild("Economy")
local LIME, GREEN, RED = Color3.fromRGB(120, 255, 40), Color3.fromRGB(120, 255, 120), Color3.fromRGB(255, 90, 90)
local status = Instance.new("TextLabel")
status.Name = "RodShopStatus"
status.AnchorPoint = Vector2.new(0.5, 0.5)
status.Position = UDim2.fromScale(0.5, 0.955)
status.Size = UDim2.fromScale(0.9, 0.065)
status.BackgroundTransparency = 1
status.Font = Enum.Font.FredokaOne
status.TextScaled = true
status.TextColor3 = Color3.new(1, 1, 1)
status.Text = ""
status.ZIndex = 5
do
	local st = Instance.new("UIStroke")
	st.Thickness = 2
	st.Color = Color3.fromRGB(10, 10, 12)
	st.Parent = status
end
status.Parent = frame
-- the server's replies -> short button text (anything else: TRY AGAIN)
local SHORT = {
	["Not enough money"] = "NEED $",
	["Sold out"] = "SOLD OUT",
	["The rod shop opens soon"] = "SOON",
	["Walk back to the rod shop to buy"] = "TOO FAR",
	["Your money is still loading - try again in a moment"] = "LOADING",
	["Couldn't save the purchase - you were not charged. Try again."] = "NOT SAVED",
	["One moment - still saving"] = "SAVING",
	["Slow down a little"] = "WAIT",
	["You already own that rod"] = "OWNED",
	["You can't do that right now"] = "NOT NOW",
	["The rod shop is unavailable right now"] = "CLOSED",
	["Your saved rods couldn't be read, so buying rods is off this session"] = "UNAVAILABLE",
}
local busy, flash = {}, {} -- rod name -> waiting for the server / { text, untilT }
local statusUntil = 0
local refresh -- defined below
local function paidOpen()
	return econ ~= nil and econ:GetAttribute("RodShopPaidOpen") == true
end
local function showStatus(text, seconds)
	status.Text = text
	statusUntil = os.clock() + seconds
	task.delay(seconds, function()
		if os.clock() >= statusUntil then
			refresh()
		end
	end)
end
-- one request per rod at a time; the equipped rod sends nothing
local function buyPressed(name)
	if busy[name] or player:GetAttribute("EquippedRod") == name then
		return
	end
	busy[name] = true
	refresh()
	local reached, ok, msg = pcall(function()
		return buyRemote:InvokeServer(name)
	end)
	busy[name] = nil
	local text
	if not reached then
		text, msg = "TRY AGAIN", "Couldn't reach the server - try again"
	elseif ok == true then
		text = if type(msg) == "string" and string.sub(msg, 1, 6) == "Bought" then "BOUGHT!" else "EQUIPPED"
	else
		text = SHORT[msg] or "TRY AGAIN"
	end
	flash[name] = { text = text, untilT = os.clock() + 1.6 }
	if type(msg) == "string" then
		showStatus(msg, 3)
	end
	refresh()
	task.delay(1.7, function()
		refresh()
	end)
end

local RARITY_COLORS = {
	Common = Color3.fromRGB(210, 210, 210), Uncommon = Color3.fromRGB(90, 230, 90), Rare = Color3.fromRGB(60, 150, 255),
	Epic = Color3.fromRGB(180, 80, 255), Legendary = Color3.fromRGB(255, 190, 40),
}

local function click() local s = SoundService:FindFirstChild("Click") if s then s:Play() end end
local function money(n)
	local s = tostring(math.floor(n))
	local out = s:reverse():gsub("(%d%d%d)", "%1,"):reverse()
	return "$" .. out:gsub("^,", "")
end

-- bright outlined rod picture, laid diagonally so it fills the square
local function fillViewport(vp, rodModel)
	vp.Ambient = Color3.new(1, 1, 1) vp.LightColor = Color3.new(1, 1, 1) vp.LightDirection = Vector3.new(-0.3, -1, -0.6)
	vp.BackgroundTransparency = 1
	local m = rodModel:Clone()
	for _, d in ipairs(m:GetDescendants()) do
		if d:IsA("BasePart") then d.Anchored = true if d.MaterialVariant ~= "" then d.MaterialVariant = "" d.Material = Enum.Material.SmoothPlastic end
		elseif d:IsA("LuaSourceContainer") then d:Destroy() end
	end
	m:PivotTo(CFrame.Angles(0, 0, math.rad(-42)) * CFrame.Angles(0, math.rad(90), 0))
	m.Parent = vp
	local cf = m:GetBoundingBox()
	local dir = Vector3.new(0, 0.1, 1).Unit
	local look = CFrame.lookAt(Vector3.zero, -dir)
	local R, U = look.RightVector, look.UpVector
	local t = math.tan(math.rad(15)) * 0.95
	local center, need = cf.Position, 0
	for _, p in ipairs(m:GetDescendants()) do
		if p:IsA("BasePart") and p.Transparency < 1 then
			local h = p.Size / 2
			for _, sx in ipairs({ -1, 1 }) do for _, sy in ipairs({ -1, 1 }) do for _, sz in ipairs({ -1, 1 }) do
				local q = p.CFrame * Vector3.new(sx * h.X, sy * h.Y, sz * h.Z) - center
				local along = q:Dot(dir)
				need = math.max(need, math.abs(q:Dot(R)) / t + along, math.abs(q:Dot(U)) / t + along)
			end end end
		end
	end
	local cam = Instance.new("Camera") cam.FieldOfView = 30
	cam.CFrame = CFrame.lookAt(center + dir * need, center)
	cam.Parent = vp vp.CurrentCamera = cam
	local z = vp.ZIndex vp.ZIndex = z + 1
	for _, d in ipairs({ { 1, 1 }, { -1, 1 }, { 1, -1 }, { -1, -1 } }) do
		local cp = vp:Clone() cp.Name = "Outline" cp.ImageColor3 = Color3.new(0, 0, 0) cp.ZIndex = z
		cp.Position = vp.Position + UDim2.fromOffset(d[1] * 3, d[2] * 3)
		cp.CurrentCamera = cp:FindFirstChildOfClass("Camera") cp.Parent = vp.Parent
	end
end

-- build cards (cheapest first)
local list = rods:GetChildren()
table.sort(list, function(a, b) return (a:GetAttribute("Order") or 0) < (b:GetAttribute("Order") or 0) end)
local cards = {}
for _, rod in ipairs(list) do
	local card = template:Clone()
	card.Name = rod.Name
	card.Visible = true
	card.LayoutOrder = rod:GetAttribute("Order") or 0
	local rarity = rod:GetAttribute("Rarity") or "Common"
	card.Rarity.Text = rarity
	card.Rarity.TextColor3 = RARITY_COLORS[rarity] or Color3.new(1, 1, 1)
	card.Mutation.Text = rod:GetAttribute("DisplayName") or rod.Name
	card.Price.Text = money(rod:GetAttribute("Price") or 0)
	local stock = card.Mutation:Clone()
	stock.Name = "Stock"
	stock.Position = UDim2.new(0.5, 0, 0.745, 0)
	stock.Parent = card
	fillViewport(card.ViewportFrame, rod)
	local buy = card.BuyButton
	buy.Activated:Connect(function()
		click()
		buyPressed(rod.Name) -- Rods: the server's real answer, see buyPressed
	end)
	card.Parent = scroll
	cards[rod.Name] = card
end

-- Rods: price or OWNED, benefit, and what the button does, all from the
-- server's attributes (they can change while the shop is open)
function refresh()
	local open = paidOpen()
	local now = os.clock()
	for name, card in pairs(cards) do
		local rod = rods:FindFirstChild(name)
		local owned = player:GetAttribute("RodOwned_" .. name) ~= nil
		local equipped = player:GetAttribute("EquippedRod") == name
		local s = player:GetAttribute("RodStock_" .. name) or 0
		local price = rod and rod:GetAttribute("Price") or 0
		local benefit = rod and rod:GetAttribute("Benefit")
		card.Price.Text = if owned then "OWNED" else money(price)
		local soldOut = not owned and s <= 0
		if type(benefit) == "string" then
			card.Stock.Text = if soldOut then benefit .. " - sold out" else benefit
		else
			card.Stock.Text = s > 0 and ("x" .. s .. " Stock") or "Out of stock"
		end
		card.Stock.TextColor3 = if soldOut then RED else GREEN
		local f = flash[name]
		local label
		if busy[name] then
			label = "..."
		elseif f and now < f.untilT then
			label = f.text
		elseif equipped then
			label = "EQUIPPED"
		elseif owned then
			label = "EQUIP"
		elseif not open then
			label = "SOON"
		elseif soldOut then
			label = "SOLD OUT"
		else
			label = "BUY"
		end
		card.BuyButton.Price.Text = label
		card.BuyButton.Price.TextColor3 = if equipped then LIME else Color3.new(1, 1, 1)
	end
	if now >= statusUntil then
		status.Text = if econ == nil
			then "The rod shop is unavailable right now"
			elseif not open then "Buying opens soon - you can equip rods you own"
			else ""
	end
end
player.AttributeChanged:Connect(function(a)
	if a:sub(1, 9) == "RodStock_" or a:sub(1, 9) == "RodOwned_" or a == "EquippedRod" then refresh() end
end)
for _, rod in ipairs(rods:GetChildren()) do
	rod.AttributeChanged:Connect(function(a)
		if a == "Price" or a == "Benefit" then refresh() end
	end)
end
local function watchEconomy(e)
	econ = e
	e:GetAttributeChangedSignal("RodShopPaidOpen"):Connect(refresh)
	refresh()
end
if econ then
	watchEconomy(econ)
else
	RS.ChildAdded:Connect(function(c)
		if c.Name == "Economy" and not econ then watchEconomy(c) end
	end)
end
refresh()

-- restock countdown
task.spawn(function()
	while true do
		local nextAt = shop:GetAttribute("NextRestock")
		if nextAt then
			local left = math.max(0, math.floor(nextAt - workspace:GetServerTimeNow()))
			timerLabel.Text = string.format("Restock: %d:%02d", left // 60, left % 60)
		end
		task.wait(0.25)
	end
end)

-- open from the shop stand, close with X
ProximityPromptService.PromptTriggered:Connect(function(prompt)
	if prompt.Name == "OpenShopPrompt" then frame.Visible = true end
end)
closeButton.MouseButton1Click:Connect(function() frame.Visible = false end)

-- make sure the whole list can be scrolled (auto canvas size misses wrapped rows)
do
	local layout = scroll:FindFirstChildOfClass("UIListLayout") or scroll:FindFirstChildOfClass("UIGridLayout")
	local pad = scroll:FindFirstChildOfClass("UIPadding")
	scroll.AutomaticCanvasSize = Enum.AutomaticSize.None
	local function fit()
		local extra = 30
		if pad then extra += pad.PaddingTop.Offset + pad.PaddingBottom.Offset end
		scroll.CanvasSize = UDim2.fromOffset(0, layout.AbsoluteContentSize.Y + extra)
	end
	layout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(fit)
	scroll:GetPropertyChangedSignal("AbsoluteSize"):Connect(fit)
	fit()
end
]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {

}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackRodShopUI.lua restores the previous sources)")
