--[[
	InstallBotRecovery.lua - GENERATED by tools/economy/build/build_updates.py.
	Edit tools/economy sources and rebuild; don't edit this file.

	Blender Bot recovery: each trip of the bot runs under pcall. If anything
	errors while the bot holds a piece (between the stack and the table), the
	loose clone is removed and the piece is HELD in the ledger - the grinder
	brings it back out of the pipe with the same owner and value, so it is
	never lost unpaid - and the bot carries on after a short back-off (it used
	to stop for good, stranding the piece). One warning, then one per 20
	failures while something stays broken.
	Changes one script: BotSystem (the sales-patched version).
	Requires: sale payouts (InstallSales.lua). Independent of the earnings
	popup and the visual features.

	HOW TO RUN: stop Play, paste this whole file into the Command Bar (Edit
	mode), press Enter. It never runs automatically.

	It checks everything first and changes nothing if any check fails:
	  * Edit mode (not Play)
	  * the prerequisite installs are present, this one and anything later
	    are not (ServerStorage backup folders, listed below)
	  * EVERY script it changes or relies on is exactly the expected version
	    (it identifies the installed version by source, not by folder names)
	Then, in one undo step, it backs up each changed script to
	ServerStorage.EconomyBotBackup (Target ObjectValue + disabled Before/After
	copies), writes the new sources and adds the listed new objects (tagged
	EconomyOwned, recorded in the backup). It deletes nothing.
	RollbackBotRecovery.lua restores every Before source and removes what it added.
]]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "InstallBotRecovery"
local BACKUP = "EconomyBotBackup"
-- ServerStorage folders that must exist: each entry is a list of names, any one of which will do
local REQUIRES = { { "EconomySalesBackup" } }
-- ServerStorage folders that must NOT exist (this install and later milestones)
local FORBIDS = { "EconomyBotBackup", "EconomyMeatGlowBackup" }
-- { key, where, class, tag?, tagOnParent?, old, new } scripts this changes;
-- or { ..., variants = { { label, old, new }, ... } } when more than one
-- version can be live (the matching one is used)
local CHANGES = {
	{ key = "BotSystem", where = "script:BotSystem", class = "Script", variants = { { label = "sales", old = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

pose(0, 0)
while true do
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		continue
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then continue end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	meat:Destroy()
	local c = meatTemplate:Clone()
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	idle(0.25)
end
]], new = [[
-- The Blender Bot waddles between the meat stack (end of the conveyor) and the sale table,
-- carrying one piece of meat at a time and laying it on the table for customers.
--
-- [Economy patch v1] Changes vs. the live script are marked "Economy".
-- The carried/table clone keeps the picked piece's identity (PieceId, owner,
-- variant, tier, value), so the customer sale pays the right owner once.
--
-- [Bot recovery patch] Each trip runs under pcall. If anything errors while
-- the bot holds a piece (between the stack and the table), the loose clone is
-- removed and the piece is held in the ledger: the grinder brings it back out
-- of the pipe, so it is never lost unpaid. The bot then carries on (it used to
-- stop for good). Changes are marked "Recovery".
local RunService = game:GetService("RunService")
local SS = game:GetService("ServerStorage")

local bot = workspace:WaitForChild("Blender Bot")
local meatStack = workspace:WaitForChild("MeatStack")
local saleMeat = workspace:WaitForChild("SaleMeat")
local saleTable = workspace:WaitForChild("SaleTable")
local meatTemplate = SS:WaitForChild("MeatTemplate")

-- Economy: optional money service (missing or not running -> original behaviour)
local Economy = nil
do
	local mod = game:GetService("ServerScriptService"):FindFirstChild("EconomyService")
	if mod and mod:IsA("ModuleScript") then
		local ok, api = pcall(require, mod)
		if ok and type(api) == "table" then
			local ran, running = pcall(api.start)
			if ran and running then
				Economy = api
			else
				warn("[BotSystem] economy not running, original behaviour: " .. tostring(running))
			end
		else
			warn("[BotSystem] could not load EconomyService, original behaviour: " .. tostring(api))
		end
	end
end

local SPEED = 7
local GROUND = 8.75
local groundOff = bot:GetAttribute("GroundOffset") or 1.5
local PICK = Vector3.new(-84.3, GROUND, 160.2)   -- next to the meat box
local HOME = Vector3.new(-84.5, GROUND, 156)
local DROP_X = -85.6                               -- beside the sale table

local slots = {}
for i = 1, saleTable:GetAttribute("SlotCount") do slots[i] = saleTable:GetAttribute("Slot" .. i) end

local _, bsize = bot:GetBoundingBox()
local carryHeight = bsize.Y - groundOff + 0.6

local pos = Vector3.new(bot:GetPivot().X, GROUND, bot:GetPivot().Z)
local look = bot:GetPivot().LookVector
local carried = nil
local t = 0

local function pose(bob, roll)
	local p = pos + Vector3.new(0, groundOff + bob, 0)
	local cf = CFrame.lookAt(p, p + Vector3.new(look.X, 0, look.Z)) * CFrame.Angles(0, 0, math.rad(roll))
	bot:PivotTo(cf)
	if carried then
		carried.CFrame = CFrame.new(p + Vector3.new(0, carryHeight, 0)) * CFrame.lookAt(Vector3.zero, look).Rotation
	end
end

local function faceTo(target)
	local d = Vector3.new(target.X - pos.X, 0, target.Z - pos.Z)
	if d.Magnitude > 0.01 then look = d.Unit end
end

local function walkTo(target)
	target = Vector3.new(target.X, GROUND, target.Z)
	faceTo(target)
	while (target - pos).Magnitude > 0.05 do
		local dt = RunService.Heartbeat:Wait()
		t += dt
		local d = target - pos
		pos += d.Unit * math.min(d.Magnitude, SPEED * dt)
		pose(math.abs(math.sin(t * 12)) * 0.35, math.sin(t * 12) * 7) -- little waddle
	end
end

local function idle(sec)
	local e = 0
	while e < sec do
		local dt = RunService.Heartbeat:Wait()
		e += dt t += dt
		pose(math.sin(t * 3) * 0.08, 0)
	end
end

local function arc(part, from, to, dur, height)
	local e = 0
	while e < dur do
		e += RunService.Heartbeat:Wait()
		local u = math.min(e / dur, 1)
		part.CFrame = CFrame.new(from:Lerp(to, u) + Vector3.new(0, height * 4 * u * (1 - u), 0)) * part.CFrame.Rotation
	end
end

local function topOfStack()
	local best, bi = nil, -1
	for _, m in ipairs(meatStack:GetChildren()) do
		local i = m:GetAttribute("StackIndex") or 0
		if i > bi then best, bi = m, i end
	end
	return best
end

local function freeSlot()
	local used = {}
	for _, m in ipairs(saleMeat:GetChildren()) do used[m:GetAttribute("Slot") or 0] = true end
	for i = 1, #slots do if not used[i] then return i end end
end

-- Recovery: the piece in the bot's hands, from leaving the stack until it lies
-- on the table ({ pieceId = id?, part = clone? })
local inHand = nil

local function trip()
	local slot = freeSlot()
	local meat = slot and topOfStack()
	if not meat then
		if (pos - HOME).Magnitude > 0.5 then walkTo(HOME) end
		faceTo(Vector3.new(-78, GROUND, 160))
		idle(0.6)
		return
	end
	-- 1) go to the meat box and grab the top piece
	walkTo(PICK)
	faceTo(Vector3.new(-78, GROUND, PICK.Z))
	idle(0.2)
	meat = topOfStack()
	if not meat then return end
	local from = meat.Position
	local tags = Economy and Economy.readPiece(meat) -- Economy: keep the piece's identity
	inHand = { pieceId = tags and tags.PieceId } -- Recovery
	meat:Destroy()
	local c = meatTemplate:Clone()
	inHand.part = c -- Recovery
	c.Name = "CarriedMeat"
	if tags then Economy.writePiece(c, tags) end
	c.CFrame = CFrame.new(from)
	c.Parent = workspace
	arc(c, from, pos + Vector3.new(0, groundOff + carryHeight, 0), 0.25, 1.5)
	carried = c
	-- 2) waddle over to the table
	local target = slots[slot]
	walkTo(Vector3.new(DROP_X, GROUND, target.Z))
	faceTo(Vector3.new(target.X, GROUND, target.Z))
	idle(0.15)
	-- 3) put it on the table
	carried = nil
	c.Name = "Meat"
	c:SetAttribute("Slot", slot)
	arc(c, c.Position, target, 0.3, 1.2)
	c.CFrame = CFrame.new(target) * CFrame.Angles(0, math.rad(math.random(-10, 10)), 0)
	c.Parent = saleMeat
	inHand = nil -- Recovery: on the table, the customer sale takes it from here
	idle(0.25)
end

-- Recovery: whatever the bot was holding goes back to the ledger (held: the
-- grinder re-emits it), never lost unpaid. (Once it lies on the table inHand
-- is already nil: the customer sale takes it from there.)
local function recover()
	carried = nil
	local h = inHand
	inHand = nil
	if not h then return end
	if Economy and h.pieceId then
		pcall(Economy.hold, h.pieceId)
	end
	if h.part then pcall(function() h.part:Destroy() end) end
end

pose(0, 0)
local fails = 0
while true do
	local ok, err = pcall(trip)
	if ok then
		fails = 0
	else
		fails += 1
		recover()
		if fails == 1 or fails % 20 == 0 then
			warn("[BotSystem] trip failed (" .. fails .. "x), piece kept, retrying: " .. tostring(err))
		end
		task.wait(math.min(5, fails)) -- back off while something stays broken
	end
end
]] } } },
}
-- { where, name, class, source } objects this adds (must not exist yet)
local ADDS = {

}
-- { key, where, class, tag?, tagOnParent?, source } scripts that must be exactly this version
local UNCHANGED = {

}

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

-- " (first difference at line N: ...)" to help find what changed
local function firstDiff(actual, expected)
	local a, e = string.split(normalize(actual), "\n"), string.split(normalize(expected), "\n")
	for i = 1, math.max(#a, #e) do
		if a[i] ~= e[i] then
			return string.format(" (first difference at line %d: Studio has %q, expected %q)", i, (a[i] or "<end>"):sub(1, 80), (e[i] or "<end>"):sub(1, 80))
		end
	end
	return ""
end

------------------------------------------------------------ checks (read-only)

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, anyOf in ipairs(REQUIRES) do
	local found = false
	for _, name in ipairs(anyOf) do
		if ServerStorage:FindFirstChild(name) then
			found = true
		end
	end
	if not found then
		return fail("ServerStorage." .. table.concat(anyOf, " / ") .. " not found: install the prerequisite first")
	end
end
for _, name in ipairs(FORBIDS) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists (already installed, or a later milestone is: roll that back first)")
	end
end

-- "script:Name" = the one Script with that name under ServerScriptService or
-- Workspace; "localscript:Name" = the one LocalScript with that name under
-- StarterPlayer, StarterGui or ReplicatedFirst; otherwise a path from a
-- service, e.g. "ReplicatedStorage/AquariumCycle/Config"
local function locate(spec)
	local where = spec.where
	local target
	if where:sub(1, 12) == "localscript:" then
		local name = where:sub(13)
		local found = {}
		for _, service in ipairs({ "StarterPlayer", "StarterGui", "ReplicatedFirst" }) do
			for _, d in ipairs(game:GetService(service):GetDescendants()) do
				if d.Name == name and d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 LocalScript named %s, found %d", name, #found)
		end
		target = found[1]
	elseif where:sub(1, 7) == "script:" then
		local name = where:sub(8)
		local found = {}
		for _, container in ipairs({ game:GetService("ServerScriptService"), workspace }) do
			for _, d in ipairs(container:GetDescendants()) do
				if d.Name == name and d:IsA("Script") and not d:IsA("LocalScript") then
					table.insert(found, d)
				end
			end
		end
		if #found ~= 1 then
			return nil, string.format("expected exactly 1 Script named %s, found %d", name, #found)
		end
		target = found[1]
	else
		local parts = string.split(where, "/")
		local node = game:GetService(parts[1])
		for i = 2, #parts do
			if parts[i] == "StarterPlayerScripts" then
				node = node and node:FindFirstChildOfClass("StarterPlayerScripts")
			else
				node = node and node:FindFirstChild(parts[i])
			end
		end
		if not node then
			return nil, where:gsub("/", ".") .. " not found"
		end
		target = node
	end
	if not target:IsA(spec.class) then
		return nil, target:GetFullName() .. " is not a " .. spec.class
	end
	if spec.tag then
		local holder = if spec.tagOnParent then target.Parent else target
		if not (holder and holder:GetAttribute(spec.tag) == true) then
			return nil, target:GetFullName() .. " is not tagged " .. spec.tag .. " (not ours)"
		end
	end
	return target
end

for _, entry in ipairs(UNCHANGED) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	if normalize(target.Source) ~= normalize(entry.source) then
		return fail(target:GetFullName() .. " is not the expected version (" .. entry.key .. ")" .. firstDiff(target.Source, entry.source) .. "; send the current source")
	end
end
local changes = {}
for _, entry in ipairs(CHANGES) do
	local target, why = locate(entry)
	if not target then
		return fail(why)
	end
	local list = entry.variants or { { old = entry.old, new = entry.new } }
	local pick
	for _, v in ipairs(list) do
		if normalize(target.Source) == normalize(v.old) then
			pick = v
			break
		end
	end
	if not pick then
		return fail(target:GetFullName() .. " is not an expected version (" .. entry.key .. ")" .. firstDiff(target.Source, list[1].old) .. "; send the current source")
	end
	table.insert(changes, { target = target, key = entry.key .. (if pick.label then "_" .. pick.label else ""), new = pick.new })
end
local adds = {}
for _, spec in ipairs(ADDS) do
	local parent, why = locate({ where = spec.where, class = "Instance" })
	if not parent then
		return fail(why)
	end
	local existing = parent:FindFirstChild(spec.name)
	if existing then
		return fail(existing:GetFullName() .. " already exists (installed already, or someone else's; remove or rename it first)")
	end
	table.insert(adds, { parent = parent, spec = spec })
end

------------------------------------------------------------ update

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

-- a disabled, childless copy holding one source
local function copyOf(target, name, source)
	local c = Instance.new(target.ClassName)
	c.Name = name
	c.Source = source
	if c:IsA("Script") or c:IsA("LocalScript") then
		c.Enabled = false
	end
	return c
end

local originals = {}
local backup
local built, buildErr = pcall(function()
	backup = Instance.new("Folder")
	backup.Name = BACKUP
	backup:SetAttribute("EconomyOwned", true)
	backup:SetAttribute("Installer", NAME)
	for i, change in ipairs(changes) do
		originals[i] = change.target.Source
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_%s", i, change.key)
		entry:SetAttribute("TargetPath", change.target:GetFullName())
		local targetValue = Instance.new("ObjectValue")
		targetValue.Name = "Target"
		targetValue.Value = change.target
		targetValue.Parent = entry
		copyOf(change.target, "Before", originals[i]).Parent = entry
		change.target.Source = change.new
		copyOf(change.target, "After", change.target.Source).Parent = entry
		entry.Parent = backup
	end
	for i, add in ipairs(adds) do
		local inst = Instance.new(add.spec.class)
		inst.Name = add.spec.name
		inst.Source = add.spec.source
		inst:SetAttribute("EconomyOwned", true)
		local entry = Instance.new("Folder")
		entry.Name = string.format("%02d_add_%s", #changes + i, add.spec.name)
		local addedValue = Instance.new("ObjectValue")
		addedValue.Name = "Added"
		addedValue.Value = inst
		addedValue.Parent = entry
		copyOf(inst, "After", add.spec.source).Parent = entry
		entry.Parent = backup
		inst.Parent = add.parent
		add.inst = inst
	end
	backup.Parent = ServerStorage
end)

if not built then
	for i, change in ipairs(changes) do
		if originals[i] then
			pcall(function()
				change.target.Source = originals[i]
			end)
		end
	end
	for _, add in ipairs(adds) do
		if add.inst then
			pcall(function()
				add.inst:Destroy()
			end)
		end
	end
	if backup then
		pcall(function()
			backup:Destroy()
		end)
	end
end

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if built then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif built then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not built then
	return warn("[" .. NAME .. "] Failed and rolled back: " .. tostring(buildErr))
end
print("[" .. NAME .. "] Installed:")
for _, change in ipairs(changes) do
	print("  updated " .. change.target:GetFullName() .. " (" .. change.key .. ")")
end
for _, add in ipairs(adds) do
	print("  added   " .. add.inst:GetFullName())
end
print("  backup  ServerStorage." .. BACKUP .. " (RollbackBotRecovery.lua restores the previous sources)")
