--[[
	RollbackUpgradeBoard.lua - GENERATED by tools/economy/build/build_updates.py.
	Reverses InstallUpgradeBoard.lua: every script it changed gets its recorded
	Before source back, every object it added is removed (only if it is
	still exactly as added), then ServerStorage.EconomyUpgradeBoardBackup is removed.
	Nothing else is touched (earlier installs and their backups stay).
	HOW TO RUN: stop Play, paste into the Studio Command Bar (Edit mode).

	Safety: if a script was edited after the install (its source no longer
	matches the recorded After copy), nothing is changed unless
	FORCE_RESTORE. Roll back later milestones FIRST. Saved Money is kept.
]]

local FORCE_RESTORE = false

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local RunService = game:GetService("RunService")
local ServerStorage = game:GetService("ServerStorage")

local NAME = "RollbackUpgradeBoard"
local BACKUP = "EconomyUpgradeBoardBackup"
local LATER = {  }

local function fail(msg)
	warn("[" .. NAME .. "] " .. msg .. " - nothing changed.")
end

local function normalize(s)
	s = s:gsub("\r", "")
	s = s:gsub("[ \t]+\n", "\n")
	s = s:gsub("%s+$", "")
	return s
end

if RunService:IsRunning() then
	return fail("stop Play first (run this in Edit mode)")
end
for _, name in ipairs(LATER) do
	if ServerStorage:FindFirstChild(name) then
		return fail("ServerStorage." .. name .. " exists: roll that milestone back first")
	end
end

local backup = ServerStorage:FindFirstChild(BACKUP)
if not backup or backup:GetAttribute("EconomyOwned") ~= true then
	return fail("ServerStorage." .. BACKUP .. " not found (not installed?)")
end

local restores, removals = {}, {}
for _, entry in ipairs(backup:GetChildren()) do
	local addedValue = entry:FindFirstChild("Added")
	if addedValue then
		local inst = addedValue:IsA("ObjectValue") and addedValue.Value
		local after = entry:FindFirstChild("After")
		if inst and inst:IsDescendantOf(game) then
			if inst:GetAttribute("EconomyOwned") ~= true then
				return fail(inst:GetFullName() .. " is not tagged EconomyOwned; remove it by hand if it is ours")
			end
			if not (after and normalize(inst.Source) == normalize(after.Source)) and not FORCE_RESTORE then
				return fail(inst:GetFullName() .. " was edited after the install; set FORCE_RESTORE = true to remove anyway")
			end
			table.insert(removals, inst)
		end
		continue
	end
	local targetValue = entry:FindFirstChild("Target")
	local target = targetValue and targetValue:IsA("ObjectValue") and targetValue.Value
	local before = entry:FindFirstChild("Before")
	local after = entry:FindFirstChild("After")
	if not (target and target:IsA("LuaSourceContainer") and target:IsDescendantOf(game)) then
		return fail(entry.Name .. ": target was moved or deleted; restore it by hand from " .. entry:GetFullName())
	end
	if not (before and before:IsA("LuaSourceContainer") and after and after:IsA("LuaSourceContainer")) then
		return fail(entry.Name .. ": backup copies are missing")
	end
	if normalize(target.Source) ~= normalize(after.Source) and not FORCE_RESTORE then
		return fail(target:GetFullName() .. " was edited after the install; set FORCE_RESTORE = true to restore anyway")
	end
	table.insert(restores, { target = target, source = before.Source })
end
if #restores == 0 and #removals == 0 then
	return fail("ServerStorage." .. BACKUP .. " is empty")
end

local recording
local ok = pcall(function()
	recording = ChangeHistoryService:TryBeginRecording(NAME)
end)
if not ok or not recording then
	recording = nil
	pcall(function()
		ChangeHistoryService:SetWaypoint("Before " .. NAME)
	end)
end

local done, err = pcall(function()
	for _, r in ipairs(restores) do
		r.target.Source = r.source
	end
	for _, inst in ipairs(removals) do
		inst:Destroy()
	end
	backup:Destroy()
end)

if recording then
	ChangeHistoryService:FinishRecording(
		recording,
		if done then Enum.FinishRecordingOperation.Commit else Enum.FinishRecordingOperation.Cancel
	)
elseif done then
	pcall(function()
		ChangeHistoryService:SetWaypoint(NAME)
	end)
end

if not done then
	return warn("[" .. NAME .. "] Failed: " .. tostring(err))
end
print(string.format("[%s] Restored %d script(s), removed %d added object(s). Saved Money is kept.", NAME, #restores, #removals))
